diary off;

clear;
clc;
close all;

%% Project paths
studyFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(studyFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Load public feasibility targets and authoritative model version
targets = cf34_10e_multipoint_targets();
baselineCfg = baseline_engine();

caseTag = "cf34_target_audit";
modelVersion = string(baselineCfg.meta.model_version);

%% Create output folders
runOutput = create_run_output_folders( ...
    projectRoot, ...
    modelVersion);

fileSuffix = ...
    caseTag + "_" + runOutput.file_tag;

commandWindowPath = fullfile( ...
    runOutput.data_folder, ...
    "command_window_" + fileSuffix + ".txt");

diary(char(commandWindowPath));

try
    fprintf("\nCF34-10E multi-point target audit started\n");
    fprintf("==================================================\n");
    fprintf("Model version:       %s\n", runOutput.version_tag);
    fprintf("Run number:          %02d\n", runOutput.run_number);
    fprintf("Engine variant:      %s\n", ...
        targets.metadata.engine_variant);
    fprintf("Primary EDB UID:     %s\n", ...
        targets.metadata.primary_edb_uid);
    fprintf("EDB release:         %s\n\n", ...
        targets.metadata.edb_release);

    %% Rating table
    ratingName = [
        targets.ratings.maximum_takeoff_apr.name
        targets.ratings.normal_takeoff.name
        targets.ratings.maximum_continuous.name
    ];

    thrust_kN = [
        targets.ratings.maximum_takeoff_apr.thrust_N / 1000
        targets.ratings.normal_takeoff.thrust_N_edb / 1000
        targets.ratings.maximum_continuous.thrust_N / 1000
    ];

    flatRatingTemperature_K = [
        targets.ratings.maximum_takeoff_apr.flat_rating_temperature_K
        NaN
        targets.ratings.maximum_continuous.flat_rating_temperature_K
    ];

    pedigree = [
        targets.ratings.maximum_takeoff_apr.pedigree
        targets.ratings.normal_takeoff.pedigree
        targets.ratings.maximum_continuous.pedigree
    ];

    ratingTable = table( ...
        ratingName, ...
        thrust_kN, ...
        flatRatingTemperature_K, ...
        pedigree, ...
        'VariableNames', { ...
            'Rating', ...
            'Thrust_kN', ...
            'FlatRatingTemperature_K', ...
            'Pedigree'});

    %% Primary EDB point table
    edbPointTable = targets.edb.primary.points;

    %% Unique-configuration envelope table
    envelope = ...
        targets.edb.unique_configuration_envelope;

    envelopeTable = table( ...
        envelope.mode, ...
        envelope.minimum_fuel_flow_kg_s, ...
        envelope.mean_fuel_flow_kg_s, ...
        envelope.maximum_fuel_flow_kg_s, ...
        'VariableNames', { ...
            'Mode', ...
            'MinimumFuelFlow_kg_s', ...
            'MeanFuelFlow_kg_s', ...
            'MaximumFuelFlow_kg_s'});

    %% Audit checks
    checkName = strings(0, 1);
    checkPassed = false(0, 1);
    checkDetail = strings(0, 1);

    add_check( ...
        "Four primary ICAO LTO points are present", ...
        height(edbPointTable) == 4, ...
        "Expected takeoff, climb-out, approach, and idle.");

    expectedRecommendedUse = [ ...
        "Diagnostic feasibility target"
        "Diagnostic feasibility target"
        "Diagnostic feasibility target"
        "Holdout"];

    add_check( ...
        "EDB target classifications match the finalized v0.6 scope", ...
        isequal( ...
            edbPointTable.RecommendedUse, ...
            expectedRecommendedUse), ...
        "Expected three diagnostic feasibility targets and one holdout.");

    feasibilityLabels = lower( ...
        edbPointTable.RecommendedUse(1:3));

    add_check( ...
        "EDB feasibility targets reject accepted calibration labels", ...
        ~any(contains(feasibilityLabels, "accepted") ...
            | contains(feasibilityLabels, "calibrated") ...
            | contains(feasibilityLabels, "validated")), ...
        "No EDB feasibility target may be accepted, calibrated, or validated.");

    add_check( ...
        "Primary thrust decreases with power setting", ...
        all(diff(edbPointTable.Thrust_N) < 0), ...
        "Thrust should decrease from takeoff through idle.");

    add_check( ...
        "Primary fuel flow decreases with power setting", ...
        all(diff(edbPointTable.FuelFlow_kg_s) < 0), ...
        "Fuel flow should decrease from takeoff through idle.");

    add_check( ...
        "All thrust and fuel-flow targets are positive", ...
        all(edbPointTable.Thrust_N > 0) ...
        && all(edbPointTable.FuelFlow_kg_s > 0), ...
        "No target may be zero or negative.");

    add_check( ...
        "Derived TSFC values are finite and positive", ...
        all(isfinite(edbPointTable.DerivedTSFC_g_kN_s)) ...
        && all(edbPointTable.DerivedTSFC_g_kN_s > 0), ...
        "Every primary EDB point must have a usable derived TSFC.");

    add_check( ...
        "Primary EDB fuel flow lies inside the unique-configuration envelope", ...
        all(edbPointTable.FuelFlow_kg_s ...
            >= envelopeTable.MinimumFuelFlow_kg_s - 1e-12) ...
        && all(edbPointTable.FuelFlow_kg_s ...
            <= envelopeTable.MaximumFuelFlow_kg_s + 1e-12), ...
        "Primary values must fall within the retained E7 configuration range.");

    add_check( ...
        "Certified rating ordering is physical", ...
        thrust_kN(1) > thrust_kN(2) ...
        && thrust_kN(2) > thrust_kN(3), ...
        "Expected APR > normal takeoff > maximum continuous.");

    add_check( ...
        "Public maximum and EDB rated-point descriptors remain separate", ...
        targets.cycle.public_maximum.bypass_ratio ...
            ~= targets.cycle.edb_rated_point.bypass_ratio ...
        && targets.cycle.public_maximum.overall_pressure_ratio ...
            ~= targets.cycle.edb_rated_point.pressure_ratio, ...
        "Do not collapse 5.4/29.0 and 5.09/27.3 into one fixed target.");

    add_check( ...
        "Cruise hold-out target is populated", ...
        targets.cruise.altitude_ft == 35000 ...
        && abs(targets.cruise.flight_mach - 0.8) < 1e-12 ...
        && targets.cruise.tsfc_g_kN_s > 0, ...
        "Expected 35,000 ft, Mach 0.8, and positive cruise TSFC.");

    auditTable = table( ...
        checkName, ...
        checkPassed, ...
        checkDetail, ...
        'VariableNames', { ...
            'Check', ...
            'Passed', ...
            'Detail'});

    %% Display results
    fprintf("Certified and public ratings\n");
    fprintf("--------------------------------------------------\n");
    disp(ratingTable);

    fprintf("Primary ICAO EDB feasibility targets\n");
    fprintf("--------------------------------------------------\n");
    disp(edbPointTable);

    fprintf("Unique CF34-10E7 configuration envelope\n");
    fprintf("--------------------------------------------------\n");
    disp(envelopeTable);

    fprintf("Target audit checks\n");
    fprintf("--------------------------------------------------\n");
    disp(auditTable);

    passedCount = nnz(auditTable.Passed);
    failedCount = height(auditTable) - passedCount;

    fprintf("Audit summary\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Passed: %d\n", passedCount);
    fprintf("Failed: %d\n", failedCount);
    fprintf("Total:  %d\n\n", height(auditTable));

    if failedCount > 0
        failedRows = auditTable(~auditTable.Passed, :);
        disp(failedRows);

        error( ...
            "CF34 target audit failed: %d check(s) failed.", ...
            failedCount);
    end

    %% Save outputs
    ratingCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "ratings_" + fileSuffix + ".csv");

    edbCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "edb_points_" + fileSuffix + ".csv");

    envelopeCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "fuel_flow_envelope_" + fileSuffix + ".csv");

    auditCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "target_audit_" + fileSuffix + ".csv");

    resultsPath = fullfile( ...
        runOutput.data_folder, ...
        "target_package_" + fileSuffix + ".mat");

    writetable(ratingTable, ratingCsvPath);
    writetable(edbPointTable, edbCsvPath);
    writetable(envelopeTable, envelopeCsvPath);
    writetable(auditTable, auditCsvPath);

    save( ...
        resultsPath, ...
        "targets", ...
        "ratingTable", ...
        "edbPointTable", ...
        "envelopeTable", ...
        "auditTable", ...
        "caseTag", ...
        "modelVersion", ...
        "runOutput");

    fprintf("Saved output files\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Ratings CSV:    %s\n", ratingCsvPath);
    fprintf("EDB points CSV: %s\n", edbCsvPath);
    fprintf("Envelope CSV:   %s\n", envelopeCsvPath);
    fprintf("Audit CSV:      %s\n", auditCsvPath);
    fprintf("Target MAT:     %s\n", resultsPath);
    fprintf("Command log:    %s\n", commandWindowPath);
    fprintf("==================================================\n");
    fprintf("CF34-10E multi-point target audit PASSED\n\n");

    diary off;

catch ME
    fprintf(2, ...
        "\nCF34-10E multi-point target audit failed.\n\n");

    fprintf(2, "%s\n", ...
        getReport( ...
            ME, ...
            "extended", ...
            "hyperlinks", ...
            "off"));

    diary off;
    rethrow(ME);
end


function add_check(name, condition, detail)
%ADD_CHECK Append one audit check to the parent workspace.

checkName = evalin("caller", "checkName");
checkPassed = evalin("caller", "checkPassed");
checkDetail = evalin("caller", "checkDetail");

checkName(end + 1, 1) = string(name);
checkPassed(end + 1, 1) = logical(condition);
checkDetail(end + 1, 1) = string(detail);

assignin("caller", "checkName", checkName);
assignin("caller", "checkPassed", checkPassed);
assignin("caller", "checkDetail", checkDetail);

end
