diary off;

clear;
clc;
close all;

%% Project paths
studyFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(studyFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Load model and public reference
cfgBase = baseline_engine();
ref = cf34_10e_reference();

caseTag = "cf34_airflow_calibration";

targetThrust_N = ...
    ref.performance.sea_level_static_thrust_N;

%% Solver settings
minimumCoreAirflow_kg_s = 25;
maximumCoreAirflow_kg_s = 65;

thrustTolerance_N = 1.0;

solverOptions = optimset( ...
    "Display", "off", ...
    "TolX", 1e-8);

%% Create output folders
runOutput = create_run_output_folders( ...
    projectRoot, ...
    cfgBase.meta.model_version);

fileSuffix = ...
    caseTag + "_" + runOutput.file_tag;

%% Start Command Window recording
commandWindowPath = fullfile( ...
    runOutput.data_folder, ...
    "command_window_" + fileSuffix + ".txt");

diary(char(commandWindowPath));

try
    fprintf("\nCF34-10E core-airflow calibration started\n");
    fprintf("==================================================\n");
    fprintf("Model version:    %s\n", runOutput.version_tag);
    fprintf("Run number:       %02d\n", runOutput.run_number);
    fprintf("Reference model:  %s\n", ...
        ref.metadata.calibration_variant);
    fprintf("Target thrust:    %.3f kN\n", ...
        targetThrust_N / 1000);
    fprintf("Reference BPR:    %.3f\n", ...
        ref.performance.bypass_ratio);
    fprintf("Reference OPR:    %.3f\n\n", ...
        ref.performance.overall_pressure_ratio);

    %% Save pre-calibration configuration
    configurationPath = fullfile( ...
        runOutput.data_folder, ...
        "configuration_" + fileSuffix + ".mat");

    save( ...
        configurationPath, ...
        "cfgBase", ...
        "ref", ...
        "targetThrust_N", ...
        "minimumCoreAirflow_kg_s", ...
        "maximumCoreAirflow_kg_s", ...
        "thrustTolerance_N", ...
        "caseTag", ...
        "runOutput");

    %% Evaluate uncalibrated model
    initialResults = run_turbofan(cfgBase);

    initialThrust_N = ...
        initialResults.performance.net_thrust_N;

    initialError_percent = ...
        100 * (initialThrust_N - targetThrust_N) ...
        / targetThrust_N;

    %% Create airflow residual
    thrustResidual = @(coreAirflow_kg_s) ...
        evaluate_airflow_residual( ...
            coreAirflow_kg_s, ...
            cfgBase, ...
            targetThrust_N);

    lowerResidual_N = ...
        thrustResidual(minimumCoreAirflow_kg_s);

    upperResidual_N = ...
        thrustResidual(maximumCoreAirflow_kg_s);

    if lowerResidual_N * upperResidual_N > 0
        error( ...
            "Unable to bracket core-airflow solution. " + ...
            "Residuals are %.3f N and %.3f N.", ...
            lowerResidual_N, ...
            upperResidual_N);
    end

    %% Solve calibrated core airflow
    calibratedCoreAirflow_kg_s = fzero( ...
        thrustResidual, ...
        [minimumCoreAirflow_kg_s, maximumCoreAirflow_kg_s], ...
        solverOptions);

    cfgCalibrated = cfgBase;

    cfgCalibrated.engine.core_airflow_kg_s = ...
        calibratedCoreAirflow_kg_s;

    calibratedResults = ...
        run_turbofan(cfgCalibrated);

    calibratedThrust_N = ...
        calibratedResults.performance.net_thrust_N;

    calibratedThrustError_N = ...
        calibratedThrust_N - targetThrust_N;

    calibratedError_percent = ...
        100 * calibratedThrustError_N ...
        / targetThrust_N;

    if abs(calibratedThrustError_N) > thrustTolerance_N
        error( ...
            "Calibrated thrust error exceeds tolerance. " + ...
            "Error is %.6f N.", ...
            calibratedThrustError_N);
    end

    %% Calibration comparison table
    caseName = [
        "Initial CF34 configuration"
        "Calibrated CF34 configuration"
        "Public CF34-10E7 target"
    ];

    coreAirflow_kg_s = [
        cfgBase.engine.core_airflow_kg_s
        calibratedCoreAirflow_kg_s
        NaN
    ];

    bypassRatio = [
        cfgBase.engine.bypass_ratio
        cfgCalibrated.engine.bypass_ratio
        ref.performance.bypass_ratio
    ];

    overallPressureRatio = [
        cfgBase.engine.fan_pressure_ratio ...
            * cfgBase.engine.lpc_pressure_ratio ...
            * cfgBase.engine.hpc_pressure_ratio

        cfgCalibrated.engine.fan_pressure_ratio ...
            * cfgCalibrated.engine.lpc_pressure_ratio ...
            * cfgCalibrated.engine.hpc_pressure_ratio

        ref.performance.overall_pressure_ratio
    ];

    thrust_kN = [
        initialThrust_N / 1000
        calibratedThrust_N / 1000
        targetThrust_N / 1000
    ];

    thrustError_percent = [
        initialError_percent
        calibratedError_percent
        0
    ];

    calibrationTable = table( ...
        caseName, ...
        coreAirflow_kg_s, ...
        bypassRatio, ...
        overallPressureRatio, ...
        thrust_kN, ...
        thrustError_percent, ...
        'VariableNames', { ...
            'Case', ...
            'CoreAirflow_kg_s', ...
            'BypassRatio', ...
            'OverallPressureRatio', ...
            'Thrust_kN', ...
            'ThrustError_percent'});

    disp(calibrationTable);

    %% Save CSV
    csvPath = fullfile( ...
        runOutput.data_folder, ...
        "airflow_calibration_" + fileSuffix + ".csv");

    writetable(calibrationTable, csvPath);

    %% Save complete MATLAB output
    resultsPath = fullfile( ...
        runOutput.data_folder, ...
        "calibration_results_" + fileSuffix + ".mat");

    save( ...
        resultsPath, ...
        "cfgBase", ...
        "cfgCalibrated", ...
        "ref", ...
        "initialResults", ...
        "calibratedResults", ...
        "calibratedCoreAirflow_kg_s", ...
        "calibrationTable", ...
        "caseTag", ...
        "runOutput");

    %% Print recommended input
    fprintf("Calibration result\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Initial core airflow:    %.6f kg/s\n", ...
        cfgBase.engine.core_airflow_kg_s);

    fprintf("Calibrated core airflow: %.6f kg/s\n", ...
        calibratedCoreAirflow_kg_s);

    fprintf("Initial thrust:          %.6f kN\n", ...
        initialThrust_N / 1000);

    fprintf("Calibrated thrust:       %.6f kN\n", ...
        calibratedThrust_N / 1000);

    fprintf("Target thrust:           %.6f kN\n", ...
        targetThrust_N / 1000);

    fprintf("Final thrust error:      %+.6f N\n\n", ...
        calibratedThrustError_N);

    fprintf("Do not edit baseline_engine.m until this result " + ...
        "has been reviewed.\n\n");

    fprintf("Saved output files\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Configuration: %s\n", configurationPath);
    fprintf("Results MAT:   %s\n", resultsPath);
    fprintf("Results CSV:   %s\n", csvPath);
    fprintf("Command log:   %s\n", commandWindowPath);
    fprintf("==================================================\n");
    fprintf("CF34-10E core-airflow calibration complete\n\n");

    diary off;

catch ME
    fprintf(2, ...
        "\nCF34-10E airflow calibration failed.\n\n");

    fprintf(2, "%s\n", ...
        getReport( ...
            ME, ...
            "extended", ...
            "hyperlinks", ...
            "off"));

    diary off;
    rethrow(ME);
end


function residual_N = evaluate_airflow_residual( ...
    coreAirflow_kg_s, cfg, targetThrust_N)
%EVALUATE_AIRFLOW_RESIDUAL Calculate thrust error at a given core flow.

cfg.engine.core_airflow_kg_s = ...
    coreAirflow_kg_s;

results = ...
    run_turbofan(cfg);

residual_N = ...
    results.performance.net_thrust_N ...
    - targetThrust_N;

end