diary off;

clear;
clc;
close all;

%% Project paths
studyFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(studyFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Run inherited APR design point
cfg = baseline_engine();
cfg = apply_cf34_operating_point( ...
    cfg, ...
    "maximum_takeoff_apr");

results = run_turbofan(cfg);

caseTag = "cf34_design_geometry_capture";

%% Create output folders
runOutput = create_run_output_folders( ...
    projectRoot, ...
    cfg.meta.model_version);

fileSuffix = ...
    caseTag + "_" + runOutput.file_tag;

commandWindowPath = fullfile( ...
    runOutput.data_folder, ...
    "command_window_" + fileSuffix + ".txt");

diary(char(commandWindowPath));

try
    fprintf("\nCF34-10E design-geometry capture started\n");
    fprintf("==================================================\n");
    fprintf("Model version:      %s\n", runOutput.version_tag);
    fprintf("Run number:         %02d\n", runOutput.run_number);
    fprintf("Operating point:    %s\n\n", ...
        results.operating_point.name);

    %% Capture nozzle geometry from the calibrated APR point
    coreArea_m2 = ...
        results.stations.station9.area_m2;

    bypassArea_m2 = ...
        results.stations.station19.area_m2;

    coreEquivalentDiameter_m = ...
        sqrt(4 * coreArea_m2 / pi);

    bypassEquivalentDiameter_m = ...
        sqrt(4 * bypassArea_m2 / pi);

    stream = [
        "Core"
        "Bypass"
    ];

    nozzleArea_m2 = [
        coreArea_m2
        bypassArea_m2
    ];

    equivalentDiameter_m = [
        coreEquivalentDiameter_m
        bypassEquivalentDiameter_m
    ];

    massFlow_kg_s = [
        results.mass.mdot_hpt_kg_s
        results.mass.mdot_bypass_air_kg_s
    ];

    inletTotalTemperature_K = [
        results.stations.station8.Tt_K
        results.stations.station18.Tt_K
    ];

    inletTotalPressure_kPa = [
        results.stations.station8.Pt_Pa / 1000
        results.stations.station18.Pt_Pa / 1000
    ];

    exitMach = [
        results.stations.station9.Mach
        results.stations.station19.Mach
    ];

    exitPressure_kPa = [
        results.stations.station9.P_Pa / 1000
        results.stations.station19.P_Pa / 1000
    ];

    exitVelocity_m_s = [
        results.stations.station9.velocity_m_s
        results.stations.station19.velocity_m_s
    ];

    isChoked = [
        results.stations.station9.is_choked
        results.stations.station19.is_choked
    ];

    pressureRecovery = [
        cfg.loss.core_nozzle_pressure_recovery
        cfg.loss.bypass_nozzle_pressure_recovery
    ];

    geometryTable = table( ...
        stream, ...
        nozzleArea_m2, ...
        equivalentDiameter_m, ...
        massFlow_kg_s, ...
        inletTotalTemperature_K, ...
        inletTotalPressure_kPa, ...
        exitMach, ...
        exitPressure_kPa, ...
        exitVelocity_m_s, ...
        isChoked, ...
        pressureRecovery, ...
        'VariableNames', { ...
            'Stream', ...
            'NozzleArea_m2', ...
            'EquivalentDiameter_m', ...
            'MassFlow_kg_s', ...
            'InletTotalTemperature_K', ...
            'InletTotalPressure_kPa', ...
            'ExitMach', ...
            'ExitPressure_kPa', ...
            'ExitVelocity_m_s', ...
            'IsChoked', ...
            'PressureRecovery'});

    %% Package exact design-geometry record
    designGeometry = struct();

    designGeometry.metadata.engine_variant = ...
        results.operating_point.engine_variant;

    designGeometry.metadata.operating_point_id = ...
        results.operating_point.id;

    designGeometry.metadata.operating_point_name = ...
        results.operating_point.name;

    designGeometry.metadata.model_version = ...
        string(cfg.meta.model_version);

    designGeometry.metadata.status = ...
        "Captured from calibrated APR design point; not yet enforced off design";

    designGeometry.ambient.temperature_K = ...
        results.atm.temperature_K;

    designGeometry.ambient.pressure_Pa = ...
        results.atm.pressure_Pa;

    designGeometry.core_nozzle.area_m2 = ...
        coreArea_m2;

    designGeometry.core_nozzle.equivalent_diameter_m = ...
        coreEquivalentDiameter_m;

    designGeometry.core_nozzle.design_mass_flow_kg_s = ...
        results.mass.mdot_hpt_kg_s;

    designGeometry.core_nozzle.design_is_choked = ...
        results.stations.station9.is_choked;

    designGeometry.bypass_nozzle.area_m2 = ...
        bypassArea_m2;

    designGeometry.bypass_nozzle.equivalent_diameter_m = ...
        bypassEquivalentDiameter_m;

    designGeometry.bypass_nozzle.design_mass_flow_kg_s = ...
        results.mass.mdot_bypass_air_kg_s;

    designGeometry.bypass_nozzle.design_is_choked = ...
        results.stations.station19.is_choked;

    %% Display and basic checks
    disp(geometryTable);

    areaChecksPass = ...
        all(nozzleArea_m2 > 0) ...
        && all(isfinite(nozzleArea_m2));

    chokingChecksPass = ...
        results.stations.station9.is_choked ...
        && ~results.stations.station19.is_choked;

    fprintf("Geometry checks\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Positive finite areas:       %s\n", ...
        string(areaChecksPass));
    fprintf("Expected choking states:     %s\n", ...
        string(chokingChecksPass));
    fprintf("Core area:                   %.9f m^2\n", ...
        coreArea_m2);
    fprintf("Bypass area:                 %.9f m^2\n", ...
        bypassArea_m2);
    fprintf("Core equivalent diameter:    %.6f m\n", ...
        coreEquivalentDiameter_m);
    fprintf("Bypass equivalent diameter:  %.6f m\n\n", ...
        bypassEquivalentDiameter_m);

    if ~areaChecksPass
        error("Captured nozzle areas are invalid.");
    end

    if ~chokingChecksPass
        error( ...
            "APR choking states changed before geometry capture.");
    end

    %% Save outputs
    geometryCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "design_nozzle_geometry_" + fileSuffix + ".csv");

    resultsPath = fullfile( ...
        runOutput.data_folder, ...
        "design_geometry_" + fileSuffix + ".mat");

    configurationPath = fullfile( ...
        runOutput.data_folder, ...
        "configuration_" + fileSuffix + ".mat");

    writetable( ...
        geometryTable, ...
        geometryCsvPath);

    save( ...
        resultsPath, ...
        "designGeometry", ...
        "geometryTable", ...
        "results", ...
        "caseTag", ...
        "runOutput");

    save( ...
        configurationPath, ...
        "cfg", ...
        "caseTag", ...
        "runOutput");

    fprintf("Saved output files\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Configuration: %s\n", configurationPath);
    fprintf("Geometry MAT:  %s\n", resultsPath);
    fprintf("Geometry CSV:  %s\n", geometryCsvPath);
    fprintf("Command log:   %s\n", commandWindowPath);
    fprintf("==================================================\n");
    fprintf("CF34-10E design-geometry capture PASSED\n\n");

    diary off;

catch ME
    fprintf(2, ...
        "\nCF34-10E design-geometry capture failed.\n\n");

    fprintf(2, "%s\n", ...
        getReport( ...
            ME, ...
            "extended", ...
            "hyperlinks", ...
            "off"));

    diary off;
    rethrow(ME);
end
