diary off;

clear;
clc;
close all;

%% Project paths
studyFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(studyFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Run inherited APR design point
cfg = baseline_engine();
cfg = apply_cf34_operating_point( ...
    cfg, ...
    "maximum_takeoff_apr");

results = run_turbofan(cfg);

caseTag = "cf34_map_reference_capture";

%% Create output folders
runOutput = create_run_output_folders( ...
    projectRoot, ...
    cfg.meta.model_version);

fileSuffix = ...
    caseTag + "_" + runOutput.file_tag;

commandWindowPath = fullfile( ...
    runOutput.data_folder, ...
    "command_window_" + fileSuffix + ".txt");

diary(char(commandWindowPath));

try
    fprintf("\nCF34 component-map reference capture started\n");
    fprintf("==================================================\n");
    fprintf("Model version:      %s\n", runOutput.version_tag);
    fprintf("Run number:         %02d\n", runOutput.run_number);
    fprintf("Operating point:    %s\n", ...
        results.operating_point.name);
    fprintf("Reference T:        %.2f K\n", ...
        cfg.reference.temperature_K);
    fprintf("Reference P:        %.3f kPa\n\n", ...
        cfg.reference.pressure_Pa / 1000);

    %% Component inlet definitions
    component = [
        "Fan"
        "LPC"
        "HPC"
        "HPT"
        "LPT"
    ];

    spool = [
        "Low"
        "Low"
        "High"
        "High"
        "Low"
    ];

    inletStation = [
        "2"
        "21"
        "25"
        "41"
        "45"
    ];

    inletTotalTemperature_K = [
        results.stations.station2.Tt_K
        results.stations.station21.Tt_K
        results.stations.station25.Tt_K
        results.stations.station41.Tt_K
        results.stations.station45.Tt_K
    ];

    inletTotalPressure_kPa = [
        results.stations.station2.Pt_Pa
        results.stations.station21.Pt_Pa
        results.stations.station25.Pt_Pa
        results.stations.station41.Pt_Pa
        results.stations.station45.Pt_Pa
    ] / 1000;

    actualMassFlow_kg_s = [
        results.mass.mdot_total_air_kg_s
        results.mass.mdot_core_air_kg_s
        results.mass.mdot_core_air_kg_s
        results.mass.mdot_hpt_kg_s
        results.mass.mdot_hpt_kg_s
    ];

    shaftSpeed_rpm = [
        cfg.shaft.low_spool_rpm
        cfg.shaft.low_spool_rpm
        cfg.shaft.high_spool_rpm
        cfg.shaft.high_spool_rpm
        cfg.shaft.low_spool_rpm
    ];

    pressureRatioOrExpansionRatio = [
        results.stations.station21.pressure_ratio
        results.stations.station25.pressure_ratio
        results.stations.station3.pressure_ratio
        results.stations.station41.Pt_Pa ...
            / results.stations.station45.Pt_Pa
        results.stations.station45.Pt_Pa ...
            / results.stations.station5.Pt_Pa
    ];

    ratioDefinition = [
        "Pt_out / Pt_in"
        "Pt_out / Pt_in"
        "Pt_out / Pt_in"
        "Pt_in / Pt_out"
        "Pt_in / Pt_out"
    ];

    isentropicEfficiency = [
        results.stations.station21.isentropic_efficiency
        results.stations.station25.isentropic_efficiency
        results.stations.station3.isentropic_efficiency
        results.stations.station45.isentropic_efficiency
        results.stations.station5.isentropic_efficiency
    ];

    shaftPower_MW = [
        results.power.fan_W
        results.power.lpc_W
        results.power.hpc_W
        results.power.hpt_W
        results.power.lpt_W
    ] / 1e6;

    %% Calculate corrected quantities
    numberComponents = numel(component);

    theta = nan(numberComponents, 1);
    delta = nan(numberComponents, 1);
    correctedMassFlow_kg_s = nan(numberComponents, 1);
    correctedSpeed_rpm = nan(numberComponents, 1);

    correctedRecords = cell( ...
        numberComponents, ...
        1);

    for componentIndex = 1:numberComponents
        correctedRecords{componentIndex} = corrected_flow_speed( ...
            actualMassFlow_kg_s(componentIndex), ...
            shaftSpeed_rpm(componentIndex), ...
            inletTotalTemperature_K(componentIndex), ...
            inletTotalPressure_kPa(componentIndex) * 1000, ...
            cfg.reference.temperature_K, ...
            cfg.reference.pressure_Pa);

        theta(componentIndex) = ...
            correctedRecords{componentIndex}.theta;

        delta(componentIndex) = ...
            correctedRecords{componentIndex}.delta;

        correctedMassFlow_kg_s(componentIndex) = ...
            correctedRecords{componentIndex}.mass_flow_kg_s;

        correctedSpeed_rpm(componentIndex) = ...
            correctedRecords{componentIndex}.speed_rpm;
    end

    mapReferenceTable = table( ...
        component, ...
        spool, ...
        inletStation, ...
        inletTotalTemperature_K, ...
        inletTotalPressure_kPa, ...
        actualMassFlow_kg_s, ...
        shaftSpeed_rpm, ...
        theta, ...
        delta, ...
        correctedMassFlow_kg_s, ...
        correctedSpeed_rpm, ...
        pressureRatioOrExpansionRatio, ...
        ratioDefinition, ...
        isentropicEfficiency, ...
        shaftPower_MW, ...
        'VariableNames', { ...
            'Component', ...
            'Spool', ...
            'InletStation', ...
            'InletTotalTemperature_K', ...
            'InletTotalPressure_kPa', ...
            'ActualMassFlow_kg_s', ...
            'ShaftSpeed_rpm', ...
            'Theta', ...
            'Delta', ...
            'CorrectedMassFlow_kg_s', ...
            'CorrectedSpeed_rpm', ...
            'PressureRatioOrExpansionRatio', ...
            'RatioDefinition', ...
            'IsentropicEfficiency', ...
            'ShaftPower_MW'});

    disp(mapReferenceTable);

    %% Package design reference
    mapReference = struct();

    mapReference.metadata.engine_variant = ...
        results.operating_point.engine_variant;

    mapReference.metadata.operating_point_id = ...
        results.operating_point.id;

    mapReference.metadata.model_version = ...
        string(cfg.meta.model_version);

    mapReference.metadata.status = ...
        "Design-point reference for future generic-map scaling";

    mapReference.reference_temperature_K = ...
        cfg.reference.temperature_K;

    mapReference.reference_pressure_Pa = ...
        cfg.reference.pressure_Pa;

    for componentIndex = 1:numberComponents
        fieldName = char(lower(component(componentIndex)));

        mapReference.(fieldName).corrected = ...
            correctedRecords{componentIndex};

        mapReference.(fieldName).pressure_ratio_or_expansion_ratio = ...
            pressureRatioOrExpansionRatio(componentIndex);

        mapReference.(fieldName).ratio_definition = ...
            ratioDefinition(componentIndex);

        mapReference.(fieldName).isentropic_efficiency = ...
            isentropicEfficiency(componentIndex);

        mapReference.(fieldName).shaft_power_W = ...
            shaftPower_MW(componentIndex) * 1e6;
    end

    %% Verification checks
    finitePositivePass = ...
        all(isfinite(correctedMassFlow_kg_s)) ...
        && all(correctedMassFlow_kg_s > 0) ...
        && all(isfinite(correctedSpeed_rpm)) ...
        && all(correctedSpeed_rpm > 0);

    ratioPass = ...
        all(pressureRatioOrExpansionRatio > 1);

    spoolAssignmentPass = ...
        shaftSpeed_rpm(1) == cfg.shaft.low_spool_rpm ...
        && shaftSpeed_rpm(2) == cfg.shaft.low_spool_rpm ...
        && shaftSpeed_rpm(3) == cfg.shaft.high_spool_rpm ...
        && shaftSpeed_rpm(4) == cfg.shaft.high_spool_rpm ...
        && shaftSpeed_rpm(5) == cfg.shaft.low_spool_rpm;

    referenceStatePass = ...
        cfg.reference.temperature_K == 288.15 ...
        && cfg.reference.pressure_Pa == 101325;

    fprintf("Reference checks\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Finite positive corrected values: %s\n", ...
        string(finitePositivePass));
    fprintf("All component ratios above one:   %s\n", ...
        string(ratioPass));
    fprintf("Spool assignments correct:        %s\n", ...
        string(spoolAssignmentPass));
    fprintf("Standard reference state correct: %s\n\n", ...
        string(referenceStatePass));

    if ~( ...
            finitePositivePass ...
            && ratioPass ...
            && spoolAssignmentPass ...
            && referenceStatePass)
        error( ...
            "CF34 component-map reference verification failed.");
    end

    %% Save outputs
    csvPath = fullfile( ...
        runOutput.data_folder, ...
        "component_map_reference_" + fileSuffix + ".csv");

    resultsPath = fullfile( ...
        runOutput.data_folder, ...
        "component_map_reference_" + fileSuffix + ".mat");

    configurationPath = fullfile( ...
        runOutput.data_folder, ...
        "configuration_" + fileSuffix + ".mat");

    writetable( ...
        mapReferenceTable, ...
        csvPath);

    save( ...
        resultsPath, ...
        "mapReference", ...
        "mapReferenceTable", ...
        "results", ...
        "caseTag", ...
        "runOutput");

    save( ...
        configurationPath, ...
        "cfg", ...
        "caseTag", ...
        "runOutput");

    fprintf("Saved output files\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Configuration: %s\n", configurationPath);
    fprintf("Reference MAT: %s\n", resultsPath);
    fprintf("Reference CSV: %s\n", csvPath);
    fprintf("Command log:   %s\n", commandWindowPath);
    fprintf("==================================================\n");
    fprintf("CF34 component-map reference capture PASSED\n\n");

    diary off;

catch ME
    fprintf(2, ...
        "\nCF34 component-map reference capture failed.\n\n");

    fprintf(2, "%s\n", ...
        getReport( ...
            ME, ...
            "extended", ...
            "hyperlinks", ...
            "off"));

    diary off;
    rethrow(ME);
end
