diary off;

clear;
clc;
close all;

%% Project paths
% This script is stored inside the Studies folder.
studyFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(studyFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Base configuration
cfgBase = baseline_engine();

caseTag = "fixedThrust";

%% Cooling-bleed study definition
bleedFractions = linspace(0.00, 0.10, 21);
numberOfCases = numel(bleedFractions);

%% Solver settings
maximumTIT_K = 2200;
thrustTolerance_N = 1.0;

solverOptions = optimset( ...
    'Display', ...
    'off', ...
    'TolX', ...
    1e-6);

%% Create matching Data and Figures run folders
runOutput = create_run_output_folders( ...
    projectRoot, ...
    cfgBase.meta.model_version);

fileSuffix = ...
    caseTag + "_" + runOutput.file_tag;

%% Start Command Window recording
commandWindowPath = fullfile( ...
    runOutput.data_folder, ...
    "command_window_" + fileSuffix + ".txt");

diary(char(commandWindowPath));

try
    fprintf("\nFixed-thrust cooling-bleed sweep started\n");
    fprintf("==================================================\n");
    fprintf("Study:         %s\n", caseTag);
    fprintf("Model version: %s\n", runOutput.version_tag);
    fprintf("Run number:    %02d\n", runOutput.run_number);
    fprintf("Data folder:   %s\n", runOutput.data_folder);
    fprintf("Figure folder: %s\n\n", runOutput.figure_folder);

    %% Establish zero-bleed target thrust
    cfgBase.cooling.bleed_fraction = 0.0;

    baselineResults = run_turbofan(cfgBase);

    targetThrust_N = ...
        baselineResults.performance.net_thrust_N;

    baselineTIT_K = ...
        cfgBase.engine.combustor_exit_temperature_K;

    fprintf("Zero-bleed target thrust: %.3f kN\n", ...
        targetThrust_N / 1000);

    fprintf("Baseline combustor Tt:    %.2f K\n\n", ...
        baselineTIT_K);

    %% Save exact study configuration
    configurationPath = fullfile( ...
        runOutput.data_folder, ...
        "configuration_" + fileSuffix + ".mat");

    save( ...
        configurationPath, ...
        "cfgBase", ...
        "bleedFractions", ...
        "targetThrust_N", ...
        "baselineTIT_K", ...
        "maximumTIT_K", ...
        "thrustTolerance_N", ...
        "caseTag", ...
        "runOutput");

    %% Preallocate outputs
    bleedPercent = ...
        100 * bleedFractions(:);

    requiredTIT_K = ...
        zeros(numberOfCases, 1);

    mixedHPTInletTt_K = ...
        zeros(numberOfCases, 1);

    fuelFlow_kg_s = ...
        zeros(numberOfCases, 1);

    tsfc_g_kN_s = ...
        zeros(numberOfCases, 1);

    netThrust_kN = ...
        zeros(numberOfCases, 1);

    thrustError_N = ...
        zeros(numberOfCases, 1);

    coreExitVelocity_m_s = ...
        zeros(numberOfCases, 1);

    mixerPressureRecovery = ...
        zeros(numberOfCases, 1);

    mixerPressureLoss_percent = ...
        zeros(numberOfCases, 1);

    % Preserve complete engine results at every solved bleed fraction.
    caseResults = ...
        cell(numberOfCases, 1);

    %% Solve TIT required to hold thrust constant
    for i = 1:numberOfCases
        cfg = cfgBase;

        cfg.cooling.bleed_fraction = ...
            bleedFractions(i);

        if i == 1
            solvedTIT_K = ...
                baselineTIT_K;

        else
            thrustResidual = @(TIT_K) ...
                evaluate_thrust_residual( ...
                    TIT_K, ...
                    cfg, ...
                    targetThrust_N);

            lowerTIT_K = ...
                baselineTIT_K;

            upperTIT_K = ...
                maximumTIT_K;

            lowerResidual_N = ...
                thrustResidual(lowerTIT_K);

            upperResidual_N = ...
                thrustResidual(upperTIT_K);

            if abs(lowerResidual_N) <= thrustTolerance_N
                solvedTIT_K = lowerTIT_K;

            elseif lowerResidual_N * upperResidual_N > 0
                error( ...
                    "Unable to bracket the fixed-thrust TIT solution " + ...
                    "at %.2f percent cooling bleed. " + ...
                    "Residuals are %.3f N and %.3f N.", ...
                    bleedPercent(i), ...
                    lowerResidual_N, ...
                    upperResidual_N);

            else
                solvedTIT_K = fzero( ...
                    thrustResidual, ...
                    [lowerTIT_K, upperTIT_K], ...
                    solverOptions);
            end
        end

        cfg.engine.combustor_exit_temperature_K = ...
            solvedTIT_K;

        cfg.engine.turbine_inlet_temperature_K = ...
            solvedTIT_K;

        results = run_turbofan(cfg);

        caseResults{i} = results;

        requiredTIT_K(i) = ...
            solvedTIT_K;

        mixedHPTInletTt_K(i) = ...
            results.stations.station41.Tt_K;

        fuelFlow_kg_s(i) = ...
            results.mass.mdot_fuel_kg_s;

        tsfc_g_kN_s(i) = ...
            results.performance.tsfc_g_kN_s;

        netThrust_kN(i) = ...
            results.performance.net_thrust_N / 1000;

        thrustError_N(i) = ...
            results.performance.net_thrust_N ...
            - targetThrust_N;

        coreExitVelocity_m_s(i) = ...
            results.stations.station9.velocity_m_s;

        mixerPressureRecovery(i) = ...
            results.stations.station41.pressure_recovery;

        mixerPressureLoss_percent(i) = ...
            100 * results.stations.station41.pressure_loss_fraction;
    end

    %% Validate fixed-thrust solution
    maximumThrustError_N = ...
        max(abs(thrustError_N));

    if maximumThrustError_N > thrustTolerance_N
        error( ...
            "Fixed-thrust sweep exceeded the %.3f N tolerance. " + ...
            "Maximum error was %.3f N.", ...
            thrustTolerance_N, ...
            maximumThrustError_N);
    end

    %% Results table
    fixedThrustTable = table( ...
        bleedPercent, ...
        requiredTIT_K, ...
        mixedHPTInletTt_K, ...
        fuelFlow_kg_s, ...
        tsfc_g_kN_s, ...
        netThrust_kN, ...
        thrustError_N, ...
        coreExitVelocity_m_s, ...
        mixerPressureRecovery, ...
        mixerPressureLoss_percent, ...
        'VariableNames', { ...
            'Bleed_percent', ...
            'RequiredCombustorExitTt_K', ...
            'MixedHPTInletTt_K', ...
            'FuelFlow_kg_s', ...
            'TSFC_g_kN_s', ...
            'NetThrust_kN', ...
            'ThrustError_N', ...
            'CoreExitVelocity_m_s', ...
            'MixerPressureRecovery', ...
            'MixerPressureLoss_percent'});

    disp(fixedThrustTable);

    %% Save CSV results
    csvPath = fullfile( ...
        runOutput.data_folder, ...
        "cooling_bleed_sweep_" + fileSuffix + ".csv");

    writetable(fixedThrustTable, csvPath);

    %% Save complete MATLAB results
    resultsPath = fullfile( ...
        runOutput.data_folder, ...
        "study_results_" + fileSuffix + ".mat");

    save( ...
        resultsPath, ...
        "fixedThrustTable", ...
        "caseResults", ...
        "baselineResults", ...
        "cfgBase", ...
        "bleedFractions", ...
        "targetThrust_N", ...
        "baselineTIT_K", ...
        "maximumTIT_K", ...
        "thrustTolerance_N", ...
        "maximumThrustError_N", ...
        "caseTag", ...
        "runOutput");

    %% Figure 1: required combustor temperature
    fig = figure("Color", "w");

    plot( ...
        bleedPercent, ...
        requiredTIT_K, ...
        "LineWidth", 1.5, ...
        "Marker", "o");

    xlabel("HPT Cooling-Bleed Fraction (%)");
    ylabel("Required Combustor Exit Total Temperature (K)");
    title("Combustor Temperature Required to Maintain Thrust");
    grid on;

    save_study_figure( ...
        fig, ...
        runOutput.figure_folder, ...
        "required_TIT_" + fileSuffix);

    %% Figure 2: fuel flow
    fig = figure("Color", "w");

    plot( ...
        bleedPercent, ...
        fuelFlow_kg_s, ...
        "LineWidth", 1.5, ...
        "Marker", "o");

    xlabel("HPT Cooling-Bleed Fraction (%)");
    ylabel("Fuel Flow (kg/s)");
    title("Cooling-Bleed Fuel Penalty at Fixed Thrust");
    grid on;

    save_study_figure( ...
        fig, ...
        runOutput.figure_folder, ...
        "fuel_flow_" + fileSuffix);

    %% Figure 3: TSFC
    fig = figure("Color", "w");

    plot( ...
        bleedPercent, ...
        tsfc_g_kN_s, ...
        "LineWidth", 1.5, ...
        "Marker", "o");

    xlabel("HPT Cooling-Bleed Fraction (%)");
    ylabel("TSFC (g/(kN·s))");
    title("Cooling-Bleed TSFC Penalty at Fixed Thrust");
    grid on;

    save_study_figure( ...
        fig, ...
        runOutput.figure_folder, ...
        "TSFC_" + fileSuffix);

    %% Figure 4: temperature comparison
    fig = figure("Color", "w");

    plot( ...
        bleedPercent, ...
        requiredTIT_K, ...
        "LineWidth", 1.5, ...
        "Marker", "o");

    hold on;

    plot( ...
        bleedPercent, ...
        mixedHPTInletTt_K, ...
        "LineWidth", 1.5, ...
        "Marker", "s");

    xlabel("HPT Cooling-Bleed Fraction (%)");
    ylabel("Total Temperature (K)");
    title("Combustor Exit and Mixed HPT Inlet Temperatures");

    legend( ...
        "Combustor Exit", ...
        "Mixed HPT Inlet", ...
        "Location", ...
        "best");

    grid on;
    hold off;

    save_study_figure( ...
        fig, ...
        runOutput.figure_folder, ...
        "temperature_trade_" + fileSuffix);

    %% Print saved-file locations
    fprintf("\nSaved output files\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Maximum thrust error: %.6f N\n", ...
        maximumThrustError_N);
    fprintf("Configuration:        %s\n", configurationPath);
    fprintf("Results MAT:          %s\n", resultsPath);
    fprintf("Results CSV:          %s\n", csvPath);
    fprintf("Command log:          %s\n", commandWindowPath);
    fprintf("==================================================\n");
    fprintf("Fixed-thrust cooling-bleed sweep complete\n\n");

    diary off;

catch ME
    fprintf(2, ...
        "\nFixed-thrust sweep failed.\n\n");

    fprintf(2, "%s\n", ...
        getReport(ME, ...
        'extended', ...
        'hyperlinks', ...
        'off'));

    diary off;
    rethrow(ME);
end


function residual_N = evaluate_thrust_residual( ...
    TIT_K, cfg, targetThrust_N)
%EVALUATE_THRUST_RESIDUAL Evaluate thrust error for the TIT solver.

cfg.engine.combustor_exit_temperature_K = TIT_K;
cfg.engine.turbine_inlet_temperature_K = TIT_K;

results = run_turbofan(cfg);

residual_N = ...
    results.performance.net_thrust_N ...
    - targetThrust_N;

end


function save_study_figure(figHandle, figureFolder, baseName)
%SAVE_STUDY_FIGURE Apply light styling and save PNG + FIG files.

apply_light_figure_style(figHandle);

pngPath = fullfile( ...
    figureFolder, ...
    baseName + ".png");

figPath = fullfile( ...
    figureFolder, ...
    baseName + ".fig");

exportgraphics( ...
    figHandle, ...
    pngPath, ...
    "Resolution", 300, ...
    "BackgroundColor", "white");

savefig( ...
    figHandle, ...
    char(figPath));

end


function apply_light_figure_style(figHandle)
%APPLY_LIGHT_FIGURE_STYLE Force white-background publication style.

figHandle.Color = "w";

axList = findall(figHandle, "Type", "axes");

for i = 1:numel(axList)
    ax = axList(i);

    % White plot area
    ax.Color = "w";

    % Dark axes/ticks
    ax.XColor = "k";
    ax.YColor = "k";

    if isprop(ax, "ZColor")
        ax.ZColor = "k";
    end

    % Titles and labels
    ax.Title.Color = "k";
    ax.XLabel.Color = "k";
    ax.YLabel.Color = "k";

    % If yyaxis is used, force both y-axes dark
    if isprop(ax, "YAxis") && numel(ax.YAxis) > 1
        for j = 1:numel(ax.YAxis)
            ax.YAxis(j).Color = "k";
        end
    end

    % Grid appearance
    ax.GridColor = [0.75 0.75 0.75];
    ax.GridAlpha = 0.35;

    if isprop(ax, "MinorGridColor")
        ax.MinorGridColor = [0.85 0.85 0.85];
    end

    if isprop(ax, "MinorGridAlpha")
        ax.MinorGridAlpha = 0.20;
    end

    ax.Box = "on";
end

% Legends
legendList = findall(figHandle, "Type", "legend");

for i = 1:numel(legendList)
    lgd = legendList(i);
    lgd.TextColor = "k";
    lgd.Color = "w";
    lgd.EdgeColor = [0.25 0.25 0.25];
end

% Any extra text objects
textList = findall(figHandle, "Type", "text");

for i = 1:numel(textList)
    if isprop(textList(i), "Color")
        textList(i).Color = "k";
    end
end

end
