diary off;

clear;
clc;
close all;

%% Project paths
studyFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(studyFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Baseline cycle solution
cfgBase = baseline_engine();
baselineResults = run_turbofan(cfgBase);

caseTag = "hpt_candidate_ranking";

station41 = baselineResults.stations.station41;
station45 = baselineResults.stations.station45;
mdotHPT_kg_s = baselineResults.mass.mdot_hpt_kg_s;
baselineHPT = baselineResults.hpt_sizing;

%% Mean-line design-space definition
% Keep this grid aligned with hpt_design_space_sweep.m so the two studies
% remain directly comparable.
loadingCoefficients = 0.90:0.05:2.20;
flowCoefficients = 0.20:0.025:0.85;

fixedReaction = cfgBase.hpt.reaction;
fixedStageCount = cfgBase.hpt.stage_count;

[loadingGrid, flowGrid] = meshgrid( ...
    loadingCoefficients, ...
    flowCoefficients);

gridSize = size(loadingGrid);

%% Provisional screening constraints
% These are engineering-screening limits for the notional mean-line model.
% They are not claimed to be proprietary or certified CF34 design limits.
maximumMachLimit = 1.10;
minimumMeanRadius_m = 0.24;
maximumMeanRadius_m = 0.33;
maximumExitSpanToRadius = 0.20;
maximumAllowedAbsoluteFlowAngle_deg = 70.0;
minimumFlowCoefficient = 0.30;

%% Ranking weights
% The score ranks only designs that pass every screening constraint.
% Lower score is better. Weights sum to one.
weightMaximumMach = 0.35;
weightRadiusDeviation = 0.35;
weightExitSpanRatio = 0.15;
weightFlowAngle = 0.15;

weightSum = ...
    weightMaximumMach ...
    + weightRadiusDeviation ...
    + weightExitSpanRatio ...
    + weightFlowAngle;

if abs(weightSum - 1.0) > 1e-12
    error("Candidate-ranking weights must sum to one.");
end

numberCandidatesToPrint = 10;
numberCandidatesToLabel = 5;

%% Create matching Data and Figures run folders
runOutput = create_run_output_folders( ...
    projectRoot, ...
    cfgBase.meta.model_version);

fileSuffix = ...
    caseTag + "_" + runOutput.file_tag;

%% Start Command Window recording
commandWindowPath = fullfile( ...
    runOutput.data_folder, ...
    "command_window_" + fileSuffix + ".txt");

diary(char(commandWindowPath));

try
    fprintf("\nHPT candidate-ranking study started\n");
    fprintf("==================================================\n");
    fprintf("Model version:              %s\n", ...
        runOutput.version_tag);
    fprintf("Run number:                 %02d\n", ...
        runOutput.run_number);
    fprintf("Stage count:                %d\n", ...
        fixedStageCount);
    fprintf("Fixed reaction:             %.3f\n", ...
        fixedReaction);
    fprintf("Number of grid points:      %d\n\n", ...
        numel(loadingGrid));

    fprintf("Provisional screening constraints\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Maximum mean-line Mach:     %.2f\n", ...
        maximumMachLimit);
    fprintf("Mean-radius range:          %.3f to %.3f m\n", ...
        minimumMeanRadius_m, ...
        maximumMeanRadius_m);
    fprintf("Maximum exit span/radius:   %.3f\n", ...
        maximumExitSpanToRadius);
    fprintf("Maximum absolute angle:     %.1f deg\n", ...
        maximumAllowedAbsoluteFlowAngle_deg);
    fprintf("Minimum flow coefficient:   %.3f\n\n", ...
        minimumFlowCoefficient);

    %% Save exact study configuration
    configurationPath = fullfile( ...
        runOutput.data_folder, ...
        "configuration_" + fileSuffix + ".mat");

    save( ...
        configurationPath, ...
        "cfgBase", ...
        "loadingCoefficients", ...
        "flowCoefficients", ...
        "fixedReaction", ...
        "fixedStageCount", ...
        "maximumMachLimit", ...
        "minimumMeanRadius_m", ...
        "maximumMeanRadius_m", ...
        "maximumExitSpanToRadius", ...
        "maximumAllowedAbsoluteFlowAngle_deg", ...
        "minimumFlowCoefficient", ...
        "weightMaximumMach", ...
        "weightRadiusDeviation", ...
        "weightExitSpanRatio", ...
        "weightFlowAngle", ...
        "caseTag", ...
        "runOutput");

    %% Preallocate design-space outputs
    validPoint = false(gridSize);

    maximumMach = nan(gridSize);
    rotorInletAbsoluteMach = nan(gridSize);
    rotorInletRelativeMach = nan(gridSize);
    rotorExitAbsoluteMach = nan(gridSize);
    rotorExitRelativeMach = nan(gridSize);

    bladeSpeed_m_s = nan(gridSize);
    axialVelocity_m_s = nan(gridSize);
    meanRadius_m = nan(gridSize);
    inletSpan_m = nan(gridSize);
    exitSpan_m = nan(gridSize);
    exitSpanToMeanRadius = nan(gridSize);
    exitHubToTipRatio = nan(gridSize);

    alpha1_deg = nan(gridSize);
    alpha2_deg = nan(gridSize);
    beta1_deg = nan(gridSize);
    beta2_deg = nan(gridSize);
    maximumAbsoluteFlowAngle_deg = nan(gridSize);

    maximumMachLocation = strings(gridSize);
    aerodynamicStatus = strings(gridSize);
    errorMessage = strings(gridSize);

    %% Evaluate each loading/flow-coefficient combination
    for row = 1:gridSize(1)
        for column = 1:gridSize(2)
            psi = loadingGrid(row, column);
            phi = flowGrid(row, column);

            try
                stage = hpt_stage_sizing( ...
                    station41, ...
                    station45, ...
                    mdotHPT_kg_s, ...
                    cfgBase.shaft.high_spool_rpm, ...
                    cfgBase.thermo.cp_hot_J_kgK, ...
                    cfgBase.thermo.gamma_hot, ...
                    cfgBase.thermo.R_J_kgK, ...
                    fixedStageCount, ...
                    psi, ...
                    phi, ...
                    fixedReaction);

                validPoint(row, column) = true;

                maximumMach(row, column) = ...
                    stage.maximum_mach;

                rotorInletAbsoluteMach(row, column) = ...
                    stage.rotor_inlet_absolute_mach;

                rotorInletRelativeMach(row, column) = ...
                    stage.rotor_inlet_relative_mach;

                rotorExitAbsoluteMach(row, column) = ...
                    stage.rotor_exit_absolute_mach;

                rotorExitRelativeMach(row, column) = ...
                    stage.rotor_exit_relative_mach;

                bladeSpeed_m_s(row, column) = ...
                    stage.blade_speed_m_s;

                axialVelocity_m_s(row, column) = ...
                    stage.axial_velocity_m_s;

                meanRadius_m(row, column) = ...
                    stage.mean_radius_m;

                inletSpan_m(row, column) = ...
                    stage.blade_span_inlet_m;

                exitSpan_m(row, column) = ...
                    stage.blade_span_exit_m;

                exitSpanToMeanRadius(row, column) = ...
                    stage.blade_span_exit_m ...
                    / stage.mean_radius_m;

                exitHubToTipRatio(row, column) = ...
                    stage.hub_radius_exit_m ...
                    / stage.tip_radius_exit_m;

                alpha1_deg(row, column) = ...
                    stage.alpha1_deg;

                alpha2_deg(row, column) = ...
                    stage.alpha2_deg;

                beta1_deg(row, column) = ...
                    stage.beta1_deg;

                beta2_deg(row, column) = ...
                    stage.beta2_deg;

                maximumAbsoluteFlowAngle_deg(row, column) = ...
                    max(abs([ ...
                        stage.alpha1_deg, ...
                        stage.alpha2_deg, ...
                        stage.beta1_deg, ...
                        stage.beta2_deg]));

                maximumMachLocation(row, column) = ...
                    string(stage.maximum_mach_location);

                aerodynamicStatus(row, column) = ...
                    string(stage.aerodynamic_status);

            catch pointError
                aerodynamicStatus(row, column) = ...
                    "Invalid mean-line point";

                errorMessage(row, column) = ...
                    string(pointError.message);
            end
        end
    end

    %% Apply screening constraints
    passesMachConstraint = ...
        validPoint ...
        & maximumMach <= maximumMachLimit;

    passesRadiusConstraint = ...
        validPoint ...
        & meanRadius_m >= minimumMeanRadius_m ...
        & meanRadius_m <= maximumMeanRadius_m;

    passesSpanConstraint = ...
        validPoint ...
        & exitSpanToMeanRadius <= maximumExitSpanToRadius;

    passesAngleConstraint = ...
        validPoint ...
        & maximumAbsoluteFlowAngle_deg ...
        <= maximumAllowedAbsoluteFlowAngle_deg;

    passesFlowConstraint = ...
        validPoint ...
        & flowGrid >= minimumFlowCoefficient;

    feasibleCandidate = ...
        passesMachConstraint ...
        & passesRadiusConstraint ...
        & passesSpanConstraint ...
        & passesAngleConstraint ...
        & passesFlowConstraint;

    numberValidPoints = nnz(validPoint);
    numberFeasibleCandidates = nnz(feasibleCandidate);

    if numberFeasibleCandidates == 0
        error( ...
            "No HPT candidates passed all provisional constraints.");
    end

    %% Calculate normalized ranking objectives
    baselineMeanRadius_m = ...
        baselineHPT.mean_radius_m;

    radiusDeviationFraction = ...
        abs(meanRadius_m - baselineMeanRadius_m) ...
        / baselineMeanRadius_m;

    normalizedMach = normalize_feasible_metric( ...
        maximumMach, ...
        feasibleCandidate);

    normalizedRadiusDeviation = normalize_feasible_metric( ...
        radiusDeviationFraction, ...
        feasibleCandidate);

    normalizedExitSpanRatio = normalize_feasible_metric( ...
        exitSpanToMeanRadius, ...
        feasibleCandidate);

    normalizedFlowAngle = normalize_feasible_metric( ...
        maximumAbsoluteFlowAngle_deg, ...
        feasibleCandidate);

    rankingScore = nan(gridSize);

    rankingScore(feasibleCandidate) = ...
        weightMaximumMach ...
        .* normalizedMach(feasibleCandidate) ...
        + weightRadiusDeviation ...
        .* normalizedRadiusDeviation(feasibleCandidate) ...
        + weightExitSpanRatio ...
        .* normalizedExitSpanRatio(feasibleCandidate) ...
        + weightFlowAngle ...
        .* normalizedFlowAngle(feasibleCandidate);

    %% Complete design-space table
    designSpaceTable = table( ...
        loadingGrid(:), ...
        flowGrid(:), ...
        repmat(fixedReaction, numel(loadingGrid), 1), ...
        validPoint(:), ...
        passesMachConstraint(:), ...
        passesRadiusConstraint(:), ...
        passesSpanConstraint(:), ...
        passesAngleConstraint(:), ...
        passesFlowConstraint(:), ...
        feasibleCandidate(:), ...
        rankingScore(:), ...
        maximumMach(:), ...
        rotorInletAbsoluteMach(:), ...
        rotorInletRelativeMach(:), ...
        rotorExitAbsoluteMach(:), ...
        rotorExitRelativeMach(:), ...
        bladeSpeed_m_s(:), ...
        axialVelocity_m_s(:), ...
        meanRadius_m(:), ...
        radiusDeviationFraction(:), ...
        inletSpan_m(:), ...
        exitSpan_m(:), ...
        exitSpanToMeanRadius(:), ...
        exitHubToTipRatio(:), ...
        alpha1_deg(:), ...
        alpha2_deg(:), ...
        beta1_deg(:), ...
        beta2_deg(:), ...
        maximumAbsoluteFlowAngle_deg(:), ...
        maximumMachLocation(:), ...
        aerodynamicStatus(:), ...
        errorMessage(:), ...
        'VariableNames', { ...
            'LoadingCoefficient_psi', ...
            'FlowCoefficient_phi', ...
            'Reaction', ...
            'ValidPoint', ...
            'PassesMachConstraint', ...
            'PassesRadiusConstraint', ...
            'PassesSpanConstraint', ...
            'PassesAngleConstraint', ...
            'PassesFlowConstraint', ...
            'FeasibleCandidate', ...
            'RankingScore', ...
            'MaximumMach', ...
            'RotorInletAbsoluteMach', ...
            'RotorInletRelativeMach', ...
            'RotorExitAbsoluteMach', ...
            'RotorExitRelativeMach', ...
            'BladeSpeed_m_s', ...
            'AxialVelocity_m_s', ...
            'MeanRadius_m', ...
            'RadiusDeviationFraction', ...
            'InletSpan_m', ...
            'ExitSpan_m', ...
            'ExitSpanToMeanRadius', ...
            'ExitHubToTipRatio', ...
            'Alpha1_deg', ...
            'Alpha2_deg', ...
            'Beta1_deg', ...
            'Beta2_deg', ...
            'MaximumAbsoluteFlowAngle_deg', ...
            'MaximumMachLocation', ...
            'AerodynamicStatus', ...
            'ErrorMessage'});

    %% Sort feasible candidates by score
    candidateTable = ...
        designSpaceTable(designSpaceTable.FeasibleCandidate, :);

    candidateTable = sortrows( ...
        candidateTable, ...
        {'RankingScore', 'MaximumMach', 'MeanRadius_m'}, ...
        {'ascend', 'ascend', 'ascend'});

    rankColumn = (1:height(candidateTable)).';

    candidateTable = [ ...
        table(rankColumn, 'VariableNames', {'Rank'}), ...
        candidateTable];

    numberTopCandidates = min( ...
        numberCandidatesToPrint, ...
        height(candidateTable));

    topCandidateTable = ...
        candidateTable(1:numberTopCandidates, :);

    bestCandidate = ...
        candidateTable(1, :);

    %% Baseline-versus-candidate comparison table
    baselineMaximumAngle_deg = max(abs([ ...
        baselineHPT.alpha1_deg, ...
        baselineHPT.alpha2_deg, ...
        baselineHPT.beta1_deg, ...
        baselineHPT.beta2_deg]));

    baselineExitSpanRatio = ...
        baselineHPT.blade_span_exit_m ...
        / baselineHPT.mean_radius_m;

    baselinePassesScreening = ...
        baselineHPT.maximum_mach <= maximumMachLimit ...
        && baselineHPT.mean_radius_m >= minimumMeanRadius_m ...
        && baselineHPT.mean_radius_m <= maximumMeanRadius_m ...
        && baselineExitSpanRatio <= maximumExitSpanToRadius ...
        && baselineMaximumAngle_deg ...
        <= maximumAllowedAbsoluteFlowAngle_deg ...
        && cfgBase.hpt.flow_coefficient ...
        >= minimumFlowCoefficient;

    comparisonCase = [ ...
        "Current baseline"; ...
        "Top-ranked screened candidate"];

    loadingCoefficient_psi = [ ...
        cfgBase.hpt.loading_coefficient; ...
        bestCandidate.LoadingCoefficient_psi];

    flowCoefficient_phi = [ ...
        cfgBase.hpt.flow_coefficient; ...
        bestCandidate.FlowCoefficient_phi];

    maximumMachComparison = [ ...
        baselineHPT.maximum_mach; ...
        bestCandidate.MaximumMach];

    meanRadiusComparison_m = [ ...
        baselineHPT.mean_radius_m; ...
        bestCandidate.MeanRadius_m];

    exitSpanRatioComparison = [ ...
        baselineExitSpanRatio; ...
        bestCandidate.ExitSpanToMeanRadius];

    maximumAngleComparison_deg = [ ...
        baselineMaximumAngle_deg; ...
        bestCandidate.MaximumAbsoluteFlowAngle_deg];

    passesScreeningComparison = [ ...
        baselinePassesScreening; ...
        true];

    baselineComparisonTable = table( ...
        comparisonCase, ...
        loadingCoefficient_psi, ...
        flowCoefficient_phi, ...
        maximumMachComparison, ...
        meanRadiusComparison_m, ...
        exitSpanRatioComparison, ...
        maximumAngleComparison_deg, ...
        passesScreeningComparison, ...
        'VariableNames', { ...
            'Case', ...
            'LoadingCoefficient_psi', ...
            'FlowCoefficient_phi', ...
            'MaximumMach', ...
            'MeanRadius_m', ...
            'ExitSpanToMeanRadius', ...
            'MaximumAbsoluteFlowAngle_deg', ...
            'PassesScreening'});

    %% Save CSV and complete MATLAB results
    designSpaceCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "hpt_ranked_design_space_" + fileSuffix + ".csv");

    candidateCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "hpt_ranked_candidates_" + fileSuffix + ".csv");

    comparisonCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "hpt_baseline_candidate_comparison_" ...
        + fileSuffix + ".csv");

    writetable(designSpaceTable, designSpaceCsvPath);
    writetable(candidateTable, candidateCsvPath);
    writetable(baselineComparisonTable, comparisonCsvPath);

    resultsPath = fullfile( ...
        runOutput.data_folder, ...
        "study_results_" + fileSuffix + ".mat");

    save( ...
        resultsPath, ...
        "designSpaceTable", ...
        "candidateTable", ...
        "topCandidateTable", ...
        "baselineComparisonTable", ...
        "baselineResults", ...
        "cfgBase", ...
        "loadingGrid", ...
        "flowGrid", ...
        "feasibleCandidate", ...
        "rankingScore", ...
        "caseTag", ...
        "runOutput");

    %% Figure 1: feasible candidate score map
    fig = figure("Color", "w");

    scoreImage = imagesc( ...
        loadingCoefficients, ...
        flowCoefficients, ...
        rankingScore);

    set(gca, "YDir", "normal");

    % Make points that fail the screening constraints transparent rather
    % than rendering them with the lowest colormap color.
    scoreImage.AlphaData = double(feasibleCandidate);
    scoreImage.AlphaDataMapping = "none";

    feasibleScores = rankingScore(feasibleCandidate);
    caxis([min(feasibleScores), max(feasibleScores)]);

    scoreColorbar = colorbar;
    scoreColorbar.Label.String = ...
        "Ranking score (lower is better)";

    hold on;

    baselineMarker = plot( ...
        cfgBase.hpt.loading_coefficient, ...
        cfgBase.hpt.flow_coefficient, ...
        "o", ...
        "MarkerSize", 8, ...
        "MarkerFaceColor", "k", ...
        "MarkerEdgeColor", "w");

    bestMarker = plot( ...
        bestCandidate.LoadingCoefficient_psi, ...
        bestCandidate.FlowCoefficient_phi, ...
        "p", ...
        "MarkerSize", 12, ...
        "MarkerFaceColor", "w", ...
        "MarkerEdgeColor", "k");

    xlabel("Stage Loading Coefficient, \psi");
    ylabel("Flow Coefficient, \phi");
    title({ ...
        "HPT Screened-Candidate Ranking Score", ...
        "Blank cells fail one or more screening constraints"});

    legend( ...
        [baselineMarker, bestMarker], ...
        "Current baseline (outside screen)", ...
        "Top-ranked candidate", ...
        "Location", "best");

    grid on;
    hold off;

    save_study_figure( ...
        fig, ...
        runOutput.figure_folder, ...
        "candidate_score_map_" + fileSuffix);

    %% Figure 2: Mach-radius tradeoff among feasible candidates
    fig = figure("Color", "w");

    markerSize = ...
        30 + 350 ...
        .* candidateTable.ExitSpanToMeanRadius;

    scatter( ...
        candidateTable.MeanRadius_m, ...
        candidateTable.MaximumMach, ...
        markerSize, ...
        candidateTable.RankingScore, ...
        "filled");

    tradeoffColorbar = colorbar;
    tradeoffColorbar.Label.String = ...
        "Ranking score (lower is better)";

    hold on;

    baselineMarker = plot( ...
        baselineHPT.mean_radius_m, ...
        baselineHPT.maximum_mach, ...
        "o", ...
        "MarkerSize", 8, ...
        "MarkerFaceColor", "k", ...
        "MarkerEdgeColor", "w");

    bestMarker = plot( ...
        bestCandidate.MeanRadius_m, ...
        bestCandidate.MaximumMach, ...
        "p", ...
        "MarkerSize", 12, ...
        "MarkerFaceColor", "w", ...
        "MarkerEdgeColor", "k");

    numberLabels = min( ...
        numberCandidatesToLabel, ...
        height(candidateTable));

    for candidateIndex = 1:numberLabels
        text( ...
            candidateTable.MeanRadius_m(candidateIndex), ...
            candidateTable.MaximumMach(candidateIndex), ...
            "  #" + string(candidateIndex), ...
            "VerticalAlignment", "middle");
    end

    xlabel("Mean Radius (m)");
    ylabel("Maximum Mean-Line Mach Number");
    title({ ...
        "Screened HPT Candidate Mach-Radius Tradeoff", ...
        "Marker size scales with exit span / mean radius"});

    legend( ...
        [baselineMarker, bestMarker], ...
        "Current baseline (fails Mach screen)", ...
        "Top-ranked candidate", ...
        "Location", "best");

    grid on;
    hold off;

    save_study_figure( ...
        fig, ...
        runOutput.figure_folder, ...
        "candidate_tradeoff_" + fileSuffix);

    %% Print ranking summary
    fprintf("Candidate-screening summary\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Valid mean-line points:       %d of %d\n", ...
        numberValidPoints, ...
        numel(loadingGrid));
    fprintf("Feasible screened candidates: %d\n\n", ...
        numberFeasibleCandidates);

    fprintf("Ranking weights\n");
    fprintf("  Maximum Mach:               %.2f\n", ...
        weightMaximumMach);
    fprintf("  Radius deviation:           %.2f\n", ...
        weightRadiusDeviation);
    fprintf("  Exit span/radius:           %.2f\n", ...
        weightExitSpanRatio);
    fprintf("  Maximum flow angle:         %.2f\n\n", ...
        weightFlowAngle);

    fprintf("Baseline comparison\n");
    disp(baselineComparisonTable);

    fprintf("Top %d screened candidates\n", ...
        numberTopCandidates);

    disp(topCandidateTable(:, { ...
        'Rank', ...
        'LoadingCoefficient_psi', ...
        'FlowCoefficient_phi', ...
        'RankingScore', ...
        'MaximumMach', ...
        'MeanRadius_m', ...
        'ExitSpanToMeanRadius', ...
        'MaximumAbsoluteFlowAngle_deg'}));

    fprintf("The ranking is a transparent screening tool, not a\n");
    fprintf("claim that the first row is the final physical design.\n");
    fprintf("Do not update baseline_engine.m until the shortlist\n");
    fprintf("has been reviewed against the velocity triangles.\n\n");

    fprintf("Saved output files\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Configuration:       %s\n", configurationPath);
    fprintf("Results MAT:         %s\n", resultsPath);
    fprintf("Full design CSV:     %s\n", designSpaceCsvPath);
    fprintf("Candidate CSV:       %s\n", candidateCsvPath);
    fprintf("Comparison CSV:      %s\n", comparisonCsvPath);
    fprintf("Command log:         %s\n", commandWindowPath);
    fprintf("==================================================\n");
    fprintf("HPT candidate-ranking study complete\n\n");

    diary off;

catch ME
    fprintf(2, ...
        "\nHPT candidate-ranking study failed.\n\n");

    fprintf(2, "%s\n", ...
        getReport( ...
            ME, ...
            "extended", ...
            "hyperlinks", ...
            "off"));

    diary off;
    rethrow(ME);
end


function normalizedMetric = normalize_feasible_metric( ...
    rawMetric, feasibleMask)
%NORMALIZE_FEASIBLE_METRIC Min-max normalize feasible values to [0, 1].

normalizedMetric = nan(size(rawMetric));

feasibleValues = rawMetric(feasibleMask);

minimumValue = min(feasibleValues);
maximumValue = max(feasibleValues);
valueRange = maximumValue - minimumValue;

if valueRange <= eps(max(abs([minimumValue, maximumValue])))
    normalizedMetric(feasibleMask) = 0;
else
    normalizedMetric(feasibleMask) = ...
        (feasibleValues - minimumValue) ...
        / valueRange;
end

end


function save_study_figure(figHandle, figureFolder, baseName)
%SAVE_STUDY_FIGURE Apply light styling and save PNG + FIG files.

apply_light_figure_style(figHandle);

pngPath = fullfile( ...
    figureFolder, ...
    baseName + ".png");

figPath = fullfile( ...
    figureFolder, ...
    baseName + ".fig");

exportgraphics( ...
    figHandle, ...
    pngPath, ...
    "Resolution", 300, ...
    "BackgroundColor", "white");

savefig( ...
    figHandle, ...
    char(figPath));

end


function apply_light_figure_style(figHandle)
%APPLY_LIGHT_FIGURE_STYLE Force white-background publication style.

figHandle.Color = "w";

axList = findall(figHandle, "Type", "axes");

for i = 1:numel(axList)
    ax = axList(i);

    ax.Color = "w";
    ax.XColor = "k";
    ax.YColor = "k";

    if isprop(ax, "ZColor")
        ax.ZColor = "k";
    end

    ax.Title.Color = "k";
    ax.XLabel.Color = "k";
    ax.YLabel.Color = "k";

    if isprop(ax, "YAxis") && numel(ax.YAxis) > 1
        for j = 1:numel(ax.YAxis)
            ax.YAxis(j).Color = "k";
        end
    end

    ax.GridColor = "k";
    ax.GridAlpha = 0.18;

    if isprop(ax, "MinorGridColor")
        ax.MinorGridColor = "k";
    end

    if isprop(ax, "MinorGridAlpha")
        ax.MinorGridAlpha = 0.10;
    end

    ax.Box = "on";

    if isprop(ax, "Toolbar")
        ax.Toolbar.Visible = "off";
    end
end

legendList = findall(figHandle, "Type", "legend");

for i = 1:numel(legendList)
    lgd = legendList(i);
    lgd.TextColor = "k";
    lgd.Color = "w";
    lgd.EdgeColor = [0.25 0.25 0.25];
end

textList = findall(figHandle, "Type", "text");

for i = 1:numel(textList)
    if isprop(textList(i), "Color")
        textList(i).Color = "k";
    end
end

colorbarList = findall(figHandle, "Type", "ColorBar");

for i = 1:numel(colorbarList)
    cb = colorbarList(i);
    cb.Color = "k";

    if isprop(cb, "Label")
        cb.Label.Color = "k";
    end

    if isprop(cb, "Title")
        cb.Title.Color = "k";
    end
end

end
