diary off;

clear;
clc;
close all;

%% Project paths
studyFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(studyFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Baseline cycle solution
cfgBase = baseline_engine();
baselineResults = run_turbofan(cfgBase);

caseTag = "hpt_design_space";

station41 = baselineResults.stations.station41;
station45 = baselineResults.stations.station45;
mdotHPT_kg_s = baselineResults.mass.mdot_hpt_kg_s;

%% Mean-line design-space definition
% Reaction and stage count remain fixed during this first screening study.
loadingCoefficients = 0.90:0.05:2.20;
flowCoefficients = 0.20:0.025:0.85;

fixedReaction = cfgBase.hpt.reaction;
fixedStageCount = cfgBase.hpt.stage_count;

[loadingGrid, flowGrid] = meshgrid( ...
    loadingCoefficients, ...
    flowCoefficients);

gridSize = size(loadingGrid);

%% Create matching Data and Figures run folders
runOutput = create_run_output_folders( ...
    projectRoot, ...
    cfgBase.meta.model_version);

fileSuffix = ...
    caseTag + "_" + runOutput.file_tag;

%% Start Command Window recording
commandWindowPath = fullfile( ...
    runOutput.data_folder, ...
    "command_window_" + fileSuffix + ".txt");

diary(char(commandWindowPath));

try
    fprintf("\nHPT mean-line design-space sweep started\n");
    fprintf("==================================================\n");
    fprintf("Model version:      %s\n", runOutput.version_tag);
    fprintf("Run number:         %02d\n", runOutput.run_number);
    fprintf("Stage count:        %d\n", fixedStageCount);
    fprintf("Fixed reaction:     %.3f\n", fixedReaction);
    fprintf("Loading range:      %.2f to %.2f\n", ...
        loadingCoefficients(1), loadingCoefficients(end));
    fprintf("Flow range:         %.3f to %.3f\n", ...
        flowCoefficients(1), flowCoefficients(end));
    fprintf("Number of cases:    %d\n\n", numel(loadingGrid));

    %% Save exact study configuration
    configurationPath = fullfile( ...
        runOutput.data_folder, ...
        "configuration_" + fileSuffix + ".mat");

    save( ...
        configurationPath, ...
        "cfgBase", ...
        "loadingCoefficients", ...
        "flowCoefficients", ...
        "fixedReaction", ...
        "fixedStageCount", ...
        "caseTag", ...
        "runOutput");

    %% Preallocate design-space outputs
    validPoint = false(gridSize);

    maximumMach = nan(gridSize);
    rotorInletAbsoluteMach = nan(gridSize);
    rotorInletRelativeMach = nan(gridSize);
    rotorExitAbsoluteMach = nan(gridSize);
    rotorExitRelativeMach = nan(gridSize);

    bladeSpeed_m_s = nan(gridSize);
    axialVelocity_m_s = nan(gridSize);
    meanRadius_m = nan(gridSize);
    inletSpan_m = nan(gridSize);
    exitSpan_m = nan(gridSize);
    exitSpanToMeanRadius = nan(gridSize);

    alpha1_deg = nan(gridSize);
    alpha2_deg = nan(gridSize);
    beta1_deg = nan(gridSize);
    beta2_deg = nan(gridSize);

    maximumMachLocation = strings(gridSize);
    aerodynamicStatus = strings(gridSize);
    errorMessage = strings(gridSize);

    %% Evaluate each loading/flow-coefficient combination
    for row = 1:gridSize(1)
        for column = 1:gridSize(2)
            psi = loadingGrid(row, column);
            phi = flowGrid(row, column);

            try
                stage = hpt_stage_sizing( ...
                    station41, ...
                    station45, ...
                    mdotHPT_kg_s, ...
                    cfgBase.shaft.high_spool_rpm, ...
                    cfgBase.thermo.cp_hot_J_kgK, ...
                    cfgBase.thermo.gamma_hot, ...
                    cfgBase.thermo.R_J_kgK, ...
                    fixedStageCount, ...
                    psi, ...
                    phi, ...
                    fixedReaction);

                validPoint(row, column) = true;

                maximumMach(row, column) = ...
                    stage.maximum_mach;

                rotorInletAbsoluteMach(row, column) = ...
                    stage.rotor_inlet_absolute_mach;

                rotorInletRelativeMach(row, column) = ...
                    stage.rotor_inlet_relative_mach;

                rotorExitAbsoluteMach(row, column) = ...
                    stage.rotor_exit_absolute_mach;

                rotorExitRelativeMach(row, column) = ...
                    stage.rotor_exit_relative_mach;

                bladeSpeed_m_s(row, column) = ...
                    stage.blade_speed_m_s;

                axialVelocity_m_s(row, column) = ...
                    stage.axial_velocity_m_s;

                meanRadius_m(row, column) = ...
                    stage.mean_radius_m;

                inletSpan_m(row, column) = ...
                    stage.blade_span_inlet_m;

                exitSpan_m(row, column) = ...
                    stage.blade_span_exit_m;

                exitSpanToMeanRadius(row, column) = ...
                    stage.blade_span_exit_m ...
                    / stage.mean_radius_m;

                alpha1_deg(row, column) = ...
                    stage.alpha1_deg;

                alpha2_deg(row, column) = ...
                    stage.alpha2_deg;

                beta1_deg(row, column) = ...
                    stage.beta1_deg;

                beta2_deg(row, column) = ...
                    stage.beta2_deg;

                maximumMachLocation(row, column) = ...
                    string(stage.maximum_mach_location);

                aerodynamicStatus(row, column) = ...
                    string(stage.aerodynamic_status);

            catch pointError
                aerodynamicStatus(row, column) = ...
                    "Invalid mean-line point";

                errorMessage(row, column) = ...
                    string(pointError.message);
            end
        end
    end

    %% Locate key cases
    validMachForSearch = maximumMach;
    validMachForSearch(~validPoint) = Inf;

    [minimumMaximumMach, minimumLinearIndex] = ...
        min(validMachForSearch(:));

    if isinf(minimumMaximumMach)
        error("No valid HPT mean-line design points were found.");
    end

    [minimumRow, minimumColumn] = ...
        ind2sub(gridSize, minimumLinearIndex);

    minimumMachPsi = ...
        loadingGrid(minimumRow, minimumColumn);

    minimumMachPhi = ...
        flowGrid(minimumRow, minimumColumn);

    subsonicMask = ...
        validPoint & maximumMach < 1.00;

    transonicOrLowerMask = ...
        validPoint & maximumMach < 1.10;

    numberValid = nnz(validPoint);
    numberSubsonic = nnz(subsonicMask);
    numberBelowOnePointOne = nnz(transonicOrLowerMask);

    baselineHPT = baselineResults.hpt_sizing;

    %% Results table
    designSpaceTable = table( ...
        loadingGrid(:), ...
        flowGrid(:), ...
        repmat(fixedReaction, numel(loadingGrid), 1), ...
        validPoint(:), ...
        maximumMach(:), ...
        rotorInletAbsoluteMach(:), ...
        rotorInletRelativeMach(:), ...
        rotorExitAbsoluteMach(:), ...
        rotorExitRelativeMach(:), ...
        bladeSpeed_m_s(:), ...
        axialVelocity_m_s(:), ...
        meanRadius_m(:), ...
        inletSpan_m(:), ...
        exitSpan_m(:), ...
        exitSpanToMeanRadius(:), ...
        alpha1_deg(:), ...
        alpha2_deg(:), ...
        beta1_deg(:), ...
        beta2_deg(:), ...
        maximumMachLocation(:), ...
        aerodynamicStatus(:), ...
        errorMessage(:), ...
        'VariableNames', { ...
            'LoadingCoefficient_psi', ...
            'FlowCoefficient_phi', ...
            'Reaction', ...
            'ValidPoint', ...
            'MaximumMach', ...
            'RotorInletAbsoluteMach', ...
            'RotorInletRelativeMach', ...
            'RotorExitAbsoluteMach', ...
            'RotorExitRelativeMach', ...
            'BladeSpeed_m_s', ...
            'AxialVelocity_m_s', ...
            'MeanRadius_m', ...
            'InletSpan_m', ...
            'ExitSpan_m', ...
            'ExitSpanToMeanRadius', ...
            'Alpha1_deg', ...
            'Alpha2_deg', ...
            'Beta1_deg', ...
            'Beta2_deg', ...
            'MaximumMachLocation', ...
            'AerodynamicStatus', ...
            'ErrorMessage'});

    %% Save CSV and complete MATLAB results
    csvPath = fullfile( ...
        runOutput.data_folder, ...
        "hpt_design_space_" + fileSuffix + ".csv");

    writetable(designSpaceTable, csvPath);

    resultsPath = fullfile( ...
        runOutput.data_folder, ...
        "study_results_" + fileSuffix + ".mat");

    save( ...
        resultsPath, ...
        "designSpaceTable", ...
        "baselineResults", ...
        "cfgBase", ...
        "loadingGrid", ...
        "flowGrid", ...
        "validPoint", ...
        "maximumMach", ...
        "meanRadius_m", ...
        "exitSpanToMeanRadius", ...
        "minimumMaximumMach", ...
        "minimumMachPsi", ...
        "minimumMachPhi", ...
        "numberValid", ...
        "numberSubsonic", ...
        "numberBelowOnePointOne", ...
        "caseTag", ...
        "runOutput");

    %% Figure 1: maximum mean-line Mach
    fig = figure("Color", "w");

    imagesc( ...
        loadingCoefficients, ...
        flowCoefficients, ...
        maximumMach);

    set(gca, "YDir", "normal");
    colorbar;
    hold on;

    [~, machOneContour] = contour( ...
        loadingCoefficients, ...
        flowCoefficients, ...
        maximumMach, ...
        [1.00 1.00], ...
        "LineWidth", 1.5);

    baselineMarker = plot( ...
        cfgBase.hpt.loading_coefficient, ...
        cfgBase.hpt.flow_coefficient, ...
        "o", ...
        "MarkerSize", 8, ...
        "MarkerFaceColor", "k", ...
        "MarkerEdgeColor", "w");

    minimumMarker = plot( ...
        minimumMachPsi, ...
        minimumMachPhi, ...
        "p", ...
        "MarkerSize", 10, ...
        "MarkerFaceColor", "w", ...
        "MarkerEdgeColor", "k");

    xlabel("Stage Loading Coefficient, \psi");
    ylabel("Flow Coefficient, \phi");
    title("HPT Maximum Mean-Line Mach Number");

    legend( ...
        [baselineMarker, minimumMarker, machOneContour], ...
        "Current baseline", ...
        "Minimum-Mach point", ...
        "M_{max} = 1.00", ...
        "Location", "best");

    grid on;
    hold off;

    save_study_figure( ...
        fig, ...
        runOutput.figure_folder, ...
        "maximum_mach_" + fileSuffix);

    %% Figure 2: mean radius
    fig = figure("Color", "w");

    imagesc( ...
        loadingCoefficients, ...
        flowCoefficients, ...
        meanRadius_m);

    set(gca, "YDir", "normal");
    colorbar;
    hold on;

    plot( ...
        cfgBase.hpt.loading_coefficient, ...
        cfgBase.hpt.flow_coefficient, ...
        "o", ...
        "MarkerSize", 8, ...
        "MarkerFaceColor", "k", ...
        "MarkerEdgeColor", "w");

    plot( ...
        minimumMachPsi, ...
        minimumMachPhi, ...
        "p", ...
        "MarkerSize", 10, ...
        "MarkerFaceColor", "w", ...
        "MarkerEdgeColor", "k");

    xlabel("Stage Loading Coefficient, \psi");
    ylabel("Flow Coefficient, \phi");
    title("HPT Mean Radius (m)");
    grid on;
    hold off;

    save_study_figure( ...
        fig, ...
        runOutput.figure_folder, ...
        "mean_radius_" + fileSuffix);

    %% Figure 3: exit span-to-radius ratio
    fig = figure("Color", "w");

    imagesc( ...
        loadingCoefficients, ...
        flowCoefficients, ...
        exitSpanToMeanRadius);

    set(gca, "YDir", "normal");
    colorbar;
    hold on;

    plot( ...
        cfgBase.hpt.loading_coefficient, ...
        cfgBase.hpt.flow_coefficient, ...
        "o", ...
        "MarkerSize", 8, ...
        "MarkerFaceColor", "k", ...
        "MarkerEdgeColor", "w");

    plot( ...
        minimumMachPsi, ...
        minimumMachPhi, ...
        "p", ...
        "MarkerSize", 10, ...
        "MarkerFaceColor", "w", ...
        "MarkerEdgeColor", "k");

    xlabel("Stage Loading Coefficient, \psi");
    ylabel("Flow Coefficient, \phi");
    title("HPT Exit Span / Mean Radius");
    grid on;
    hold off;

    save_study_figure( ...
        fig, ...
        runOutput.figure_folder, ...
        "exit_span_ratio_" + fileSuffix);

    %% Print screening summary
    fprintf("Design-space screening summary\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Valid points:                 %d of %d\n", ...
        numberValid, numel(loadingGrid));
    fprintf("Points with maximum Mach < 1: %d\n", ...
        numberSubsonic);
    fprintf("Points with maximum Mach < 1.1: %d\n\n", ...
        numberBelowOnePointOne);

    fprintf("Current baseline\n");
    fprintf("  psi:                         %.3f\n", ...
        cfgBase.hpt.loading_coefficient);
    fprintf("  phi:                         %.3f\n", ...
        cfgBase.hpt.flow_coefficient);
    fprintf("  maximum Mach:                %.3f\n", ...
        baselineHPT.maximum_mach);
    fprintf("  mean radius:                 %.4f m\n", ...
        baselineHPT.mean_radius_m);
    fprintf("  exit span / mean radius:     %.4f\n\n", ...
        baselineHPT.blade_span_exit_m ...
        / baselineHPT.mean_radius_m);

    fprintf("Lowest-Mach grid point\n");
    fprintf("  psi:                         %.3f\n", ...
        minimumMachPsi);
    fprintf("  phi:                         %.3f\n", ...
        minimumMachPhi);
    fprintf("  maximum Mach:                %.3f\n", ...
        minimumMaximumMach);
    fprintf("  mean radius:                 %.4f m\n", ...
        meanRadius_m(minimumRow, minimumColumn));
    fprintf("  exit span / mean radius:     %.4f\n\n", ...
        exitSpanToMeanRadius(minimumRow, minimumColumn));

    fprintf("Do not update the baseline HPT coefficients from this\n");
    fprintf("screening study until the geometry and loading tradeoffs\n");
    fprintf("have been reviewed.\n\n");

    fprintf("Saved output files\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Configuration: %s\n", configurationPath);
    fprintf("Results MAT:   %s\n", resultsPath);
    fprintf("Results CSV:   %s\n", csvPath);
    fprintf("Command log:   %s\n", commandWindowPath);
    fprintf("==================================================\n");
    fprintf("HPT mean-line design-space sweep complete\n\n");

    diary off;

catch ME
    fprintf(2, ...
        "\nHPT design-space sweep failed.\n\n");

    fprintf(2, "%s\n", ...
        getReport( ...
            ME, ...
            "extended", ...
            "hyperlinks", ...
            "off"));

    diary off;
    rethrow(ME);
end


function save_study_figure(figHandle, figureFolder, baseName)
%SAVE_STUDY_FIGURE Apply light styling and save PNG + FIG files.

apply_light_figure_style(figHandle);

pngPath = fullfile( ...
    figureFolder, ...
    baseName + ".png");

figPath = fullfile( ...
    figureFolder, ...
    baseName + ".fig");

exportgraphics( ...
    figHandle, ...
    pngPath, ...
    "Resolution", 300, ...
    "BackgroundColor", "white");

savefig( ...
    figHandle, ...
    char(figPath));

end


function apply_light_figure_style(figHandle)
%APPLY_LIGHT_FIGURE_STYLE Force white-background publication style.

figHandle.Color = "w";

axList = findall(figHandle, "Type", "axes");

for i = 1:numel(axList)
    ax = axList(i);

    ax.Color = "w";
    ax.XColor = "k";
    ax.YColor = "k";

    if isprop(ax, "ZColor")
        ax.ZColor = "k";
    end

    ax.Title.Color = "k";
    ax.XLabel.Color = "k";
    ax.YLabel.Color = "k";

    if isprop(ax, "YAxis") && numel(ax.YAxis) > 1
        for j = 1:numel(ax.YAxis)
            ax.YAxis(j).Color = "k";
        end
    end

    ax.GridColor = [0.75 0.75 0.75];
    ax.GridAlpha = 0.35;

    if isprop(ax, "MinorGridColor")
        ax.MinorGridColor = [0.85 0.85 0.85];
    end

    if isprop(ax, "MinorGridAlpha")
        ax.MinorGridAlpha = 0.20;
    end

    ax.Box = "on";
end

legendList = findall(figHandle, "Type", "legend");

for i = 1:numel(legendList)
    lgd = legendList(i);
    lgd.TextColor = "k";
    lgd.Color = "w";
    lgd.EdgeColor = [0.25 0.25 0.25];
end

textList = findall(figHandle, "Type", "text");

for i = 1:numel(textList)
    if isprop(textList(i), "Color")
        textList(i).Color = "k";
    end
end

end
