diary off;

clear;
clc;
close all;

%% Project paths
studyFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(studyFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Baseline cycle and HPT design point
cfgBase = baseline_engine();
baselineResults = run_turbofan(cfgBase);

caseTag = "hpt_candidate_sensitivity";

station41 = baselineResults.stations.station41;
station45 = baselineResults.stations.station45;
mdotHPT_kg_s = baselineResults.mass.mdot_hpt_kg_s;
baselineHPT = baselineResults.hpt_sizing;

%% Mean-line design-space definition
% Keep this grid aligned with the design-space and candidate-ranking studies.
loadingCoefficients = 0.90:0.05:2.20;
flowCoefficients = 0.20:0.025:0.85;

fixedReaction = cfgBase.hpt.reaction;
fixedStageCount = cfgBase.hpt.stage_count;

[loadingGrid, flowGrid] = meshgrid( ...
    loadingCoefficients, ...
    flowCoefficients);

gridSize = size(loadingGrid);

%% Constraints held fixed across every sensitivity scenario
minimumMeanRadius_m = 0.24;
maximumMeanRadius_m = 0.33;
maximumExitSpanToRadius = 0.20;
minimumFlowCoefficient = 0.30;

%% Constraint values varied across scenarios
maximumMachLimits = [1.08, 1.09, 1.10];
maximumAbsoluteAngleLimits_deg = [68, 69, 70];

%% Ranking-weight sets
% Columns:
%   maximum Mach, radius deviation, exit span/radius, maximum flow angle
weightSetName = [
    "Current"
    "Equal"
    "Mach priority"
    "Compactness priority"
    "Span priority"
    "Angle priority"
];

weightMatrix = [
    0.35, 0.35, 0.15, 0.15
    0.25, 0.25, 0.25, 0.25
    0.50, 0.20, 0.15, 0.15
    0.25, 0.50, 0.15, 0.10
    0.25, 0.25, 0.35, 0.15
    0.25, 0.25, 0.15, 0.35
];

if any(abs(sum(weightMatrix, 2) - 1.0) > 1e-12)
    error("Every sensitivity weight set must sum to one.");
end

numberScenarios = ...
    numel(maximumMachLimits) ...
    * numel(maximumAbsoluteAngleLimits_deg) ...
    * height(weightSetName);

%% Robustness metric
% For each scenario:
%   percentile rank = 0 for the winner and 1 for the last candidate.
%
% A point that fails a scenario receives the penalty below. Therefore:
%   lower robustness score is better,
%   candidates that remain feasible across changing assumptions are favored.
infeasiblePercentilePenalty = 1.25;

numberCandidatesToPrint = 12;
numberCandidatesToLabel = 5;

%% Create matching Data and Figures run folders
runOutput = create_run_output_folders( ...
    projectRoot, ...
    cfgBase.meta.model_version);

fileSuffix = ...
    caseTag + "_" + runOutput.file_tag;

%% Start Command Window recording
commandWindowPath = fullfile( ...
    runOutput.data_folder, ...
    "command_window_" + fileSuffix + ".txt");

diary(char(commandWindowPath));

try
    fprintf("\nHPT candidate-sensitivity study started\n");
    fprintf("==================================================\n");
    fprintf("Model version:                %s\n", ...
        runOutput.version_tag);
    fprintf("Run number:                   %02d\n", ...
        runOutput.run_number);
    fprintf("Stage count:                  %d\n", ...
        fixedStageCount);
    fprintf("Fixed reaction:               %.3f\n", ...
        fixedReaction);
    fprintf("Number of design points:      %d\n", ...
        numel(loadingGrid));
    fprintf("Number of ranking scenarios:  %d\n\n", ...
        numberScenarios);

    fprintf("Fixed screening constraints\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Mean-radius range:            %.3f to %.3f m\n", ...
        minimumMeanRadius_m, ...
        maximumMeanRadius_m);
    fprintf("Maximum exit span/radius:     %.3f\n", ...
        maximumExitSpanToRadius);
    fprintf("Minimum flow coefficient:     %.3f\n\n", ...
        minimumFlowCoefficient);

    fprintf("Varied screening constraints\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Maximum Mach limits:          %s\n", ...
        join(string(maximumMachLimits), ", "));
    fprintf("Maximum angle limits:         %s deg\n\n", ...
        join(string(maximumAbsoluteAngleLimits_deg), ", "));

    %% Save exact study configuration
    configurationPath = fullfile( ...
        runOutput.data_folder, ...
        "configuration_" + fileSuffix + ".mat");

    save( ...
        configurationPath, ...
        "cfgBase", ...
        "loadingCoefficients", ...
        "flowCoefficients", ...
        "fixedReaction", ...
        "fixedStageCount", ...
        "minimumMeanRadius_m", ...
        "maximumMeanRadius_m", ...
        "maximumExitSpanToRadius", ...
        "minimumFlowCoefficient", ...
        "maximumMachLimits", ...
        "maximumAbsoluteAngleLimits_deg", ...
        "weightSetName", ...
        "weightMatrix", ...
        "infeasiblePercentilePenalty", ...
        "caseTag", ...
        "runOutput");

    %% Evaluate the mean-line grid once
    validPoint = false(gridSize);

    maximumMach = nan(gridSize);
    rotorInletAbsoluteMach = nan(gridSize);
    rotorInletRelativeMach = nan(gridSize);
    rotorExitAbsoluteMach = nan(gridSize);
    rotorExitRelativeMach = nan(gridSize);

    bladeSpeed_m_s = nan(gridSize);
    axialVelocity_m_s = nan(gridSize);
    meanRadius_m = nan(gridSize);
    inletSpan_m = nan(gridSize);
    exitSpan_m = nan(gridSize);
    exitSpanToMeanRadius = nan(gridSize);
    exitHubToTipRatio = nan(gridSize);

    alpha1_deg = nan(gridSize);
    alpha2_deg = nan(gridSize);
    beta1_deg = nan(gridSize);
    beta2_deg = nan(gridSize);
    maximumAbsoluteFlowAngle_deg = nan(gridSize);

    maximumMachLocation = strings(gridSize);
    aerodynamicStatus = strings(gridSize);
    errorMessage = strings(gridSize);

    for row = 1:gridSize(1)
        for column = 1:gridSize(2)
            psi = loadingGrid(row, column);
            phi = flowGrid(row, column);

            try
                stage = hpt_stage_sizing( ...
                    station41, ...
                    station45, ...
                    mdotHPT_kg_s, ...
                    cfgBase.shaft.high_spool_rpm, ...
                    cfgBase.thermo.cp_hot_J_kgK, ...
                    cfgBase.thermo.gamma_hot, ...
                    cfgBase.thermo.R_J_kgK, ...
                    fixedStageCount, ...
                    psi, ...
                    phi, ...
                    fixedReaction);

                validPoint(row, column) = true;

                maximumMach(row, column) = ...
                    stage.maximum_mach;

                rotorInletAbsoluteMach(row, column) = ...
                    stage.rotor_inlet_absolute_mach;

                rotorInletRelativeMach(row, column) = ...
                    stage.rotor_inlet_relative_mach;

                rotorExitAbsoluteMach(row, column) = ...
                    stage.rotor_exit_absolute_mach;

                rotorExitRelativeMach(row, column) = ...
                    stage.rotor_exit_relative_mach;

                bladeSpeed_m_s(row, column) = ...
                    stage.blade_speed_m_s;

                axialVelocity_m_s(row, column) = ...
                    stage.axial_velocity_m_s;

                meanRadius_m(row, column) = ...
                    stage.mean_radius_m;

                inletSpan_m(row, column) = ...
                    stage.blade_span_inlet_m;

                exitSpan_m(row, column) = ...
                    stage.blade_span_exit_m;

                exitSpanToMeanRadius(row, column) = ...
                    stage.blade_span_exit_m ...
                    / stage.mean_radius_m;

                exitHubToTipRatio(row, column) = ...
                    stage.hub_radius_exit_m ...
                    / stage.tip_radius_exit_m;

                alpha1_deg(row, column) = ...
                    stage.alpha1_deg;

                alpha2_deg(row, column) = ...
                    stage.alpha2_deg;

                beta1_deg(row, column) = ...
                    stage.beta1_deg;

                beta2_deg(row, column) = ...
                    stage.beta2_deg;

                maximumAbsoluteFlowAngle_deg(row, column) = ...
                    max(abs([ ...
                        stage.alpha1_deg, ...
                        stage.alpha2_deg, ...
                        stage.beta1_deg, ...
                        stage.beta2_deg]));

                maximumMachLocation(row, column) = ...
                    stage.maximum_mach_location;

                aerodynamicStatus(row, column) = ...
                    stage.aerodynamic_status;

            catch ME
                errorMessage(row, column) = ...
                    string(ME.message);
            end
        end
    end

    %% Metrics used in every ranking scenario
    baselineMeanRadius_m = ...
        baselineHPT.mean_radius_m;

    radiusDeviationFraction = ...
        abs(meanRadius_m - baselineMeanRadius_m) ...
        / baselineMeanRadius_m;

    passesFixedConstraints = ...
        validPoint ...
        & meanRadius_m >= minimumMeanRadius_m ...
        & meanRadius_m <= maximumMeanRadius_m ...
        & exitSpanToMeanRadius <= maximumExitSpanToRadius ...
        & flowGrid >= minimumFlowCoefficient;

    %% Sensitivity accumulators
    scenarioFeasibleCount = zeros(gridSize);
    scenarioWinCount = zeros(gridSize);
    scenarioTop3Count = zeros(gridSize);
    scenarioTop5Count = zeros(gridSize);

    percentileRankSum = zeros(gridSize);
    normalizedScoreSum = zeros(gridSize);

    scenarioNumber = 0;
    scenarioRows = cell(numberScenarios, 14);

    %% Run every ranking scenario
    for machIndex = 1:numel(maximumMachLimits)
        machLimit = maximumMachLimits(machIndex);

        for angleIndex = 1:numel(maximumAbsoluteAngleLimits_deg)
            angleLimit_deg = ...
                maximumAbsoluteAngleLimits_deg(angleIndex);

            for weightIndex = 1:height(weightSetName)
                scenarioNumber = scenarioNumber + 1;

                weights = ...
                    weightMatrix(weightIndex, :);

                feasibleMask = ...
                    passesFixedConstraints ...
                    & maximumMach <= machLimit ...
                    & maximumAbsoluteFlowAngle_deg <= angleLimit_deg;

                numberFeasible = nnz(feasibleMask);

                if numberFeasible == 0
                    error( ...
                        "Sensitivity scenario %d has no feasible candidates.", ...
                        scenarioNumber);
                end

                normalizedMach = normalize_masked_metric( ...
                    maximumMach, ...
                    feasibleMask);

                normalizedRadius = normalize_masked_metric( ...
                    radiusDeviationFraction, ...
                    feasibleMask);

                normalizedSpan = normalize_masked_metric( ...
                    exitSpanToMeanRadius, ...
                    feasibleMask);

                normalizedAngle = normalize_masked_metric( ...
                    maximumAbsoluteFlowAngle_deg, ...
                    feasibleMask);

                scenarioScore = nan(gridSize);

                scenarioScore(feasibleMask) = ...
                    weights(1) .* normalizedMach(feasibleMask) ...
                    + weights(2) .* normalizedRadius(feasibleMask) ...
                    + weights(3) .* normalizedSpan(feasibleMask) ...
                    + weights(4) .* normalizedAngle(feasibleMask);

                feasibleLinearIndices = ...
                    find(feasibleMask);

                sortingTable = table( ...
                    feasibleLinearIndices, ...
                    scenarioScore(feasibleMask), ...
                    maximumMach(feasibleMask), ...
                    meanRadius_m(feasibleMask), ...
                    'VariableNames', { ...
                        'LinearIndex', ...
                        'Score', ...
                        'MaximumMach', ...
                        'MeanRadius_m'});

                sortingTable = sortrows( ...
                    sortingTable, ...
                    {'Score', 'MaximumMach', 'MeanRadius_m'}, ...
                    {'ascend', 'ascend', 'ascend'});

                rankedLinearIndices = ...
                    sortingTable.LinearIndex;

                rankValue = ...
                    (1:numberFeasible)';

                if numberFeasible == 1
                    percentileRank = 0;
                else
                    percentileRank = ...
                        (rankValue - 1) ...
                        / (numberFeasible - 1);
                end

                scenarioFeasibleCount(rankedLinearIndices) = ...
                    scenarioFeasibleCount(rankedLinearIndices) + 1;

                scenarioWinCount(rankedLinearIndices(1)) = ...
                    scenarioWinCount(rankedLinearIndices(1)) + 1;

                scenarioTop3Count( ...
                    rankedLinearIndices(1:min(3, numberFeasible))) = ...
                    scenarioTop3Count( ...
                    rankedLinearIndices(1:min(3, numberFeasible))) + 1;

                scenarioTop5Count( ...
                    rankedLinearIndices(1:min(5, numberFeasible))) = ...
                    scenarioTop5Count( ...
                    rankedLinearIndices(1:min(5, numberFeasible))) + 1;

                percentileRankSum(rankedLinearIndices) = ...
                    percentileRankSum(rankedLinearIndices) ...
                    + percentileRank;

                normalizedScoreSum(rankedLinearIndices) = ...
                    normalizedScoreSum(rankedLinearIndices) ...
                    + sortingTable.Score;

                winnerIndex = rankedLinearIndices(1);

                scenarioRows(scenarioNumber, :) = { ...
                    scenarioNumber, ...
                    machLimit, ...
                    angleLimit_deg, ...
                    weightSetName(weightIndex), ...
                    weights(1), ...
                    weights(2), ...
                    weights(3), ...
                    weights(4), ...
                    numberFeasible, ...
                    loadingGrid(winnerIndex), ...
                    flowGrid(winnerIndex), ...
                    scenarioScore(winnerIndex), ...
                    maximumMach(winnerIndex), ...
                    meanRadius_m(winnerIndex)};
            end
        end
    end

    %% Calculate cross-scenario robustness score
    scenarioCoverage = ...
        scenarioFeasibleCount ...
        / numberScenarios;

    meanPercentileWhenFeasible = ...
        nan(gridSize);

    hasScenarioCoverage = ...
        scenarioFeasibleCount > 0;

    meanPercentileWhenFeasible(hasScenarioCoverage) = ...
        percentileRankSum(hasScenarioCoverage) ...
        ./ scenarioFeasibleCount(hasScenarioCoverage);

    meanNormalizedScoreWhenFeasible = ...
        nan(gridSize);

    meanNormalizedScoreWhenFeasible(hasScenarioCoverage) = ...
        normalizedScoreSum(hasScenarioCoverage) ...
        ./ scenarioFeasibleCount(hasScenarioCoverage);

    robustnessScore = ...
        (percentileRankSum ...
        + (numberScenarios - scenarioFeasibleCount) ...
        .* infeasiblePercentilePenalty) ...
        / numberScenarios;

    robustnessScore(~validPoint) = NaN;

    %% Complete design-space table
    designSpaceTable = table( ...
        loadingGrid(:), ...
        flowGrid(:), ...
        repmat(fixedReaction, numel(loadingGrid), 1), ...
        validPoint(:), ...
        passesFixedConstraints(:), ...
        maximumMach(:), ...
        rotorInletAbsoluteMach(:), ...
        rotorInletRelativeMach(:), ...
        rotorExitAbsoluteMach(:), ...
        rotorExitRelativeMach(:), ...
        bladeSpeed_m_s(:), ...
        axialVelocity_m_s(:), ...
        meanRadius_m(:), ...
        radiusDeviationFraction(:), ...
        inletSpan_m(:), ...
        exitSpan_m(:), ...
        exitSpanToMeanRadius(:), ...
        exitHubToTipRatio(:), ...
        alpha1_deg(:), ...
        alpha2_deg(:), ...
        beta1_deg(:), ...
        beta2_deg(:), ...
        maximumAbsoluteFlowAngle_deg(:), ...
        scenarioFeasibleCount(:), ...
        scenarioCoverage(:), ...
        scenarioWinCount(:), ...
        scenarioTop3Count(:), ...
        scenarioTop5Count(:), ...
        meanPercentileWhenFeasible(:), ...
        meanNormalizedScoreWhenFeasible(:), ...
        robustnessScore(:), ...
        maximumMachLocation(:), ...
        aerodynamicStatus(:), ...
        errorMessage(:), ...
        'VariableNames', { ...
            'LoadingCoefficient_psi', ...
            'FlowCoefficient_phi', ...
            'Reaction', ...
            'ValidPoint', ...
            'PassesFixedConstraints', ...
            'MaximumMach', ...
            'RotorInletAbsoluteMach', ...
            'RotorInletRelativeMach', ...
            'RotorExitAbsoluteMach', ...
            'RotorExitRelativeMach', ...
            'BladeSpeed_m_s', ...
            'AxialVelocity_m_s', ...
            'MeanRadius_m', ...
            'RadiusDeviationFraction', ...
            'InletSpan_m', ...
            'ExitSpan_m', ...
            'ExitSpanToMeanRadius', ...
            'ExitHubToTipRatio', ...
            'Alpha1_deg', ...
            'Alpha2_deg', ...
            'Beta1_deg', ...
            'Beta2_deg', ...
            'MaximumAbsoluteFlowAngle_deg', ...
            'ScenarioFeasibleCount', ...
            'ScenarioCoverage_fraction', ...
            'ScenarioWinCount', ...
            'ScenarioTop3Count', ...
            'ScenarioTop5Count', ...
            'MeanPercentileRankWhenFeasible', ...
            'MeanNormalizedScoreWhenFeasible', ...
            'RobustnessScore', ...
            'MaximumMachLocation', ...
            'AerodynamicStatus', ...
            'ErrorMessage'});

    reviewedMask = ...
        validPoint ...
        & scenarioFeasibleCount > 0;

    robustCandidateTable = ...
        designSpaceTable(reviewedMask(:), :);

    robustCandidateTable = sortrows( ...
        robustCandidateTable, ...
        { ...
            'RobustnessScore', ...
            'ScenarioWinCount', ...
            'ScenarioTop3Count', ...
            'MaximumMach'}, ...
        { ...
            'ascend', ...
            'descend', ...
            'descend', ...
            'ascend'});

    robustCandidateTable.RobustRank = ...
        (1:height(robustCandidateTable))';

    robustCandidateTable = movevars( ...
        robustCandidateTable, ...
        'RobustRank', ...
        'Before', ...
        'LoadingCoefficient_psi');

    %% Scenario-winner table
    scenarioWinnerTable = cell2table( ...
        scenarioRows, ...
        'VariableNames', { ...
            'Scenario', ...
            'MaximumMachLimit', ...
            'MaximumAngleLimit_deg', ...
            'WeightSet', ...
            'WeightMaximumMach', ...
            'WeightRadiusDeviation', ...
            'WeightExitSpanRatio', ...
            'WeightFlowAngle', ...
            'FeasibleCandidateCount', ...
            'WinnerLoadingCoefficient_psi', ...
            'WinnerFlowCoefficient_phi', ...
            'WinnerScenarioScore', ...
            'WinnerMaximumMach', ...
            'WinnerMeanRadius_m'});

    %% Baseline and leading robust candidate comparison
    bestRobustCandidate = ...
        robustCandidateTable(1, :);

    comparisonCase = [
        "Current baseline"
        "Top robust candidate"
    ];

    loadingCoefficient_psi = [
        cfgBase.hpt.loading_coefficient
        bestRobustCandidate.LoadingCoefficient_psi
    ];

    flowCoefficient_phi = [
        cfgBase.hpt.flow_coefficient
        bestRobustCandidate.FlowCoefficient_phi
    ];

    maximumMachComparison = [
        baselineHPT.maximum_mach
        bestRobustCandidate.MaximumMach
    ];

    meanRadiusComparison_m = [
        baselineHPT.mean_radius_m
        bestRobustCandidate.MeanRadius_m
    ];

    bladeSpeedComparison_m_s = [
        baselineHPT.blade_speed_m_s
        bestRobustCandidate.BladeSpeed_m_s
    ];

    exitSpanRatioComparison = [
        baselineHPT.blade_span_exit_m ...
            / baselineHPT.mean_radius_m
        bestRobustCandidate.ExitSpanToMeanRadius
    ];

    maximumAngleComparison_deg = [
        max(abs([ ...
            baselineHPT.alpha1_deg, ...
            baselineHPT.alpha2_deg, ...
            baselineHPT.beta1_deg, ...
            baselineHPT.beta2_deg]))
        bestRobustCandidate.MaximumAbsoluteFlowAngle_deg
    ];

    scenarioCoverageComparison = [
        NaN
        bestRobustCandidate.ScenarioCoverage_fraction
    ];

    robustnessScoreComparison = [
        NaN
        bestRobustCandidate.RobustnessScore
    ];

    comparisonTable = table( ...
        comparisonCase, ...
        loadingCoefficient_psi, ...
        flowCoefficient_phi, ...
        maximumMachComparison, ...
        meanRadiusComparison_m, ...
        bladeSpeedComparison_m_s, ...
        exitSpanRatioComparison, ...
        maximumAngleComparison_deg, ...
        scenarioCoverageComparison, ...
        robustnessScoreComparison, ...
        'VariableNames', { ...
            'Case', ...
            'LoadingCoefficient_psi', ...
            'FlowCoefficient_phi', ...
            'MaximumMach', ...
            'MeanRadius_m', ...
            'BladeSpeed_m_s', ...
            'ExitSpanToMeanRadius', ...
            'MaximumAbsoluteFlowAngle_deg', ...
            'ScenarioCoverage_fraction', ...
            'RobustnessScore'});

    %% Display results
    fprintf("Sensitivity summary\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Valid mean-line points:      %d of %d\n", ...
        nnz(validPoint), ...
        numel(validPoint));
    fprintf("Points feasible in at least one scenario: %d\n\n", ...
        height(robustCandidateTable));

    fprintf("Baseline comparison\n");
    disp(comparisonTable);

    fprintf("Top %d robust candidates\n", ...
        min(numberCandidatesToPrint, height(robustCandidateTable)));

    displayVariables = { ...
        'RobustRank', ...
        'LoadingCoefficient_psi', ...
        'FlowCoefficient_phi', ...
        'RobustnessScore', ...
        'ScenarioCoverage_fraction', ...
        'ScenarioWinCount', ...
        'ScenarioTop3Count', ...
        'MaximumMach', ...
        'MeanRadius_m', ...
        'BladeSpeed_m_s', ...
        'ExitSpanToMeanRadius', ...
        'MaximumAbsoluteFlowAngle_deg'};

    disp(robustCandidateTable( ...
        1:min(numberCandidatesToPrint, height(robustCandidateTable)), ...
        displayVariables));

    fprintf("The robustness score measures sensitivity to the\n");
    fprintf("tested limits and weights. It is not a direct\n");
    fprintf("aerodynamic efficiency or structural-life metric.\n\n");

    %% Save tabular output
    designSpaceCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "hpt_sensitivity_design_space_" + fileSuffix + ".csv");

    robustCandidatesCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "hpt_robust_candidates_" + fileSuffix + ".csv");

    scenarioWinnersCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "hpt_sensitivity_scenarios_" + fileSuffix + ".csv");

    comparisonCsvPath = fullfile( ...
        runOutput.data_folder, ...
        "hpt_robust_candidate_comparison_" + fileSuffix + ".csv");

    writetable( ...
        designSpaceTable, ...
        designSpaceCsvPath);

    writetable( ...
        robustCandidateTable, ...
        robustCandidatesCsvPath);

    writetable( ...
        scenarioWinnerTable, ...
        scenarioWinnersCsvPath);

    writetable( ...
        comparisonTable, ...
        comparisonCsvPath);

    %% Figure 1: robustness score in psi-phi space
    figureRobustness = figure( ...
        "Name", ...
        "HPT candidate robustness", ...
        "Color", ...
        "w");

    robustnessImage = imagesc( ...
        loadingCoefficients, ...
        flowCoefficients, ...
        robustnessScore);

    set(gca, "YDir", "normal");

    robustnessImage.AlphaData = ...
        double(reviewedMask);

    robustnessImage.AlphaDataMapping = ...
        "none";

    reviewedScores = ...
        robustnessScore(reviewedMask);

    caxis([min(reviewedScores), max(reviewedScores)]);

    robustnessColorbar = colorbar;
    robustnessColorbar.Label.String = ...
        "Robustness score (lower is better)";

    hold on;

    plot( ...
        cfgBase.hpt.loading_coefficient, ...
        cfgBase.hpt.flow_coefficient, ...
        "ko", ...
        "MarkerFaceColor", ...
        "k", ...
        "MarkerSize", ...
        8, ...
        "DisplayName", ...
        "Current baseline");

    plot( ...
        bestRobustCandidate.LoadingCoefficient_psi, ...
        bestRobustCandidate.FlowCoefficient_phi, ...
        "kp", ...
        "MarkerFaceColor", ...
        "w", ...
        "MarkerSize", ...
        14, ...
        "LineWidth", ...
        1.3, ...
        "DisplayName", ...
        "Top robust candidate");

    xlabel("Stage Loading Coefficient, \psi");
    ylabel("Flow Coefficient, \phi");

    title({ ...
        "HPT Candidate Robustness Across 54 Ranking Scenarios", ...
        "Blank cells were infeasible in every tested scenario"});

    legend( ...
        "Location", ...
        "northeast");

    grid on;
    box on;

    %% Figure 2: robust candidate Mach-radius tradeoff
    figureTradeoff = figure( ...
        "Name", ...
        "HPT robust candidate tradeoff", ...
        "Color", ...
        "w");

    markerSize = ...
        70 ...
        + 900 ...
        .* robustCandidateTable.ExitSpanToMeanRadius;

    scatter( ...
        robustCandidateTable.MeanRadius_m, ...
        robustCandidateTable.MaximumMach, ...
        markerSize, ...
        robustCandidateTable.RobustnessScore, ...
        "filled");

    tradeoffColorbar = colorbar;
    tradeoffColorbar.Label.String = ...
        "Robustness score (lower is better)";

    hold on;

    plot( ...
        baselineHPT.mean_radius_m, ...
        baselineHPT.maximum_mach, ...
        "ko", ...
        "MarkerFaceColor", ...
        "k", ...
        "MarkerSize", ...
        8, ...
        "DisplayName", ...
        "Current baseline");

    plot( ...
        bestRobustCandidate.MeanRadius_m, ...
        bestRobustCandidate.MaximumMach, ...
        "kp", ...
        "MarkerFaceColor", ...
        "w", ...
        "MarkerSize", ...
        14, ...
        "LineWidth", ...
        1.3, ...
        "DisplayName", ...
        "Top robust candidate");

    for candidateNumber = ...
            1:min(numberCandidatesToLabel, height(robustCandidateTable))

        text( ...
            robustCandidateTable.MeanRadius_m(candidateNumber), ...
            robustCandidateTable.MaximumMach(candidateNumber), ...
            "  #" + string(candidateNumber), ...
            "Color", ...
            "k", ...
            "FontWeight", ...
            "bold", ...
            "VerticalAlignment", ...
            "middle");
    end

    xlabel("Mean Radius (m)");
    ylabel("Maximum Mean-Line Mach Number");

    title({ ...
        "Robust HPT Candidate Mach-Radius Tradeoff", ...
        "Marker size scales with exit span / mean radius"});

    legend( ...
        "Location", ...
        "northeast");

    grid on;
    box on;

    %% Apply consistent black-text figure style
    apply_light_figure_style(figureRobustness);
    apply_light_figure_style(figureTradeoff);

    %% Save figures
    robustnessFigureBase = ...
        "candidate_robustness_map_" + fileSuffix;

    tradeoffFigureBase = ...
        "robust_candidate_tradeoff_" + fileSuffix;

    save_study_figure( ...
        figureRobustness, ...
        runOutput.figure_folder, ...
        robustnessFigureBase);

    save_study_figure( ...
        figureTradeoff, ...
        runOutput.figure_folder, ...
        tradeoffFigureBase);

    %% Save complete MATLAB results
    resultsPath = fullfile( ...
        runOutput.data_folder, ...
        "study_results_" + fileSuffix + ".mat");

    save( ...
        resultsPath, ...
        "cfgBase", ...
        "baselineResults", ...
        "loadingCoefficients", ...
        "flowCoefficients", ...
        "fixedReaction", ...
        "fixedStageCount", ...
        "minimumMeanRadius_m", ...
        "maximumMeanRadius_m", ...
        "maximumExitSpanToRadius", ...
        "minimumFlowCoefficient", ...
        "maximumMachLimits", ...
        "maximumAbsoluteAngleLimits_deg", ...
        "weightSetName", ...
        "weightMatrix", ...
        "infeasiblePercentilePenalty", ...
        "designSpaceTable", ...
        "robustCandidateTable", ...
        "scenarioWinnerTable", ...
        "comparisonTable", ...
        "caseTag", ...
        "runOutput");

    fprintf("Saved output files\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Configuration:       %s\n", configurationPath);
    fprintf("Results MAT:         %s\n", resultsPath);
    fprintf("Design-space CSV:    %s\n", designSpaceCsvPath);
    fprintf("Robust-candidate CSV:%s\n", robustCandidatesCsvPath);
    fprintf("Scenario CSV:        %s\n", scenarioWinnersCsvPath);
    fprintf("Comparison CSV:      %s\n", comparisonCsvPath);
    fprintf("Command log:         %s\n", commandWindowPath);
    fprintf("==================================================\n");
    fprintf("HPT candidate-sensitivity study complete\n\n");

    diary off;

catch ME
    fprintf(2, ...
        "\nHPT candidate-sensitivity study failed.\n\n");

    fprintf(2, "%s\n", ...
        getReport( ...
            ME, ...
            "extended", ...
            "hyperlinks", ...
            "off"));

    diary off;
    rethrow(ME);
end


function normalizedMetric = normalize_masked_metric( ...
    rawMetric, activeMask)
%NORMALIZE_MASKED_METRIC Min-max normalize selected values to [0, 1].

normalizedMetric = nan(size(rawMetric));

activeValues = rawMetric(activeMask);

minimumValue = min(activeValues);
maximumValue = max(activeValues);
valueRange = maximumValue - minimumValue;

if valueRange <= eps(max(abs([minimumValue, maximumValue])))
    normalizedMetric(activeMask) = 0;
else
    normalizedMetric(activeMask) = ...
        (activeValues - minimumValue) ...
        / valueRange;
end

end


function save_study_figure( ...
    figHandle, figureFolder, baseName)
%SAVE_STUDY_FIGURE Apply styling and save PNG plus editable FIG.

apply_light_figure_style(figHandle);

pngPath = fullfile( ...
    figureFolder, ...
    baseName + ".png");

figPath = fullfile( ...
    figureFolder, ...
    baseName + ".fig");

exportgraphics( ...
    figHandle, ...
    pngPath, ...
    "Resolution", ...
    300, ...
    "BackgroundColor", ...
    "white");

savefig( ...
    figHandle, ...
    figPath);

end


function apply_light_figure_style(figHandle)
%APPLY_LIGHT_FIGURE_STYLE Force readable white figures with black text.

figHandle.Color = "w";

axesList = findall( ...
    figHandle, ...
    "Type", ...
    "axes");

for i = 1:numel(axesList)
    ax = axesList(i);

    ax.Color = "w";
    ax.XColor = "k";
    ax.YColor = "k";
    ax.GridColor = "k";
    ax.GridAlpha = 0.18;

    if isprop(ax, "MinorGridColor")
        ax.MinorGridColor = "k";
    end

    if isprop(ax, "MinorGridAlpha")
        ax.MinorGridAlpha = 0.10;
    end

    ax.Box = "on";

    if isprop(ax, "Toolbar")
        ax.Toolbar.Visible = "off";
    end
end

% Set only actual text objects to black. Do not assign the generic
% Color property on axes or legends, because for those objects Color
% controls the background rather than the text.
textList = findall( ...
    figHandle, ...
    "Type", ...
    "text");

for i = 1:numel(textList)
    textList(i).Color = "k";
end

legendList = findall( ...
    figHandle, ...
    "Type", ...
    "legend");

for i = 1:numel(legendList)
    lgd = legendList(i);

    if isprop(lgd, "TextColor")
        lgd.TextColor = "k";
    end

    if isprop(lgd, "Color")
        lgd.Color = "w";
    end

    if isprop(lgd, "EdgeColor")
        lgd.EdgeColor = "k";
    end
end

colorbarList = findall( ...
    figHandle, ...
    "Type", ...
    "ColorBar");

for i = 1:numel(colorbarList)
    cb = colorbarList(i);
    cb.Color = "k";
    cb.Label.Color = "k";

    if isprop(cb, "Title")
        cb.Title.Color = "k";
    end
end

end
