diary off;

clear;
clc;
close all;

%% Project paths
studyFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(studyFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Run inherited APR design point
cfg = baseline_engine();
cfg = apply_cf34_operating_point( ...
    cfg, ...
    "maximum_takeoff_apr");

results = run_turbofan(cfg);

caseTag = "cf34_fixed_nozzle_verification";

%% Create output folders
runOutput = create_run_output_folders( ...
    projectRoot, ...
    cfg.meta.model_version);

fileSuffix = ...
    caseTag + "_" + runOutput.file_tag;

commandWindowPath = fullfile( ...
    runOutput.data_folder, ...
    "command_window_" + fileSuffix + ".txt");

diary(char(commandWindowPath));

try
    fprintf("\nCF34 fixed-nozzle geometry verification started\n");
    fprintf("==================================================\n");
    fprintf("Model version:      %s\n", runOutput.version_tag);
    fprintf("Run number:         %02d\n", runOutput.run_number);
    fprintf("Operating point:    %s\n\n", ...
        results.operating_point.name);

    %% Evaluate fixed-area nozzle capacities
    coreCapacity = nozzle_fixed_area_capacity( ...
        results.stations.station8, ...
        results.atm.pressure_Pa, ...
        cfg.geometry.core_nozzle_area_m2, ...
        cfg.loss.core_nozzle_pressure_recovery, ...
        cfg.thermo.gamma_hot, ...
        cfg.thermo.R_J_kgK);

    bypassCapacity = nozzle_fixed_area_capacity( ...
        results.stations.station18, ...
        results.atm.pressure_Pa, ...
        cfg.geometry.bypass_nozzle_area_m2, ...
        cfg.loss.bypass_nozzle_pressure_recovery, ...
        cfg.thermo.gamma_cold, ...
        cfg.thermo.R_J_kgK);

    %% Compare prescribed stream flow with fixed-area capacity
    stream = [
        "Core"
        "Bypass"
    ];

    fixedArea_m2 = [
        cfg.geometry.core_nozzle_area_m2
        cfg.geometry.bypass_nozzle_area_m2
    ];

    demandedMassFlow_kg_s = [
        results.mass.mdot_hpt_kg_s
        results.mass.mdot_bypass_air_kg_s
    ];

    supportedMassFlow_kg_s = [
        coreCapacity.mass_flow_capacity_kg_s
        bypassCapacity.mass_flow_capacity_kg_s
    ];

    massFlowResidual_kg_s = ...
        demandedMassFlow_kg_s ...
        - supportedMassFlow_kg_s;

    massFlowResidual_percent = ...
        100 ...
        * massFlowResidual_kg_s ...
        ./ demandedMassFlow_kg_s;

    currentCalculatedArea_m2 = [
        results.stations.station9.area_m2
        results.stations.station19.area_m2
    ];

    areaDifference_m2 = ...
        fixedArea_m2 ...
        - currentCalculatedArea_m2;

    exitMach = [
        coreCapacity.Mach
        bypassCapacity.Mach
    ];

    isChoked = [
        coreCapacity.is_choked
        bypassCapacity.is_choked
    ];

    capacityTable = table( ...
        stream, ...
        fixedArea_m2, ...
        currentCalculatedArea_m2, ...
        areaDifference_m2, ...
        demandedMassFlow_kg_s, ...
        supportedMassFlow_kg_s, ...
        massFlowResidual_kg_s, ...
        massFlowResidual_percent, ...
        exitMach, ...
        isChoked, ...
        'VariableNames', { ...
            'Stream', ...
            'FixedArea_m2', ...
            'CurrentCalculatedArea_m2', ...
            'AreaDifference_m2', ...
            'DemandedMassFlow_kg_s', ...
            'SupportedMassFlow_kg_s', ...
            'MassFlowResidual_kg_s', ...
            'MassFlowResidual_percent', ...
            'ExitMach', ...
            'IsChoked'});

    disp(capacityTable);

    %% Verification checks
    massFlowTolerance_kg_s = 1e-4;
    areaTolerance_m2 = 1e-8;

    coreMassFlowPass = ...
        abs(massFlowResidual_kg_s(1)) ...
        <= massFlowTolerance_kg_s;

    bypassMassFlowPass = ...
        abs(massFlowResidual_kg_s(2)) ...
        <= massFlowTolerance_kg_s;

    areaPass = ...
        all(abs(areaDifference_m2) <= areaTolerance_m2);

    chokingPass = ...
        coreCapacity.is_choked ...
        && ~bypassCapacity.is_choked;

    fprintf("Verification checks\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Core mass-flow capacity:      %s\n", ...
        string(coreMassFlowPass));
    fprintf("Bypass mass-flow capacity:    %s\n", ...
        string(bypassMassFlowPass));
    fprintf("Captured-area consistency:    %s\n", ...
        string(areaPass));
    fprintf("Expected choking states:      %s\n\n", ...
        string(chokingPass));

    if ~( ...
            coreMassFlowPass ...
            && bypassMassFlowPass ...
            && areaPass ...
            && chokingPass)
        error( ...
            "Fixed-nozzle design-point verification failed.");
    end

    %% Save outputs
    csvPath = fullfile( ...
        runOutput.data_folder, ...
        "fixed_nozzle_verification_" + fileSuffix + ".csv");

    resultsPath = fullfile( ...
        runOutput.data_folder, ...
        "fixed_nozzle_verification_" + fileSuffix + ".mat");

    configurationPath = fullfile( ...
        runOutput.data_folder, ...
        "configuration_" + fileSuffix + ".mat");

    writetable( ...
        capacityTable, ...
        csvPath);

    save( ...
        resultsPath, ...
        "capacityTable", ...
        "coreCapacity", ...
        "bypassCapacity", ...
        "results", ...
        "caseTag", ...
        "runOutput");

    save( ...
        configurationPath, ...
        "cfg", ...
        "caseTag", ...
        "runOutput");

    fprintf("Saved output files\n");
    fprintf("--------------------------------------------------\n");
    fprintf("Configuration: %s\n", configurationPath);
    fprintf("Results MAT:   %s\n", resultsPath);
    fprintf("Results CSV:   %s\n", csvPath);
    fprintf("Command log:   %s\n", commandWindowPath);
    fprintf("==================================================\n");
    fprintf("CF34 fixed-nozzle geometry verification PASSED\n\n");

    diary off;

catch ME
    fprintf(2, ...
        "\nCF34 fixed-nozzle geometry verification failed.\n\n");

    fprintf(2, "%s\n", ...
        getReport( ...
            ME, ...
            "extended", ...
            "hyperlinks", ...
            "off"));

    diary off;
    rethrow(ME);
end
