function corrected = corrected_flow_speed( ...
    mdot_kg_s, ...
    shaftSpeed_rpm, ...
    inletTotalTemperature_K, ...
    inletTotalPressure_Pa, ...
    referenceTemperature_K, ...
    referencePressure_Pa)
%CORRECTED_FLOW_SPEED Calculate dimensional corrected flow and speed.
%
% Definitions:
%
%   theta = Tt / Tref
%   delta = Pt / Pref
%
%   corrected mass flow = mdot * sqrt(theta) / delta
%   corrected speed     = N / sqrt(theta)
%
% These are dimensional corrected quantities referenced to the supplied
% standard state. They are not normalized compressor-map coordinates.

validateattributes(mdot_kg_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

validateattributes(shaftSpeed_rpm, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

validateattributes(inletTotalTemperature_K, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

validateattributes(inletTotalPressure_Pa, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

validateattributes(referenceTemperature_K, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

validateattributes(referencePressure_Pa, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

theta = ...
    inletTotalTemperature_K ...
    / referenceTemperature_K;

delta = ...
    inletTotalPressure_Pa ...
    / referencePressure_Pa;

correctedMassFlow_kg_s = ...
    mdot_kg_s ...
    * sqrt(theta) ...
    / delta;

correctedSpeed_rpm = ...
    shaftSpeed_rpm ...
    / sqrt(theta);

corrected = struct();

corrected.theta = ...
    theta;

corrected.delta = ...
    delta;

corrected.mass_flow_kg_s = ...
    correctedMassFlow_kg_s;

corrected.speed_rpm = ...
    correctedSpeed_rpm;

corrected.reference_temperature_K = ...
    referenceTemperature_K;

corrected.reference_pressure_Pa = ...
    referencePressure_Pa;

corrected.inlet_total_temperature_K = ...
    inletTotalTemperature_K;

corrected.inlet_total_pressure_Pa = ...
    inletTotalPressure_Pa;

corrected.actual_mass_flow_kg_s = ...
    mdot_kg_s;

corrected.actual_speed_rpm = ...
    shaftSpeed_rpm;

end
