function [matPath, csvPath] = export_hpt_blade_conditions( ...
    results, outputFolder, fileSuffix)
%EXPORT_HPT_BLADE_CONDITIONS Export Project 1 HPT design conditions.
%
% Creates:
%   hpt_blade_design_point.mat
%   hpt_blade_design_point.csv

validateattributes(fileSuffix, ...
    {'char', 'string'}, {'nonempty'});

fileSuffix = string(fileSuffix);

if ~exist(outputFolder, "dir")
    mkdir(outputFolder);
end

cfg = results.cfg;
s = results.stations;
m = results.mass;
hpt = results.hpt_sizing;

%% Structured MATLAB handoff
bladeBC.metadata.engine_name = cfg.meta.name;
bladeBC.metadata.model_version = cfg.meta.model_version;
bladeBC.metadata.operating_condition = cfg.meta.condition;

bladeBC.flight.altitude_m = cfg.flight.altitude_m;
bladeBC.flight.Mach = cfg.flight.Mach;

bladeBC.cooling.bleed_fraction = ...
    results.cooling.bleed_fraction;

bladeBC.cooling.mdot_coolant_kg_s = ...
    m.mdot_cooling_air_kg_s;

bladeBC.cooling.supply_Tt_K = ...
    s.station3.Tt_K;

bladeBC.cooling.supply_Pt_Pa = ...
    s.station3.Pt_Pa;

bladeBC.hot_gas.combustor_exit_Tt_K = ...
    s.station4.Tt_K;

bladeBC.hot_gas.combustor_exit_Pt_Pa = ...
    s.station4.Pt_Pa;

bladeBC.hot_gas.rotor_inlet_Tt_K = ...
    s.station41.Tt_K;

bladeBC.hot_gas.rotor_inlet_Pt_Pa = ...
    s.station41.Pt_Pa;

bladeBC.hot_gas.rotor_exit_Tt_K = ...
    s.station45.Tt_K;

bladeBC.hot_gas.rotor_exit_Pt_Pa = ...
    s.station45.Pt_Pa;

bladeBC.hot_gas.mdot_hpt_kg_s = ...
    m.mdot_hpt_kg_s;

bladeBC.stage = hpt;

%% Save MATLAB structure
matPath = fullfile( ...
    outputFolder, ...
    "hpt_blade_design_point_" + fileSuffix + ".mat");

save(matPath, "bladeBC");

%% Human-readable one-row CSV
handoffTable = table( ...
    string(cfg.meta.model_version), ...
    cfg.flight.altitude_m, ...
    cfg.flight.Mach, ...
    100 * results.cooling.bleed_fraction, ...
    m.mdot_cooling_air_kg_s, ...
    s.station3.Tt_K, ...
    s.station3.Pt_Pa / 1000, ...
    s.station4.Tt_K, ...
    s.station4.Pt_Pa / 1000, ...
    s.station41.Tt_K, ...
    s.station41.Pt_Pa / 1000, ...
    s.station45.Tt_K, ...
    s.station45.Pt_Pa / 1000, ...
    m.mdot_hpt_kg_s, ...
    hpt.shaft_speed_rpm, ...
    hpt.omega_rad_s, ...
    hpt.total_specific_work_J_kg, ...
    hpt.loading_coefficient, ...
    hpt.flow_coefficient, ...
    hpt.reaction, ...
    hpt.blade_speed_m_s, ...
    hpt.axial_velocity_m_s, ...
    hpt.mean_radius_m, ...
    hpt.hub_radius_inlet_m, ...
    hpt.tip_radius_inlet_m, ...
    hpt.blade_span_inlet_m, ...
    hpt.hub_radius_exit_m, ...
    hpt.tip_radius_exit_m, ...
    hpt.blade_span_exit_m, ...
    hpt.alpha1_deg, ...
    hpt.alpha2_deg, ...
    hpt.beta1_deg, ...
    hpt.beta2_deg, ...
    hpt.rotor_inlet_static_temperature_K, ...
    hpt.rotor_inlet_static_pressure_Pa / 1000, ...
    hpt.rotor_exit_static_temperature_K, ...
    hpt.rotor_exit_static_pressure_Pa / 1000, ...
    'VariableNames', { ...
    'ModelVersion', ...
    'Altitude_m', ...
    'FlightMach', ...
    'CoolingBleed_percent', ...
    'CoolingFlow_kg_s', ...
    'CoolantSupply_Tt_K', ...
    'CoolantSupply_Pt_kPa', ...
    'CombustorExit_Tt_K', ...
    'CombustorExit_Pt_kPa', ...
    'HPTRotorInlet_Tt_K', ...
    'HPTRotorInlet_Pt_kPa', ...
    'HPTRotorExit_Tt_K', ...
    'HPTRotorExit_Pt_kPa', ...
    'HPTMassFlow_kg_s', ...
    'HighSpoolSpeed_rpm', ...
    'Omega_rad_s', ...
    'HPTSpecificWork_J_kg', ...
    'LoadingCoefficient', ...
    'FlowCoefficient', ...
    'Reaction', ...
    'BladeSpeed_m_s', ...
    'AxialVelocity_m_s', ...
    'MeanRadius_m', ...
    'InletHubRadius_m', ...
    'InletTipRadius_m', ...
    'InletBladeSpan_m', ...
    'ExitHubRadius_m', ...
    'ExitTipRadius_m', ...
    'ExitBladeSpan_m', ...
    'Alpha1_deg', ...
    'Alpha2_deg', ...
    'Beta1_deg', ...
    'Beta2_deg', ...
    'RotorInletStaticT_K', ...
    'RotorInletStaticP_kPa', ...
    'RotorExitStaticT_K', ...
    'RotorExitStaticP_kPa'});

csvPath = fullfile( ...
    outputFolder, ...
    "hpt_blade_design_point_" + fileSuffix + ".csv");

writetable(handoffTable, csvPath);

end