function match = match_cf34_multipoint(cfgApr, diagnosticOptions)
%MATCH_CF34_MULTIPOINT Diagnose three public CF34-10E feasibility targets.
% This reduced-order, steady-state, fixed-nozzle-area matcher preserves the
% Automatic Power Reserve (APR) design point and diagnoses normal takeoff,
% climb-out, and approach targets from the ICAO Engine Emissions Databank
% (EDB). It is not an accepted off-design model or control schedule.
% Effective core flow, bypass ratio, overall pressure ratio, and combustor
% exit temperature minimize thrust, fuel-flow, and nozzle-capacity residuals.
% APR logarithmic pressure-rise fractions define the component split.
% Bounded deterministic local searches do not prove global infeasibility.
% diagnosticOptions may change solver budgets only.

validateattributes(cfgApr, {'struct'}, {'scalar'});

if nargin < 2
    diagnosticOptions = struct();
end

validateattributes(diagnosticOptions, {'struct'}, {'scalar'});

requiredGeometryFields = [ ...
    "core_nozzle_area_m2", ...
    "bypass_nozzle_area_m2"];

for fieldIndex = 1:numel(requiredGeometryFields)
    if ~isfield(cfgApr.geometry, requiredGeometryFields(fieldIndex))
        error( ...
            "Missing fixed-nozzle geometry field: %s", ...
            requiredGeometryFields(fieldIndex));
    end
end

%% Preserve and evaluate the inherited APR baseline
aprCfg = cfgApr;
aprResults = run_turbofan(aprCfg);

designComponentPressureRatios = [ ...
    aprCfg.engine.fan_pressure_ratio, ...
    aprCfg.engine.lpc_pressure_ratio, ...
    aprCfg.engine.hpc_pressure_ratio];

designOverallPressureRatio = ...
    prod(designComponentPressureRatios);

logPressureRiseFractions = ...
    log(designComponentPressureRatios) ...
    / log(designOverallPressureRatio);

%% Supported EDB diagnostic feasibility points
pointIds = [ ...
    "normal_takeoff_edb" ...
    "climb_out_edb" ...
    "approach_edb"];

numberPoints = numel(pointIds);

exactSolutionTolerance = 5e-5;

% Bounds apply only to EDB diagnostics; APR is not optimized.
lowerBounds = [ ...
    5.0, ...       % core airflow, kg/s
    2.0, ...       % effective bypass ratio
    2.0, ...       % effective overall pressure ratio
    700.0];        % combustor exit temperature, K

upperBounds = [ ...
    aprCfg.engine.core_airflow_kg_s, ...
    8.0, ...
    designOverallPressureRatio, ...
    aprCfg.engine.combustor_exit_temperature_K];

solverOptions = optimset( ...
    'Display', 'off', ...
    'MaxFunEvals', 6000, ...
    'MaxIter', 2500, ...
    'TolFun', 1e-14, ...
    'TolX', 1e-10);

solverOptions = apply_solver_option_overrides( ...
    solverOptions, ...
    diagnosticOptions);

startTemplate = struct( ...
    'start_index', NaN, ...
    'initial_physical', nan(1, 4), ...
    'terminal_physical', nan(1, 4), ...
    'objective', NaN, ...
    'recomputed_objective', NaN, ...
    'objective_consistency_error', NaN, ...
    'exit_flag', NaN, ...
    'iterations', NaN, ...
    'function_evaluations', NaN, ...
    'solver_exit_success', false, ...
    'terminal_evaluation_valid', false, ...
    'objective_consistent', false, ...
    'selected', false, ...
    'expected_failure_count', 0, ...
    'expected_failure_identifiers', strings(0, 1), ...
    'expected_failure_messages', strings(0, 1), ...
    'expected_failure_contexts', strings(0, 1));

caseTemplate = struct( ...
    'point_id', "", ...
    'classification', "diagnostic", ...
    'feasibility_status', "", ...
    'is_exact_solution', false, ...
    'active_bounds', "none", ...
    'target_provenance', "", ...
    'target_thrust_basis', "", ...
    'solver_success', false, ...
    'selected_start_index', NaN, ...
    'start_diagnostics', repmat(startTemplate, 0, 1), ...
    'expected_domain_failure_count', 0, ...
    'unexpected_exception_count', 0, ...
    'cfg', struct(), ...
    'results', struct(), ...
    'raw_residuals', zeros(4, 1), ...
    'normalized_residuals', zeros(4, 1), ...
    'objective', NaN, ...
    'recomputed_objective', NaN, ...
    'objective_consistency_error', NaN, ...
    'exit_flag', NaN, ...
    'iterations', NaN, ...
    'function_evaluations', NaN, ...
    'jacobian', nan(4), ...
    'jacobian_singular_values', nan(4, 1), ...
    'jacobian_rank', NaN, ...
    'jacobian_condition_number', NaN);

cases = repmat(caseTemplate, numberPoints, 1);

currentPointId = "";
currentStartIndex = NaN;
currentExpectedFailureIdentifiers = strings(0, 1);
currentExpectedFailureMessages = strings(0, 1);
currentExpectedFailureContexts = strings(0, 1);

for pointIndex = 1:numberPoints
    pointCfg = apply_cf34_operating_point( ...
        aprCfg, ...
        pointIds(pointIndex));

    powerFraction = ...
        pointCfg.operating_point.target_thrust_N ...
        / aprCfg.operating_point.target_thrust_N;

    initialPhysical = initial_guess( ...
        aprCfg, ...
        designOverallPressureRatio, ...
        powerFraction, ...
        lowerBounds, ...
        upperBounds);

    physicalStarts = deterministic_starts( ...
        initialPhysical, ...
        lowerBounds, ...
        upperBounds);

    startDiagnostics = repmat( ...
        startTemplate, ...
        size(physicalStarts, 1), ...
        1);

    bestObjective = Inf;
    bestState = [];
    bestExitFlag = NaN;
    bestOutput = struct();
    bestStartIndex = NaN;

    currentPointId = pointIds(pointIndex);

    for startIndex = 1:size(physicalStarts, 1)
        currentStartIndex = startIndex;
        currentExpectedFailureIdentifiers = strings(0, 1);
        currentExpectedFailureMessages = strings(0, 1);
        currentExpectedFailureContexts = strings(0, 1);

        initialUnconstrained = to_unconstrained( ...
            physicalStarts(startIndex, :), ...
            lowerBounds, ...
            upperBounds);

        objectiveFunction = @recorded_objective;

        [candidateState, candidateObjective, candidateExitFlag, candidateOutput] = ...
            fminsearch( ...
                objectiveFunction, ...
                initialUnconstrained, ...
                solverOptions);

        candidatePhysical = from_unconstrained( ...
            candidateState, ...
            lowerBounds, ...
            upperBounds);

        [candidateRecomputedObjective, terminalFailure] = ...
            objective_value( ...
                candidateState, ...
                pointCfg, ...
                logPressureRiseFractions, ...
                lowerBounds, ...
                upperBounds);

        if terminalFailure.occurred
            record_expected_failure( ...
                terminalFailure, ...
                candidateState, ...
                "terminal evaluation");
        end

        objectiveConsistencyError = abs( ...
            candidateObjective - candidateRecomputedObjective);

        objectiveConsistencyTolerance = ...
            1e-12 * max(1, abs(candidateRecomputedObjective));

        terminalEvaluationValid = ...
            ~terminalFailure.occurred ...
            && isfinite(candidateRecomputedObjective);

        objectiveConsistent = ...
            terminalEvaluationValid ...
            && objectiveConsistencyError ...
                <= objectiveConsistencyTolerance;

        solverExitSuccess = ...
            candidateExitFlag > 0;

        candidateSucceeded = ...
            solverExitSuccess ...
            && terminalEvaluationValid ...
            && objectiveConsistent;

        startDiagnostics(startIndex).start_index = startIndex;
        startDiagnostics(startIndex).initial_physical = ...
            physicalStarts(startIndex, :);
        startDiagnostics(startIndex).terminal_physical = ...
            candidatePhysical;
        startDiagnostics(startIndex).objective = ...
            candidateObjective;
        startDiagnostics(startIndex).recomputed_objective = ...
            candidateRecomputedObjective;
        startDiagnostics(startIndex).objective_consistency_error = ...
            objectiveConsistencyError;
        startDiagnostics(startIndex).exit_flag = ...
            candidateExitFlag;
        startDiagnostics(startIndex).iterations = ...
            candidateOutput.iterations;
        startDiagnostics(startIndex).function_evaluations = ...
            candidateOutput.funcCount;
        startDiagnostics(startIndex).solver_exit_success = ...
            solverExitSuccess;
        startDiagnostics(startIndex).terminal_evaluation_valid = ...
            terminalEvaluationValid;
        startDiagnostics(startIndex).objective_consistent = ...
            objectiveConsistent;
        startDiagnostics(startIndex).expected_failure_count = ...
            numel(currentExpectedFailureIdentifiers);
        startDiagnostics(startIndex).expected_failure_identifiers = ...
            currentExpectedFailureIdentifiers;
        startDiagnostics(startIndex).expected_failure_messages = ...
            currentExpectedFailureMessages;
        startDiagnostics(startIndex).expected_failure_contexts = ...
            currentExpectedFailureContexts;

        if candidateSucceeded ...
                && candidateRecomputedObjective < bestObjective
            bestObjective = candidateRecomputedObjective;
            bestState = candidateState;
            bestExitFlag = candidateExitFlag;
            bestOutput = candidateOutput;
            bestStartIndex = startIndex;
        end
    end

    totalExpectedFailureCount = ...
        sum([startDiagnostics.expected_failure_count]);

    if isnan(bestStartIndex)
        cases(pointIndex).point_id = pointIds(pointIndex);
        cases(pointIndex).classification = "diagnostic";
        cases(pointIndex).feasibility_status = ...
            "solver_failure_no_successful_start";
        cases(pointIndex).solver_success = false;
        cases(pointIndex).start_diagnostics = startDiagnostics;
        cases(pointIndex).expected_domain_failure_count = ...
            totalExpectedFailureCount;
        cases(pointIndex).target_provenance = ...
            pointCfg.operating_point.source;
        cases(pointIndex).target_thrust_basis = ...
            pointCfg.operating_point.target_thrust_basis;
        cases(pointIndex).cfg = pointCfg;
        continue
    end

    startDiagnostics(bestStartIndex).selected = true;

    bestPhysical = from_unconstrained( ...
        bestState, ...
        lowerBounds, ...
        upperBounds);

    [normalizedResiduals, rawResiduals, matchedCfg, matchedResults] = ...
        evaluate_match( ...
            bestPhysical, ...
            pointCfg, ...
            logPressureRiseFractions);

    recomputedObjective = ...
        sum(normalizedResiduals .^ 2);

    objectiveConsistencyError = ...
        abs(bestObjective - recomputedObjective);

    objectiveConsistencyTolerance = ...
        1e-12 * max(1, abs(recomputedObjective));

    if objectiveConsistencyError > objectiveConsistencyTolerance
        error( ...
            "CF34Matcher:SelectedObjectiveMismatch", ...
            "Selected objective is inconsistent with its normalized residuals.");
    end

    [jacobian, singularValues, jacobianRank, conditionNumber] = ...
        residual_jacobian( ...
            bestPhysical, ...
            pointCfg, ...
            logPressureRiseFractions, ...
            lowerBounds, ...
            upperBounds);

    activeBounds = active_bound_labels( ...
        bestPhysical, ...
        lowerBounds, ...
        upperBounds);

    isExactSolution = ...
        max(abs(normalizedResiduals)) <= exactSolutionTolerance;

    if isExactSolution
        feasibilityStatus = "exact_solution_found_within_bounds";
    else
        feasibilityStatus = "no_exact_solution_found_within_bounds";
    end

    cases(pointIndex).point_id = pointIds(pointIndex);
    cases(pointIndex).classification = "diagnostic";
    cases(pointIndex).feasibility_status = feasibilityStatus;
    cases(pointIndex).is_exact_solution = isExactSolution;
    cases(pointIndex).active_bounds = activeBounds;
    cases(pointIndex).target_provenance = pointCfg.operating_point.source;
    cases(pointIndex).target_thrust_basis = ...
        pointCfg.operating_point.target_thrust_basis;
    cases(pointIndex).solver_success = true;
    cases(pointIndex).selected_start_index = bestStartIndex;
    cases(pointIndex).start_diagnostics = startDiagnostics;
    cases(pointIndex).expected_domain_failure_count = ...
        totalExpectedFailureCount;
    cases(pointIndex).cfg = matchedCfg;
    cases(pointIndex).results = matchedResults;
    cases(pointIndex).raw_residuals = rawResiduals;
    cases(pointIndex).normalized_residuals = normalizedResiduals;
    cases(pointIndex).objective = bestObjective;
    cases(pointIndex).recomputed_objective = recomputedObjective;
    cases(pointIndex).objective_consistency_error = ...
        objectiveConsistencyError;
    cases(pointIndex).exit_flag = bestExitFlag;
    cases(pointIndex).iterations = bestOutput.iterations;
    cases(pointIndex).function_evaluations = bestOutput.funcCount;
    cases(pointIndex).jacobian = jacobian;
    cases(pointIndex).jacobian_singular_values = singularValues;
    cases(pointIndex).jacobian_rank = jacobianRank;
    cases(pointIndex).jacobian_condition_number = conditionNumber;
end

%% Assemble effective schedule and diagnostics
powerSetting_percentFoo = nan(numberPoints, 1);
coreAirflow_kg_s = nan(numberPoints, 1);
effectiveBypassRatio = nan(numberPoints, 1);
fanPressureRatio = nan(numberPoints, 1);
lpcPressureRatio = nan(numberPoints, 1);
hpcPressureRatio = nan(numberPoints, 1);
effectiveOverallPressureRatio = nan(numberPoints, 1);
combustorExitTemperature_K = nan(numberPoints, 1);
thrustResidual_N = nan(numberPoints, 1);
fuelFlowResidual_kg_s = nan(numberPoints, 1);
coreNozzleCapacityResidual_kg_s = nan(numberPoints, 1);
bypassNozzleCapacityResidual_kg_s = nan(numberPoints, 1);
maximumNormalizedResidual = nan(numberPoints, 1);
jacobianConditionNumber = nan(numberPoints, 1);
solverSuccess = false(numberPoints, 1);
selectedExitFlag = nan(numberPoints, 1);
selectedStartIndex = nan(numberPoints, 1);
objective = nan(numberPoints, 1);
objectiveConsistencyError = nan(numberPoints, 1);
expectedDomainFailureCount = zeros(numberPoints, 1);
classification = repmat("diagnostic", numberPoints, 1);
feasibilityStatus = strings(numberPoints, 1);
activeBounds = strings(numberPoints, 1);
targetProvenance = strings(numberPoints, 1);
targetThrustBasis = strings(numberPoints, 1);

for pointIndex = 1:numberPoints
    pointCfg = cases(pointIndex).cfg;

    powerSetting_percentFoo(pointIndex) = ...
        pointCfg.operating_point.power_setting_percent_Foo;

    if cases(pointIndex).solver_success
        coreAirflow_kg_s(pointIndex) = ...
            pointCfg.engine.core_airflow_kg_s;

        effectiveBypassRatio(pointIndex) = ...
            pointCfg.engine.bypass_ratio;

        fanPressureRatio(pointIndex) = ...
            pointCfg.engine.fan_pressure_ratio;

        lpcPressureRatio(pointIndex) = ...
            pointCfg.engine.lpc_pressure_ratio;

        hpcPressureRatio(pointIndex) = ...
            pointCfg.engine.hpc_pressure_ratio;

        effectiveOverallPressureRatio(pointIndex) = ...
            fanPressureRatio(pointIndex) ...
            * lpcPressureRatio(pointIndex) ...
            * hpcPressureRatio(pointIndex);

        combustorExitTemperature_K(pointIndex) = ...
            pointCfg.engine.combustor_exit_temperature_K;

        thrustResidual_N(pointIndex) = ...
            cases(pointIndex).raw_residuals(1);

        fuelFlowResidual_kg_s(pointIndex) = ...
            cases(pointIndex).raw_residuals(2);

        coreNozzleCapacityResidual_kg_s(pointIndex) = ...
            cases(pointIndex).raw_residuals(3);

        bypassNozzleCapacityResidual_kg_s(pointIndex) = ...
            cases(pointIndex).raw_residuals(4);

        maximumNormalizedResidual(pointIndex) = ...
            max(abs(cases(pointIndex).normalized_residuals));

        jacobianConditionNumber(pointIndex) = ...
            cases(pointIndex).jacobian_condition_number;
    end

    solverSuccess(pointIndex) = ...
        cases(pointIndex).solver_success;

    selectedExitFlag(pointIndex) = ...
        cases(pointIndex).exit_flag;

    selectedStartIndex(pointIndex) = ...
        cases(pointIndex).selected_start_index;

    objective(pointIndex) = ...
        cases(pointIndex).objective;

    objectiveConsistencyError(pointIndex) = ...
        cases(pointIndex).objective_consistency_error;

    expectedDomainFailureCount(pointIndex) = ...
        cases(pointIndex).expected_domain_failure_count;

    feasibilityStatus(pointIndex) = ...
        cases(pointIndex).feasibility_status;

    activeBounds(pointIndex) = ...
        cases(pointIndex).active_bounds;

    targetProvenance(pointIndex) = ...
        cases(pointIndex).target_provenance;

    targetThrustBasis(pointIndex) = ...
        cases(pointIndex).target_thrust_basis;
end

schedule = table( ...
    pointIds', ...
    powerSetting_percentFoo, ...
    coreAirflow_kg_s, ...
    effectiveBypassRatio, ...
    fanPressureRatio, ...
    lpcPressureRatio, ...
    hpcPressureRatio, ...
    effectiveOverallPressureRatio, ...
    combustorExitTemperature_K, ...
    thrustResidual_N, ...
    fuelFlowResidual_kg_s, ...
    coreNozzleCapacityResidual_kg_s, ...
    bypassNozzleCapacityResidual_kg_s, ...
    maximumNormalizedResidual, ...
    jacobianConditionNumber, ...
    solverSuccess, ...
    selectedExitFlag, ...
    selectedStartIndex, ...
    objective, ...
    objectiveConsistencyError, ...
    expectedDomainFailureCount, ...
    classification, ...
    feasibilityStatus, ...
    activeBounds, ...
    targetProvenance, ...
    targetThrustBasis, ...
    'VariableNames', { ...
        'PointId', ...
        'PowerSetting_percentFoo', ...
        'CoreAirflow_kg_s', ...
        'EffectiveBypassRatio', ...
        'FanPressureRatio', ...
        'LPCPressureRatio', ...
        'HPCPressureRatio', ...
        'EffectiveOverallPressureRatio', ...
        'CombustorExitTemperature_K', ...
        'ThrustResidual_N', ...
        'FuelFlowResidual_kg_s', ...
        'CoreNozzleCapacityResidual_kg_s', ...
        'BypassNozzleCapacityResidual_kg_s', ...
        'MaximumNormalizedResidual', ...
        'JacobianConditionNumber', ...
        'SolverSuccess', ...
        'SelectedExitFlag', ...
        'SelectedStartIndex', ...
        'Objective', ...
        'ObjectiveConsistencyError', ...
        'ExpectedDomainFailureCount', ...
        'Classification', ...
        'FeasibilityStatus', ...
        'ActiveBounds', ...
        'TargetProvenance', ...
        'TargetThrustBasis'});

match = struct();
match.method = ...
    "reduced-order, steady-state, fixed-nozzle-area multipoint matcher";
match.scope = ...
    "Three diagnostic EDB feasibility targets; APR preserved; idle, maximum-continuous, and cruise remain holdouts";
match.classification = ...
    "diagnostic_feasibility_study";
match.is_accepted_off_design_model = false;
match.exact_solution_tolerance = exactSolutionTolerance;
match.effective_quantity_names = [ ...
    "CoreAirflow_kg_s" ...
    "EffectiveBypassRatio" ...
    "EffectiveOverallPressureRatio" ...
    "CombustorExitTemperature_K"];
match.residual_names = [ ...
    "Thrust_N" ...
    "FuelFlow_kg_s" ...
    "CoreNozzleCapacity_kg_s" ...
    "BypassNozzleCapacity_kg_s"];
match.lower_bounds = lowerBounds;
match.upper_bounds = upperBounds;
match.solver_options = solverOptions;
match.deterministic_start_count = size(physicalStarts, 1);
match.solver_failure_status = ...
    "solver_failure_no_successful_start";
match.log_pressure_rise_fractions = logPressureRiseFractions;
match.apr.cfg = aprCfg;
match.apr.results = aprResults;
match.cases = cases;
match.schedule = schedule;
match.limitations = [ ...
    "No EDB point is an accepted calibrated operating point or validated prediction."
    "Failure to find an exact solution with this bounded multistart local diagnostic is not a global proof that no exact root exists."
    "Public APR BPR/OPR values and UID 10GE133 EDB values have mixed pedigree and are not proven to describe identical internal engine states."
    "Climb-out and approach thrust targets are derived from percent Foo rather than independent net-thrust measurements at the modeled ambient midpoint."
    "The effective bypass ratio is a modeled mass-flow ratio, not a geometry change."
    "No compressor maps, turbine maps, spool-speed matching, or proprietary control schedule are represented."];


    function recordedObjective = recorded_objective(unconstrained)
    %RECORDED_OBJECTIVE Evaluate and retain expected domain failures.

        [recordedObjective, failure] = objective_value( ...
            unconstrained, ...
            pointCfg, ...
            logPressureRiseFractions, ...
            lowerBounds, ...
            upperBounds);

        if failure.occurred
            record_expected_failure( ...
                failure, ...
                unconstrained, ...
                "solver objective evaluation");
        end
    end


    function record_expected_failure(failure, unconstrained, phase)
    %RECORD_EXPECTED_FAILURE Retain source and state for diagnosis.

        physical = from_unconstrained( ...
            unconstrained, ...
            lowerBounds, ...
            upperBounds);

        context = sprintf( ...
            "point=%s; start=%d; phase=%s; physical=%s", ...
            currentPointId, ...
            currentStartIndex, ...
            phase, ...
            mat2str(physical, 10));

        currentExpectedFailureIdentifiers(end + 1, 1) = ...
            failure.identifier;
        currentExpectedFailureMessages(end + 1, 1) = ...
            failure.message;
        currentExpectedFailureContexts(end + 1, 1) = ...
            context;
    end

end


function label = active_bound_labels(physical, lowerBounds, upperBounds)
%ACTIVE_BOUND_LABELS Report bounds active at a constrained diagnostic result.

variableNames = [ ...
    "core_airflow" ...
    "effective_bypass_ratio" ...
    "effective_overall_pressure_ratio" ...
    "combustor_exit_temperature"];

activeLabels = strings(0, 1);
boundTolerance = 1e-8 * (upperBounds - lowerBounds);

for variableIndex = 1:numel(physical)
    if physical(variableIndex) - lowerBounds(variableIndex) ...
            <= boundTolerance(variableIndex)
        activeLabels(end + 1, 1) = ...
            variableNames(variableIndex) + "_lower";
    end

    if upperBounds(variableIndex) - physical(variableIndex) ...
            <= boundTolerance(variableIndex)
        activeLabels(end + 1, 1) = ...
            variableNames(variableIndex) + "_upper";
    end
end

if isempty(activeLabels)
    label = "none";
else
    label = strjoin(activeLabels, ", ");
end

end


function physical = initial_guess( ...
    cfgApr, ...
    designOverallPressureRatio, ...
    powerFraction, ...
    lowerBounds, ...
    upperBounds)
%INITIAL_GUESS Build one deterministic physics-scaled starting point.

coreAirflow = ...
    cfgApr.engine.core_airflow_kg_s ...
    * (0.12 + 0.88 * powerFraction);

effectiveBypassRatio = ...
    cfgApr.engine.bypass_ratio;

effectiveOverallPressureRatio = ...
    1 + (designOverallPressureRatio - 1) ...
    * powerFraction^0.70;

combustorExitTemperature = ...
    550 + (cfgApr.engine.combustor_exit_temperature_K - 550) ...
    * powerFraction^0.30;

physical = [ ...
    coreAirflow, ...
    effectiveBypassRatio, ...
    effectiveOverallPressureRatio, ...
    combustorExitTemperature];

physical = clip_inside_bounds( ...
    physical, ...
    lowerBounds, ...
    upperBounds);

end


function starts = deterministic_starts(initial, lowerBounds, upperBounds)
%DETERMINISTIC_STARTS Provide repeatable alternatives for the local solver.

relativeOffsets = [ ...
     0.00,  0.00,  0.00,  0.00
    -0.12,  0.08, -0.12, -0.08
     0.12, -0.08,  0.12,  0.08
    -0.08, -0.08,  0.10, -0.12
     0.08,  0.08, -0.10,  0.12];

range = upperBounds - lowerBounds;
starts = initial + relativeOffsets .* range;

for startIndex = 1:size(starts, 1)
    starts(startIndex, :) = clip_inside_bounds( ...
        starts(startIndex, :), ...
        lowerBounds, ...
        upperBounds);
end

end


function clipped = clip_inside_bounds(values, lowerBounds, upperBounds)
%CLIP_INSIDE_BOUNDS Keep starts away from asymptotic transformed bounds.

margin = 1e-5 * (upperBounds - lowerBounds);
clipped = min(max(values, lowerBounds + margin), upperBounds - margin);

end


function unconstrained = to_unconstrained(physical, lowerBounds, upperBounds)
%TO_UNCONSTRAINED Apply a bounded logistic coordinate transform.

fraction = ...
    (physical - lowerBounds) ...
    ./ (upperBounds - lowerBounds);

fraction = min(max(fraction, 1e-10), 1 - 1e-10);
unconstrained = log(fraction ./ (1 - fraction));

end


function physical = from_unconstrained(unconstrained, lowerBounds, upperBounds)
%FROM_UNCONSTRAINED Recover bounded effective operating quantities.

fraction = 1 ./ (1 + exp(-unconstrained));
physical = lowerBounds + fraction .* (upperBounds - lowerBounds);

end


function [objective, failure] = objective_value( ...
    unconstrained, ...
    pointCfg, ...
    logPressureRiseFractions, ...
    lowerBounds, ...
    upperBounds)
%OBJECTIVE_VALUE Return the squared normalized four-residual norm.

failure = struct( ...
    'occurred', false, ...
    'identifier', "", ...
    'message', "");

physical = from_unconstrained( ...
    unconstrained, ...
    lowerBounds, ...
    upperBounds);

try
    normalizedResiduals = evaluate_match( ...
        physical, ...
        pointCfg, ...
        logPressureRiseFractions);

    if any(~isfinite(normalizedResiduals))
        failure.occurred = true;
        failure.identifier = ...
            "CF34Matcher:NonfiniteModelDomainEvaluation";
        failure.message = ...
            "Cycle evaluator returned a nonfinite normalized residual.";
        objective = domain_failure_penalty(unconstrained);
    else
        objective = sum(normalizedResiduals .^ 2);
    end
catch exception
    if ~is_expected_model_domain_error(exception)
        rethrow(exception)
    end

    failure.occurred = true;
    failure.identifier = string(exception.identifier);

    if strlength(failure.identifier) == 0
        failure.identifier = ...
            "CF34Matcher:ExpectedModelDomainFailure";
    end

    failure.message = string(exception.message);
    objective = domain_failure_penalty(unconstrained);
end

end


function penalty = domain_failure_penalty(unconstrained)
%DOMAIN_FAILURE_PENALTY Keep expected inadmissible states out of the fit.

boundedCoordinate = min(abs(unconstrained), 1e6);
penalty = 1e12 + sum(boundedCoordinate .^ 2);

end


function expected = is_expected_model_domain_error(exception)
%IS_EXPECTED_MODEL_DOMAIN_ERROR Whitelist physical-domain evaluation errors.

expectedMessages = [ ...
    "Invalid combustor energy balance: denominator is nonpositive."
    "Calculated fuel-air ratio is nonpositive."
    "Coolant supply total pressure must exceed the hot-gas total pressure."
    "Cooling-mixer pressure loss is nonphysical."
    "Turbine power demand produces a nonphysical outlet temperature."
    "Turbine expansion produces a nonphysical isentropic temperature."
    "Nozzle total pressure must exceed ambient pressure."
    "Available nozzle total pressure must exceed ambient pressure."
    "Calculated net thrust is nonpositive."
    "Calculated jet kinetic-power increase is nonpositive."
    "Calculated fuel chemical power is nonpositive."
    "HPT outlet temperature must be below its inlet temperature."
    "Calculated HPT rotor-inlet static temperature is nonphysical."
    "Calculated HPT rotor-exit static temperature is nonphysical."
    "Calculated HPT hub radius is nonphysical."];

expected = ...
    any(string(exception.message) == expectedMessages);

end


function solverOptions = apply_solver_option_overrides( ...
    solverOptions, ...
    diagnosticOptions)
%APPLY_SOLVER_OPTION_OVERRIDES Limit diagnostic solver budgets when requested.

allowedFields = [ ...
    "solver_max_iterations"
    "solver_max_function_evaluations"];

requestedFields = string(fieldnames(diagnosticOptions));

unexpectedFields = setdiff(requestedFields, allowedFields);

if ~isempty(unexpectedFields)
    error( ...
        "CF34Matcher:UnknownDiagnosticOption", ...
        "Unknown diagnostic option: %s", ...
        unexpectedFields(1));
end

if isfield(diagnosticOptions, "solver_max_iterations")
    validateattributes( ...
        diagnosticOptions.solver_max_iterations, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'integer', 'nonnegative'});

    solverOptions.MaxIter = ...
        diagnosticOptions.solver_max_iterations;
end

if isfield(diagnosticOptions, "solver_max_function_evaluations")
    validateattributes( ...
        diagnosticOptions.solver_max_function_evaluations, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'integer', 'positive'});

    solverOptions.MaxFunEvals = ...
        diagnosticOptions.solver_max_function_evaluations;
end

end


function [normalizedResiduals, rawResiduals, cfg, results] = ...
    evaluate_match(physical, pointCfg, logPressureRiseFractions)
%EVALUATE_MATCH Run one bounded effective operating state.

coreAirflow_kg_s = physical(1);
effectiveBypassRatio = physical(2);
effectiveOverallPressureRatio = physical(3);
combustorExitTemperature_K = physical(4);

componentPressureRatios = ...
    exp(logPressureRiseFractions * log(effectiveOverallPressureRatio));

cfg = pointCfg;
cfg.engine.core_airflow_kg_s = coreAirflow_kg_s;
cfg.engine.bypass_ratio = effectiveBypassRatio;
cfg.engine.target_overall_pressure_ratio = ...
    effectiveOverallPressureRatio;
cfg.engine.fan_pressure_ratio = componentPressureRatios(1);
cfg.engine.lpc_pressure_ratio = componentPressureRatios(2);
cfg.engine.hpc_pressure_ratio = componentPressureRatios(3);
cfg.engine.combustor_exit_temperature_K = ...
    combustorExitTemperature_K;
cfg.engine.turbine_inlet_temperature_K = ...
    combustorExitTemperature_K;

results = run_turbofan(cfg);

rawResiduals = [ ...
    results.performance.net_thrust_N ...
        - cfg.operating_point.target_thrust_N
    results.mass.mdot_fuel_kg_s ...
        - cfg.operating_point.target_fuel_flow_kg_s
    results.residuals.core_nozzle_capacity_kg_s
    results.residuals.bypass_nozzle_capacity_kg_s];

normalization = [ ...
    cfg.operating_point.target_thrust_N
    cfg.operating_point.target_fuel_flow_kg_s
    results.mass.mdot_hpt_kg_s
    results.mass.mdot_bypass_air_kg_s];

normalizedResiduals = rawResiduals ./ normalization;

end


function [jacobian, singularValues, jacobianRank, conditionNumber] = ...
    residual_jacobian( ...
        physical, ...
        pointCfg, ...
        logPressureRiseFractions, ...
        lowerBounds, ...
        upperBounds)
%RESIDUAL_JACOBIAN Diagnose local identifiability in scaled coordinates.

normalizedPhysical = ...
    (physical - lowerBounds) ...
    ./ (upperBounds - lowerBounds);

step = 1e-4;
jacobian = zeros(4);

for variableIndex = 1:4
    lowerCoordinate = normalizedPhysical;
    upperCoordinate = normalizedPhysical;

    lowerCoordinate(variableIndex) = max( ...
        1e-8, ...
        normalizedPhysical(variableIndex) - step);

    upperCoordinate(variableIndex) = min( ...
        1 - 1e-8, ...
        normalizedPhysical(variableIndex) + step);

    lowerPhysical = ...
        lowerBounds ...
        + lowerCoordinate .* (upperBounds - lowerBounds);

    upperPhysical = ...
        lowerBounds ...
        + upperCoordinate .* (upperBounds - lowerBounds);

    lowerResidual = evaluate_match( ...
        lowerPhysical, ...
        pointCfg, ...
        logPressureRiseFractions);

    upperResidual = evaluate_match( ...
        upperPhysical, ...
        pointCfg, ...
        logPressureRiseFractions);

    coordinateDifference = ...
        upperCoordinate(variableIndex) ...
        - lowerCoordinate(variableIndex);

    jacobian(:, variableIndex) = ...
        (upperResidual - lowerResidual) ...
        / coordinateDifference;
end

singularValues = svd(jacobian);
jacobianRank = rank(jacobian);

if singularValues(end) <= eps(singularValues(1))
    conditionNumber = Inf;
else
    conditionNumber = singularValues(1) / singularValues(end);
end

end
