function outlet = nozzle_fixed_area_capacity( ...
    inlet, ...
    ambientPressure_Pa, ...
    area_m2, ...
    pressureRecovery, ...
    gamma, ...
    R)
%NOZZLE_FIXED_AREA_CAPACITY Evaluate flow supported by fixed nozzle area.
%
% This function uses the same ideal convergent-nozzle assumptions as
% nozzle.m, but treats physical area as an input and mass flow as an output.
%
% It is currently a diagnostic building block for off-design matching:
%
%   - If the nozzle is choked, mass flow is the sonic capacity.
%   - If it is unchoked, exit pressure is ambient and mass flow follows
%     from the resulting exit state and the fixed area.
%
% The existing cycle model still prescribes stream mass flow. A future
% off-design solver will drive the difference between demanded mass flow
% and this fixed-area capacity toward zero.

validateattributes(ambientPressure_Pa, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

validateattributes(area_m2, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

validateattributes(pressureRecovery, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', 0, '<=', 1});

validateattributes(gamma, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', 1});

validateattributes(R, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

%% Available nozzle total conditions
TtAvailable_K = ...
    inlet.Tt_K;

PtAvailable_Pa = ...
    pressureRecovery * inlet.Pt_Pa;

if PtAvailable_Pa <= ambientPressure_Pa
    error( ...
        "Available nozzle total pressure must exceed ambient pressure.");
end

%% Determine choking state
criticalNozzlePressureRatio = ...
    ((gamma + 1) / 2)^(gamma / (gamma - 1));

nozzlePressureRatio = ...
    PtAvailable_Pa / ambientPressure_Pa;

isChoked = ...
    nozzlePressureRatio >= criticalNozzlePressureRatio;

%% Exit state
if isChoked
    exitMach = 1.0;

    exitPressure_Pa = ...
        PtAvailable_Pa ...
        / criticalNozzlePressureRatio;
else
    exitPressure_Pa = ...
        ambientPressure_Pa;

    exitMach = sqrt( ...
        (2 / (gamma - 1)) ...
        * ( ...
            nozzlePressureRatio^((gamma - 1) / gamma) ...
            - 1));
end

exitTemperature_K = ...
    TtAvailable_K ...
    / (1 + ((gamma - 1) / 2) * exitMach^2);

exitSpeedOfSound_m_s = ...
    sqrt(gamma * R * exitTemperature_K);

exitVelocity_m_s = ...
    exitMach * exitSpeedOfSound_m_s;

exitDensity_kg_m3 = ...
    exitPressure_Pa ...
    / (R * exitTemperature_K);

massFlowCapacity_kg_s = ...
    exitDensity_kg_m3 ...
    * exitVelocity_m_s ...
    * area_m2;

pressureThrust_N = ...
    (exitPressure_Pa - ambientPressure_Pa) ...
    * area_m2;

%% Package outputs
outlet.Tt_K = ...
    TtAvailable_K;

outlet.Pt_Pa = ...
    PtAvailable_Pa;

outlet.T_K = ...
    exitTemperature_K;

outlet.P_Pa = ...
    exitPressure_Pa;

outlet.Mach = ...
    exitMach;

outlet.velocity_m_s = ...
    exitVelocity_m_s;

outlet.density_kg_m3 = ...
    exitDensity_kg_m3;

outlet.area_m2 = ...
    area_m2;

outlet.mass_flow_capacity_kg_s = ...
    massFlowCapacity_kg_s;

outlet.pressure_thrust_N = ...
    pressureThrust_N;

outlet.nozzle_pressure_ratio = ...
    nozzlePressureRatio;

outlet.critical_nozzle_pressure_ratio = ...
    criticalNozzlePressureRatio;

outlet.pressure_recovery = ...
    pressureRecovery;

outlet.is_choked = ...
    isChoked;

end
