function results = run_turbofan(cfg)
%RUN_TURBOFAN Execute the complete separate-flow turbofan cycle model.
%
% Input:
%   cfg      Engine configuration structure from baseline_engine.m
%
% Output:
%   results  Structure containing stations, mass flows, power,
%            thrust performance, cooling data, and balance residuals

[cfg, combustorExitTemperature_K] = ...
    resolve_combustor_exit_temperature(cfg);

reject_unsupported_external_loads(cfg);

%% Atmosphere and freestream
atm = atmosphere( ...
    cfg.flight.altitude_m, ...
    cfg.flight.ambient_temperature_override_K, ...
    cfg.flight.ambient_pressure_override_Pa);

%% Mass-flow accounting
mdotCore = cfg.engine.core_airflow_kg_s;
mdotBypass = cfg.engine.bypass_ratio * mdotCore;
mdotTotal = mdotCore + mdotBypass;

%% Freestream and diffuser: 0 -> 2
[station0, station2] = diffuser( ...
    atm, ...
    cfg.flight.Mach, ...
    cfg.eff.diffuser_pressure_recovery);

%% Fan: 2 -> 21 and 13
fanExit = compressor( ...
    station2, ...
    cfg.engine.fan_pressure_ratio, ...
    cfg.eff.fan_isentropic, ...
    cfg.thermo.cp_cold_J_kgK, ...
    cfg.thermo.gamma_cold);

station21 = fanExit;
station13 = fanExit;

%% LPC: 21 -> 25
station25 = compressor( ...
    station21, ...
    cfg.engine.lpc_pressure_ratio, ...
    cfg.eff.lpc_isentropic, ...
    cfg.thermo.cp_cold_J_kgK, ...
    cfg.thermo.gamma_cold);

%% HPC: 25 -> 3
station3 = compressor( ...
    station25, ...
    cfg.engine.hpc_pressure_ratio, ...
    cfg.eff.hpc_isentropic, ...
    cfg.thermo.cp_cold_J_kgK, ...
    cfg.thermo.gamma_cold);

%% Compression powers
fanPower_W = ...
    mdotTotal * fanExit.specific_work_J_kg;

lpcPower_W = ...
    mdotCore * station25.specific_work_J_kg;

hpcPower_W = ...
    mdotCore * station3.specific_work_J_kg;

%% Cooling-flow split after HPC
coolingFraction = cfg.cooling.bleed_fraction;

validateattributes(coolingFraction, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0, '<', 1});

mdotCoolingAir = coolingFraction * mdotCore;
mdotCombustorAir = mdotCore - mdotCoolingAir;

%% Combustor: 3 -> 4
station4 = combustor( ...
    station3, ...
    mdotCombustorAir, ...
    combustorExitTemperature_K, ...
    cfg.loss.combustor_pressure_ratio, ...
    cfg.eff.combustor, ...
    cfg.fuel.lower_heating_value_J_kg, ...
    cfg.thermo.cp_cold_J_kgK, ...
    cfg.thermo.cp_hot_J_kgK);

%% Cooling-air mixing: 4 + HPC bleed -> 41
station41 = cooling_mixer( ...
    station4, ...
    station4.mdot_gas_kg_s, ...
    station3, ...
    mdotCoolingAir, ...
    coolingFraction, ...
    cfg.loss.cooling_mixer_loss_coefficient, ...
    cfg.thermo.cp_hot_J_kgK, ...
    cfg.thermo.cp_cold_J_kgK);

mdotHPT = station41.mdot_mixed_kg_s;

%% HPT: 41 -> 45
hptRequiredPower_W = hpcPower_W;

station45 = turbine( ...
    station41, ...
    mdotHPT, ...
    hptRequiredPower_W, ...
    cfg.eff.hpt_isentropic, ...
    cfg.mech.hpt, ...
    cfg.thermo.cp_hot_J_kgK, ...
    cfg.thermo.gamma_hot);

%% Preliminary HPT mean-line sizing
hptSizing = hpt_stage_sizing( ...
    station41, ...
    station45, ...
    mdotHPT, ...
    cfg.shaft.high_spool_rpm, ...
    cfg.thermo.cp_hot_J_kgK, ...
    cfg.thermo.gamma_hot, ...
    cfg.thermo.R_J_kgK, ...
    cfg.hpt.stage_count, ...
    cfg.hpt.loading_coefficient, ...
    cfg.hpt.flow_coefficient, ...
    cfg.hpt.reaction);

%% LPT: 45 -> 5
lptRequiredPower_W = fanPower_W + lpcPower_W;

station5 = turbine( ...
    station45, ...
    mdotHPT, ...
    lptRequiredPower_W, ...
    cfg.eff.lpt_isentropic, ...
    cfg.mech.lpt, ...
    cfg.thermo.cp_hot_J_kgK, ...
    cfg.thermo.gamma_hot);

%% Core exhaust duct: 5 -> 8
station8 = station5;
station8.Pt_Pa = ...
    cfg.loss.core_duct_pressure_ratio * station5.Pt_Pa;

%% Bypass exhaust duct: 13 -> 18
station18 = station13;
station18.Pt_Pa = ...
    cfg.loss.bypass_duct_pressure_ratio * station13.Pt_Pa;

%% Core nozzle: 8 -> 9
station9 = nozzle( ...
    station8, ...
    mdotHPT, ...
    atm.pressure_Pa, ...
    cfg.loss.core_nozzle_pressure_recovery, ...
    cfg.thermo.gamma_hot, ...
    cfg.thermo.R_J_kgK);

%% Bypass nozzle: 18 -> 19
station19 = nozzle( ...
    station18, ...
    mdotBypass, ...
    atm.pressure_Pa, ...
    cfg.loss.bypass_nozzle_pressure_recovery, ...
    cfg.thermo.gamma_cold, ...
    cfg.thermo.R_J_kgK);

%% Fixed-area nozzle capacity diagnostics
% The cycle still prescribes stream mass flow. These diagnostics calculate
% the flow supported by the captured physical nozzle areas and expose the
% residuals required by the future off-design matching solver.

coreNozzleCapacity = nozzle_fixed_area_capacity( ...
    station8, ...
    atm.pressure_Pa, ...
    cfg.geometry.core_nozzle_area_m2, ...
    cfg.loss.core_nozzle_pressure_recovery, ...
    cfg.thermo.gamma_hot, ...
    cfg.thermo.R_J_kgK);

bypassNozzleCapacity = nozzle_fixed_area_capacity( ...
    station18, ...
    atm.pressure_Pa, ...
    cfg.geometry.bypass_nozzle_area_m2, ...
    cfg.loss.bypass_nozzle_pressure_recovery, ...
    cfg.thermo.gamma_cold, ...
    cfg.thermo.R_J_kgK);

coreNozzleCapacityResidual_kg_s = ...
    mdotHPT ...
    - coreNozzleCapacity.mass_flow_capacity_kg_s;

bypassNozzleCapacityResidual_kg_s = ...
    mdotBypass ...
    - bypassNozzleCapacity.mass_flow_capacity_kg_s;

%% Net thrust and TSFC
enginePerformance = thrust( ...
    station9, ...
    station19, ...
    mdotHPT, ...
    mdotBypass, ...
    mdotTotal, ...
    station0.velocity_m_s, ...
    station4.mdot_fuel_kg_s);

%% Balance residuals
highSpoolResidual_W = ...
    station45.shaft_power_W - hpcPower_W;

lowSpoolResidual_W = ...
    station5.shaft_power_W - ...
    (fanPower_W + lpcPower_W);

massResidual_kg_s = ...
    mdotTotal + station4.mdot_fuel_kg_s ...
    - mdotHPT - mdotBypass;

%% Package results
results.cfg = cfg;
results.atm = atm;

results.operating_point = ...
    cfg.operating_point;

results.mass.mdot_core_air_kg_s = mdotCore;
results.mass.mdot_bypass_air_kg_s = mdotBypass;
results.mass.mdot_total_air_kg_s = mdotTotal;
results.mass.mdot_cooling_air_kg_s = mdotCoolingAir;
results.mass.mdot_combustor_air_kg_s = mdotCombustorAir;
results.mass.mdot_fuel_kg_s = station4.mdot_fuel_kg_s;
results.mass.mdot_hpt_kg_s = mdotHPT;

results.stations.station0 = station0;
results.stations.station2 = station2;
results.stations.station21 = station21;
results.stations.station13 = station13;
results.stations.station25 = station25;
results.stations.station3 = station3;
results.stations.station4 = station4;
results.stations.station41 = station41;
results.stations.station45 = station45;
results.stations.station5 = station5;
results.stations.station8 = station8;
results.stations.station9 = station9;
results.stations.station18 = station18;
results.stations.station19 = station19;

results.power.fan_W = fanPower_W;
results.power.lpc_W = lpcPower_W;
results.power.hpc_W = hpcPower_W;
results.power.hpt_W = station45.shaft_power_W;
results.power.lpt_W = station5.shaft_power_W;
results.power.total_compression_W = ...
    fanPower_W + lpcPower_W + hpcPower_W;

results.cooling.bleed_fraction = ...
    coolingFraction;

results.cooling.mdot_coolant_kg_s = ...
    mdotCoolingAir;

results.cooling.mixer_loss_coefficient = ...
    station41.loss_coefficient;

results.cooling.mixer_pressure_loss_fraction = ...
    station41.pressure_loss_fraction;

results.cooling.mixer_pressure_recovery = ...
    station41.pressure_recovery;

results.cooling.mixer_energy_residual_W = ...
    station41.energy_residual_W;

results.performance = enginePerformance;

results.residuals.high_spool_W = highSpoolResidual_W;
results.residuals.low_spool_W = lowSpoolResidual_W;
results.residuals.mass_kg_s = massResidual_kg_s;

results.hpt_sizing = hptSizing;

results.nozzle_capacity.core = ...
    coreNozzleCapacity;

results.nozzle_capacity.bypass = ...
    bypassNozzleCapacity;

results.residuals.core_nozzle_capacity_kg_s = ...
    coreNozzleCapacityResidual_kg_s;

results.residuals.bypass_nozzle_capacity_kg_s = ...
    bypassNozzleCapacityResidual_kg_s;

%% Preliminary engine efficiencies
engineEfficiencies = calculate_efficiencies( ...
    station9, ...
    station19, ...
    mdotHPT, ...
    mdotBypass, ...
    mdotTotal, ...
    station0.velocity_m_s, ...
    station4.mdot_fuel_kg_s, ...
    cfg.fuel.lower_heating_value_J_kg, ...
    enginePerformance.net_thrust_N);

results.efficiency = engineEfficiencies;

end


function reject_unsupported_external_loads(cfg)
%REJECT_UNSUPPORTED_EXTERNAL_LOADS Fail before silently ignoring loads.

if ~isfield(cfg, "external_loads")
    return
end

if isfield(cfg.external_loads, "external_bleed_fraction")
    externalBleedFraction = ...
        cfg.external_loads.external_bleed_fraction;

    validateattributes( ...
        externalBleedFraction, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'nonnegative'});

    if externalBleedFraction ~= 0
        error( ...
            "TurbofanConfig:UnsupportedExternalBleed", ...
            "Nonzero external bleed is not implemented by run_turbofan; requested fraction was %.12g.", ...
            externalBleedFraction);
    end
end

if isfield(cfg.external_loads, "accessory_power_extraction_W")
    accessoryPowerExtraction_W = ...
        cfg.external_loads.accessory_power_extraction_W;

    validateattributes( ...
        accessoryPowerExtraction_W, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'nonnegative'});

    if accessoryPowerExtraction_W ~= 0
        error( ...
            "TurbofanConfig:UnsupportedAccessoryPowerExtraction", ...
            "Nonzero accessory power extraction is not implemented by run_turbofan; requested power was %.12g W.", ...
            accessoryPowerExtraction_W);
    end
end

end


function [cfg, combustorExitTemperature_K] = ...
    resolve_combustor_exit_temperature(cfg)
%RESOLVE_COMBUSTOR_EXIT_TEMPERATURE Enforce canonical Tt4 authority.

canonicalField = "combustor_exit_temperature_K";
legacyField = "turbine_inlet_temperature_K";

hasCanonical = isfield(cfg.engine, canonicalField);
hasLegacy = isfield(cfg.engine, legacyField);

if ~hasCanonical && ~hasLegacy
    error( ...
        "TurbofanConfig:MissingCombustorExitTemperature", ...
        "Configuration must define engine.%s.", ...
        canonicalField);
end

if hasCanonical
    combustorExitTemperature_K = ...
        cfg.engine.(canonicalField);
else
    combustorExitTemperature_K = ...
        cfg.engine.(legacyField);

    cfg.engine.(canonicalField) = ...
        combustorExitTemperature_K;
end

validateattributes( ...
    combustorExitTemperature_K, ...
    {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

if hasLegacy
    legacyTemperature_K = ...
        cfg.engine.(legacyField);

    validateattributes( ...
        legacyTemperature_K, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});

    if legacyTemperature_K ~= combustorExitTemperature_K
        error( ...
            "TurbofanConfig:InconsistentCombustorExitTemperature", ...
            "engine.%s (%.12g K) must equal canonical engine.%s (%.12g K).", ...
            legacyField, ...
            legacyTemperature_K, ...
            canonicalField, ...
            combustorExitTemperature_K);
    end
else
    cfg.engine.(legacyField) = ...
        combustorExitTemperature_K;
end

end
