function summary = test_cf34_fixed_nozzle_diagnostics()
%TEST_CF34_FIXED_NOZZLE_DIAGNOSTICS Verify APR fixed-area diagnostics.
%
% This test expects run_turbofan.m to package fixed-area nozzle-capacity
% results and capacity residuals without changing the existing cycle solve.

clc;

%% Project paths
testFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Run inherited APR baseline
cfg = baseline_engine();
cfg = apply_cf34_operating_point( ...
    cfg, ...
    "maximum_takeoff_apr");

results = run_turbofan(cfg);

%% Test state
passedCount = 0;
failedCount = 0;
failureMessages = strings(0, 1);

fprintf("\nCF34 fixed-nozzle diagnostic test started\n");
fprintf("==================================================\n");

%% Required packaged fields
requiredFieldsPresent = ...
    isfield(results, "nozzle_capacity") ...
    && isfield(results.nozzle_capacity, "core") ...
    && isfield(results.nozzle_capacity, "bypass") ...
    && isfield(results.residuals, "core_nozzle_capacity_kg_s") ...
    && isfield(results.residuals, "bypass_nozzle_capacity_kg_s");

check( ...
    "Fixed-area nozzle diagnostics are packaged", ...
    requiredFieldsPresent, ...
    "Expected results.nozzle_capacity and residual fields.");

if requiredFieldsPresent
    core = results.nozzle_capacity.core;
    bypass = results.nozzle_capacity.bypass;

    capacityTolerance_kg_s = 1e-4;
    areaTolerance_m2 = 1e-8;

    check( ...
        "Core fixed area matches the baseline configuration", ...
        abs(core.area_m2 ...
            - cfg.geometry.core_nozzle_area_m2) <= areaTolerance_m2, ...
        sprintf( ...
            "Difference: %.12g m^2", ...
            core.area_m2 ...
            - cfg.geometry.core_nozzle_area_m2));

    check( ...
        "Bypass fixed area matches the baseline configuration", ...
        abs(bypass.area_m2 ...
            - cfg.geometry.bypass_nozzle_area_m2) <= areaTolerance_m2, ...
        sprintf( ...
            "Difference: %.12g m^2", ...
            bypass.area_m2 ...
            - cfg.geometry.bypass_nozzle_area_m2));

    check( ...
        "Core nozzle capacity residual closes at APR", ...
        abs(results.residuals.core_nozzle_capacity_kg_s) ...
            <= capacityTolerance_kg_s, ...
        sprintf( ...
            "Residual: %.12g kg/s", ...
            results.residuals.core_nozzle_capacity_kg_s));

    check( ...
        "Bypass nozzle capacity residual closes at APR", ...
        abs(results.residuals.bypass_nozzle_capacity_kg_s) ...
            <= capacityTolerance_kg_s, ...
        sprintf( ...
            "Residual: %.12g kg/s", ...
            results.residuals.bypass_nozzle_capacity_kg_s));

    check( ...
        "APR nozzle choking states remain correct", ...
        logical(core.is_choked) ...
        && ~logical(bypass.is_choked), ...
        sprintf( ...
            "Core choked=%d, bypass choked=%d", ...
            logical(core.is_choked), ...
            logical(bypass.is_choked)));
end

%% Final summary
totalCount = passedCount + failedCount;

summary = struct();
summary.total_tests = totalCount;
summary.passed_tests = passedCount;
summary.failed_tests = failedCount;
summary.failure_messages = failureMessages;

fprintf("==================================================\n");
fprintf("Passed: %d\n", passedCount);
fprintf("Failed: %d\n", failedCount);
fprintf("Total:  %d\n", totalCount);

if failedCount > 0
    fprintf(2, "\nFailed checks\n");

    for failureIndex = 1:numel(failureMessages)
        fprintf(2, "  %s\n", failureMessages(failureIndex));
    end

    error( ...
        "CF34 fixed-nozzle diagnostic test failed: %d of %d checks failed.", ...
        failedCount, ...
        totalCount);
end

fprintf("CF34 fixed-nozzle diagnostic test PASSED\n\n");


    function check(testName, condition, detail)
    %CHECK Record and print one test result.

        if condition
            passedCount = passedCount + 1;
            fprintf("[PASS] %s\n", testName);
        else
            failedCount = failedCount + 1;

            failureMessage = ...
                string(testName) + " -- " + string(detail);

            failureMessages(end + 1, 1) = ...
                failureMessage;

            fprintf(2, "[FAIL] %s\n", failureMessage);
        end
    end

end
