function summary = test_cf34_multipoint_matcher()
%TEST_CF34_MULTIPOINT_MATCHER Verify the expected no-exact-solution diagnosis.
% The bounded diagnostic preserves Automatic Power Reserve (APR) and examines
% three ICAO Engine Emissions Databank (EDB) targets without accepting them.

clc;

%% Project paths
testFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Capture APR configuration and execute matcher
cfgApr = baseline_engine();
resultsAprBefore = run_turbofan(cfgApr);

match = match_cf34_multipoint(cfgApr);
resultsAprAfter = run_turbofan(match.apr.cfg);

schedule = match.schedule;

%% Diagnostic limits
exactSolutionTolerance = 5e-5;
maximumJacobianConditionNumber = 1e5;
maximumAprThrustDifference_N = 1e-9;
maximumAprTSFCDifference_g_kN_s = 1e-12;
objectiveConsistencyTolerance = 1e-12;

expectedObjectives = [ ...
    0.0030406741716204233
    0.00057681147220320654
    0.09396520447414955];

objectiveRegressionTolerance = ...
    max(1e-10, 1e-5 * expectedObjectives);

expectedRawResiduals = [ ...
    -3891.194675,  0.020099062, 0.692599832,   0.571130799
    -1358.022421,  0.009760883, 0.151527388,  -0.033924364
    -4383.310080,  0.050071940, 0.545318884, -14.521378833];

rawResidualRegressionTolerance = [2, 2e-5, 2e-3, 2e-3];

checkName = strings(0, 1);
checkPassed = false(0, 1);
checkDetail = strings(0, 1);

fprintf("\nCF34 multipoint no-exact-solution diagnostic test started\n");
fprintf("==================================================\n");

%% Scope and APR preservation
add_check( ...
    "Only the three supported EDB points are fitted", ...
    isequal(schedule.PointId, [ ...
        "normal_takeoff_edb"; ...
        "climb_out_edb"; ...
        "approach_edb"]), ...
    "Idle, maximum-continuous, and cruise must remain holdouts.");

add_check( ...
    "Matcher is explicitly classified as diagnostic", ...
    match.classification == "diagnostic_feasibility_study" ...
    && ~match.is_accepted_off_design_model ...
    && all(schedule.Classification == "diagnostic"), ...
    "The bounded matcher must not be represented as an accepted schedule.");

add_check( ...
    "APR effective inputs remain numerically unchanged", ...
    all(abs([ ...
        cfgApr.engine.core_airflow_kg_s ...
        cfgApr.engine.bypass_ratio ...
        cfgApr.engine.target_overall_pressure_ratio ...
        cfgApr.engine.fan_pressure_ratio ...
        cfgApr.engine.lpc_pressure_ratio ...
        cfgApr.engine.hpc_pressure_ratio ...
        cfgApr.engine.combustor_exit_temperature_K] ...
        - [ ...
        match.apr.cfg.engine.core_airflow_kg_s ...
        match.apr.cfg.engine.bypass_ratio ...
        match.apr.cfg.engine.target_overall_pressure_ratio ...
        match.apr.cfg.engine.fan_pressure_ratio ...
        match.apr.cfg.engine.lpc_pressure_ratio ...
        match.apr.cfg.engine.hpc_pressure_ratio ...
        match.apr.cfg.engine.combustor_exit_temperature_K]) <= 1e-12), ...
    "The matcher must not alter the inherited APR engine inputs.");

add_check( ...
    "APR fixed nozzle areas remain bit-for-bit unchanged", ...
    isequaln(cfgApr.geometry, match.apr.cfg.geometry), ...
    "The matcher must preserve both fixed nozzle areas exactly.");

add_check( ...
    "APR numerical regression remains unchanged", ...
    abs(resultsAprAfter.performance.net_thrust_N ...
        - resultsAprBefore.performance.net_thrust_N) ...
        <= maximumAprThrustDifference_N ...
    && abs(resultsAprAfter.performance.tsfc_g_kN_s ...
        - resultsAprBefore.performance.tsfc_g_kN_s) ...
        <= maximumAprTSFCDifference_g_kN_s, ...
    sprintf( ...
        "Thrust difference %.12g N; TSFC difference %.12g g/(kN*s).", ...
        resultsAprAfter.performance.net_thrust_N ...
            - resultsAprBefore.performance.net_thrust_N, ...
        resultsAprAfter.performance.tsfc_g_kN_s ...
            - resultsAprBefore.performance.tsfc_g_kN_s));

%% Successful bounded diagnosis and local conditioning
add_check( ...
    "No exact solution was found by the bounded local diagnostic", ...
    all(schedule.FeasibilityStatus ...
        == "no_exact_solution_found_within_bounds") ...
    && all(~[match.cases.is_exact_solution]') ...
    && all(schedule.MaximumNormalizedResidual ...
        > exactSolutionTolerance), ...
    sprintf( ...
        "Minimum nonzero normalized residual %.6g.", ...
        min(schedule.MaximumNormalizedResidual)));

add_check( ...
    "Every selected diagnostic solution terminated successfully", ...
    all(schedule.SolverSuccess) ...
    && all(schedule.SelectedExitFlag > 0) ...
    && all([match.cases.solver_success]') ...
    && all([match.cases.exit_flag]' > 0), ...
    "Physical feasibility status requires a successful positive solver exit flag.");

completeStartDiagnostics = true;
selectedStartDiagnosticsValid = true;
expectedFailureRecordsValid = true;

for pointIndex = 1:numel(match.cases)
    starts = match.cases(pointIndex).start_diagnostics;

    completeStartDiagnostics = completeStartDiagnostics ...
        && numel(starts) == match.deterministic_start_count ...
        && all(isfinite([starts.exit_flag])) ...
        && all(isfinite([starts.iterations])) ...
        && all(isfinite([starts.function_evaluations]));

    selectedMask = [starts.selected];
    selectedStartDiagnosticsValid = selectedStartDiagnosticsValid ...
        && nnz(selectedMask) == 1 ...
        && find(selectedMask, 1) ...
            == match.cases(pointIndex).selected_start_index ...
        && starts(selectedMask).solver_exit_success ...
        && starts(selectedMask).terminal_evaluation_valid ...
        && starts(selectedMask).objective_consistent;

    for startIndex = 1:numel(starts)
        expectedFailureRecordsValid = expectedFailureRecordsValid ...
            && starts(startIndex).expected_failure_count ...
                == numel(starts(startIndex).expected_failure_identifiers) ...
            && starts(startIndex).expected_failure_count ...
                == numel(starts(startIndex).expected_failure_messages) ...
            && starts(startIndex).expected_failure_count ...
                == numel(starts(startIndex).expected_failure_contexts) ...
            && all(strlength( ...
                starts(startIndex).expected_failure_identifiers) > 0) ...
            && all(strlength( ...
                starts(startIndex).expected_failure_messages) > 0) ...
            && all(strlength( ...
                starts(startIndex).expected_failure_contexts) > 0);
    end
end

add_check( ...
    "Every deterministic start retains termination diagnostics", ...
    completeStartDiagnostics && selectedStartDiagnosticsValid, ...
    "Each point must retain all starts and identify one successful selected start.");

add_check( ...
    "Expected domain failures retain identifiers and evaluation context", ...
    expectedFailureRecordsValid ...
    && all([match.cases.unexpected_exception_count] == 0), ...
    "Expected domain failures must be diagnosable; unexpected exceptions must rethrow.");

objectiveConsistencyErrors = abs( ...
    schedule.Objective ...
    - arrayfun( ...
        @(entry) sum(entry.normalized_residuals .^ 2), ...
        match.cases));

add_check( ...
    "Selected objectives equal squared normalized residual norms", ...
    all(objectiveConsistencyErrors <= objectiveConsistencyTolerance) ...
    && all(schedule.ObjectiveConsistencyError ...
        <= objectiveConsistencyTolerance), ...
    sprintf( ...
        "Maximum objective consistency error %.6g.", ...
        max(objectiveConsistencyErrors)));

add_check( ...
    "Diagnostic objectives remain inside bounded regression envelopes", ...
    all(abs(schedule.Objective - expectedObjectives) ...
        <= objectiveRegressionTolerance), ...
    sprintf( ...
        "Maximum objective regression error %.6g.", ...
        max(abs(schedule.Objective - expectedObjectives))));

actualRawResiduals = [ ...
    schedule.ThrustResidual_N, ...
    schedule.FuelFlowResidual_kg_s, ...
    schedule.CoreNozzleCapacityResidual_kg_s, ...
    schedule.BypassNozzleCapacityResidual_kg_s];

add_check( ...
    "Diagnostic residual vectors remain inside bounded regression envelopes", ...
    all(abs(actualRawResiduals - expectedRawResiduals) ...
        <= rawResidualRegressionTolerance, ...
        "all"), ...
    "A materially degraded finite local solution must not pass unnoticed.");

finiteDiagnostics = all(isfinite([ ...
    schedule.CoreAirflow_kg_s
    schedule.EffectiveBypassRatio
    schedule.EffectiveOverallPressureRatio
    schedule.CombustorExitTemperature_K
    schedule.ThrustResidual_N
    schedule.FuelFlowResidual_kg_s
    schedule.CoreNozzleCapacityResidual_kg_s
    schedule.BypassNozzleCapacityResidual_kg_s
    schedule.MaximumNormalizedResidual
    schedule.JacobianConditionNumber]));

add_check( ...
    "All solver results and residual diagnostics are finite", ...
    finiteDiagnostics, ...
    "Every investigated point must produce a finite diagnostic record.");

allFullRank = all(arrayfun( ...
    @(entry) entry.jacobian_rank == 4, ...
    match.cases));

add_check( ...
    "Four-residual Jacobians are full rank", ...
    allFullRank, ...
    "Each point must locally identify all four effective quantities.");

add_check( ...
    "Four-residual Jacobians are acceptably conditioned", ...
    all(schedule.JacobianConditionNumber ...
        <= maximumJacobianConditionNumber), ...
    sprintf( ...
        "Maximum condition number %.6g.", ...
        max(schedule.JacobianConditionNumber)));

%% Active bounds and fixed geometry
expectedActiveBounds = [ ...
    "combustor_exit_temperature_upper"
    "combustor_exit_temperature_upper"
    "effective_bypass_ratio_upper"];

add_check( ...
    "Expected active bounds are reported", ...
    isequal(schedule.ActiveBounds, expectedActiveBounds), ...
    "Expected Tt4 upper bounds at takeoff/climb and BPR upper bound at approach.");

effectiveStates = [ ...
    schedule.CoreAirflow_kg_s, ...
    schedule.EffectiveBypassRatio, ...
    schedule.EffectiveOverallPressureRatio, ...
    schedule.CombustorExitTemperature_K];

boundTolerance = 1e-10 * (match.upper_bounds - match.lower_bounds);

add_check( ...
    "Effective diagnostic states remain positive and bounded", ...
    all(effectiveStates > 0, "all") ...
    && all(effectiveStates ...
        >= match.lower_bounds - boundTolerance, "all") ...
    && all(effectiveStates ...
        <= match.upper_bounds + boundTolerance, "all") ...
    && all(schedule.FanPressureRatio > 1) ...
    && all(schedule.LPCPressureRatio > 1) ...
    && all(schedule.HPCPressureRatio > 1), ...
    "Every effective quantity and pressure-ratio component must remain admissible.");

monotonicTolerance = 1e-8;

add_check( ...
    "Effective diagnostic states remain physically monotonic with power", ...
    all(diff(schedule.CoreAirflow_kg_s) <= monotonicTolerance) ...
    && all(diff(schedule.EffectiveBypassRatio) >= -monotonicTolerance) ...
    && all(diff(schedule.EffectiveOverallPressureRatio) ...
        <= monotonicTolerance) ...
    && all(diff(schedule.CombustorExitTemperature_K) ...
        <= monotonicTolerance), ...
    "Rows descend in power; flow, pressure ratio, and Tt4 must not rise materially.");

nozzleAreasPreserved = true;

for pointIndex = 1:numel(match.cases)
    nozzleAreasPreserved = nozzleAreasPreserved ...
        && isequal( ...
            match.cases(pointIndex).cfg.geometry.core_nozzle_area_m2, ...
            cfgApr.geometry.core_nozzle_area_m2) ...
        && isequal( ...
            match.cases(pointIndex).cfg.geometry.bypass_nozzle_area_m2, ...
            cfgApr.geometry.bypass_nozzle_area_m2);
end

add_check( ...
    "Both fixed nozzle areas are preserved at every fitted point", ...
    nozzleAreasPreserved, ...
    "Nozzle geometry must not become a calibration variable.");

add_check( ...
    "Target provenance and thrust basis are retained", ...
    all(strlength(schedule.TargetProvenance) > 0) ...
    && all(strlength(schedule.TargetThrustBasis) > 0), ...
    "Every diagnostic row must identify its external or derived target basis.");

operatingPointStatuses = string(arrayfun( ...
    @(entry) entry.cfg.operating_point.validation_status, ...
    match.cases, ...
    'UniformOutput', false));

classificationText = lower( ...
    schedule.Classification ...
    + " " + schedule.FeasibilityStatus ...
    + " " + operatingPointStatuses);

add_check( ...
    "EDB diagnostic results reject accepted or calibrated labels", ...
    all(operatingPointStatuses == "diagnostic_feasibility_target") ...
    && ~any(contains(classificationText, "accepted") ...
        | contains(classificationText, "calibrated") ...
        | contains(classificationText, "validated")), ...
    "No failed EDB diagnostic may be presented as accepted or calibrated.");

%% Explicit solver-nonconvergence classification path
nonconvergenceOptions = struct( ...
    'solver_max_iterations', 0, ...
    'solver_max_function_evaluations', 1);

nonconvergedMatch = match_cf34_multipoint( ...
    cfgApr, ...
    nonconvergenceOptions);

nonconvergedStatuses = ...
    nonconvergedMatch.schedule.FeasibilityStatus;

add_check( ...
    "Solver nonconvergence is not classified as physical infeasibility", ...
    all(~nonconvergedMatch.schedule.SolverSuccess) ...
    && all(nonconvergedStatuses ...
        == "solver_failure_no_successful_start") ...
    && ~any(contains( ...
        nonconvergedStatuses, ...
        "no_exact_solution_found")) ...
    && all(isnan( ...
        nonconvergedMatch.schedule.MaximumNormalizedResidual)), ...
    "Zero-iteration diagnostics must report solver failure with no feasibility claim.");

%% Display numerical diagnostics
disp(schedule);

audit = table( ...
    checkName, ...
    checkPassed, ...
    checkDetail, ...
    'VariableNames', {'Check', 'Passed', 'Detail'});

disp(audit);

passedCount = nnz(checkPassed);
failedCount = numel(checkPassed) - passedCount;

summary = struct();
summary.total_checks = numel(checkPassed);
summary.passed_checks = passedCount;
summary.failed_checks = failedCount;
summary.schedule = schedule;
summary.audit = audit;

fprintf("==================================================\n");
fprintf("Passed: %d\n", passedCount);
fprintf("Failed: %d\n", failedCount);
fprintf("Total:  %d\n", numel(checkPassed));

if failedCount > 0
    error( ...
        "CF34 multipoint matcher test failed: %d check(s) failed.", ...
        failedCount);
end

fprintf("CF34 multipoint no-exact-solution diagnostic test PASSED\n\n");


    function add_check(name, condition, detail)
        checkName(end + 1, 1) = string(name);
        checkPassed(end + 1, 1) = logical(condition);
        checkDetail(end + 1, 1) = string(detail);

        if condition
            fprintf("[PASS] %s\n", name);
        else
            fprintf(2, "[FAIL] %s -- %s\n", name, detail);
        end
    end

end
