function summary = test_v05_acceptance()
%TEST_V05_ACCEPTANCE Automated acceptance checks for turbofan model v0.5.
%
% Run from MATLAB with:
%
%   test_v05_acceptance
%
% The test executes the active baseline configuration directly. It does
% not create Data or Figures run folders and does not modify model inputs.

clc;

%% Project paths
testFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Execute active baseline
cfg = baseline_engine();
ref = cf34_10e_reference();
results = run_turbofan(cfg);

hpt = results.hpt_sizing;

%% Acceptance targets and tolerances
expectedModelVersion = "0.5";

referenceThrust_N = ...
    ref.performance.sea_level_static_thrust_N;

expectedBaselineThrust_N = ...
    90561.52557522783;

expectedBaselineTSFC_g_kN_s = ...
    11.268947855401436;

maximumReferenceThrustError_N = 10;
maximumRegressionThrustError_N = 25;
maximumRegressionTSFCError_g_kN_s = 0.01;

maximumPowerResidual_W = 1e-3;
maximumMassResidual_kg_s = 1e-10;
maximumMixerEnergyResidual_W = 1e-6;

maximumAcceptedHPTMach = 1.08;
minimumAcceptedMeanRadius_m = 0.30;
maximumAcceptedMeanRadius_m = 0.33;

%% Test state
passedCount = 0;
failedCount = 0;
failureMessages = strings(0, 1);

fprintf("\nv0.5 acceptance test started\n");
fprintf("==================================================\n");

%% Metadata and calibrated inputs
check( ...
    "Model version is v0.5", ...
    string(cfg.meta.model_version) == expectedModelVersion, ...
    "Actual version: " + string(cfg.meta.model_version));

check( ...
    "CF34-10E bypass ratio is 5.4", ...
    abs(cfg.engine.bypass_ratio - 5.4) < 1e-12, ...
    sprintf("Actual BPR: %.12g", cfg.engine.bypass_ratio));

calculatedOPR = ...
    cfg.engine.fan_pressure_ratio ...
    * cfg.engine.lpc_pressure_ratio ...
    * cfg.engine.hpc_pressure_ratio;

check( ...
    "Overall pressure ratio is 29", ...
    abs(calculatedOPR - 29.0) < 1e-10, ...
    sprintf("Calculated OPR: %.12f", calculatedOPR));

check( ...
    "Public CF34 architecture is represented", ...
    cfg.architecture.fan_stage_count == 1 ...
    && cfg.architecture.lpc_stage_count == 3 ...
    && cfg.architecture.hpc_stage_count == 9 ...
    && cfg.architecture.hpt_stage_count == 1 ...
    && cfg.architecture.lpt_stage_count == 4, ...
    "Expected stage counts: 1 fan / 3 LPC / 9 HPC / 1 HPT / 4 LPT");

%% Reference calibration and baseline regression
referenceThrustError_N = ...
    results.performance.net_thrust_N ...
    - referenceThrust_N;

check( ...
    "Thrust matches CF34-10E7 reference within 10 N", ...
    abs(referenceThrustError_N) <= maximumReferenceThrustError_N, ...
    sprintf( ...
        "Error: %+.6f N; model: %.6f kN; reference: %.6f kN", ...
        referenceThrustError_N, ...
        results.performance.net_thrust_N / 1000, ...
        referenceThrust_N / 1000));

regressionThrustError_N = ...
    results.performance.net_thrust_N ...
    - expectedBaselineThrust_N;

check( ...
    "Baseline thrust regression is stable", ...
    abs(regressionThrustError_N) <= maximumRegressionThrustError_N, ...
    sprintf( ...
        "Regression error: %+.6f N", ...
        regressionThrustError_N));

regressionTSFCError_g_kN_s = ...
    results.performance.tsfc_g_kN_s ...
    - expectedBaselineTSFC_g_kN_s;

check( ...
    "Baseline TSFC regression is stable", ...
    abs(regressionTSFCError_g_kN_s) ...
    <= maximumRegressionTSFCError_g_kN_s, ...
    sprintf( ...
        "TSFC error: %+.9f g/(kN*s)", ...
        regressionTSFCError_g_kN_s));

%% Conservation and spool balances
check( ...
    "High-spool power balance closes", ...
    abs(results.residuals.high_spool_W) ...
    <= maximumPowerResidual_W, ...
    sprintf( ...
        "Residual: %.12g W", ...
        results.residuals.high_spool_W));

check( ...
    "Low-spool power balance closes", ...
    abs(results.residuals.low_spool_W) ...
    <= maximumPowerResidual_W, ...
    sprintf( ...
        "Residual: %.12g W", ...
        results.residuals.low_spool_W));

check( ...
    "Engine mass-flow balance closes", ...
    abs(results.residuals.mass_kg_s) ...
    <= maximumMassResidual_kg_s, ...
    sprintf( ...
        "Residual: %.12g kg/s", ...
        results.residuals.mass_kg_s));

check( ...
    "Cooling mixer energy balance closes", ...
    abs(results.cooling.mixer_energy_residual_W) ...
    <= maximumMixerEnergyResidual_W, ...
    sprintf( ...
        "Residual: %.12g W", ...
        results.cooling.mixer_energy_residual_W));

totalAirflowResidual_kg_s = ...
    results.mass.mdot_total_air_kg_s ...
    - (results.mass.mdot_core_air_kg_s ...
    + results.mass.mdot_bypass_air_kg_s);

check( ...
    "Total airflow equals core plus bypass airflow", ...
    abs(totalAirflowResidual_kg_s) <= maximumMassResidual_kg_s, ...
    sprintf( ...
        "Residual: %.12g kg/s", ...
        totalAirflowResidual_kg_s));

hptFlowResidual_kg_s = ...
    results.mass.mdot_hpt_kg_s ...
    - (results.mass.mdot_combustor_air_kg_s ...
    + results.mass.mdot_cooling_air_kg_s ...
    + results.mass.mdot_fuel_kg_s);

check( ...
    "HPT flow includes combustor air, coolant, and fuel", ...
    abs(hptFlowResidual_kg_s) <= maximumMassResidual_kg_s, ...
    sprintf( ...
        "Residual: %.12g kg/s", ...
        hptFlowResidual_kg_s));

%% Thermodynamic state ordering
pressureOrderingPasses = ...
    results.stations.station3.Pt_Pa ...
        > results.stations.station25.Pt_Pa ...
    && results.stations.station25.Pt_Pa ...
        > results.stations.station21.Pt_Pa ...
    && results.stations.station21.Pt_Pa ...
        > results.stations.station2.Pt_Pa ...
    && results.stations.station41.Pt_Pa ...
        < results.stations.station4.Pt_Pa ...
    && results.stations.station45.Pt_Pa ...
        < results.stations.station41.Pt_Pa ...
    && results.stations.station5.Pt_Pa ...
        < results.stations.station45.Pt_Pa;

check( ...
    "Compressor and turbine pressure ordering is physical", ...
    pressureOrderingPasses, ...
    "Expected compression pressure rise and turbine pressure drop");

temperatureOrderingPasses = ...
    results.stations.station4.Tt_K ...
        > results.stations.station41.Tt_K ...
    && results.stations.station41.Tt_K ...
        > results.stations.station45.Tt_K ...
    && results.stations.station45.Tt_K ...
        > results.stations.station5.Tt_K;

check( ...
    "Hot-section total-temperature ordering is physical", ...
    temperatureOrderingPasses, ...
    "Expected Tt4 > Tt41 > Tt45 > Tt5");

%% Nozzle behavior
check( ...
    "Core nozzle remains choked at the baseline point", ...
    logical(results.stations.station9.is_choked), ...
    sprintf( ...
        "Core nozzle Mach: %.6f", ...
        results.stations.station9.Mach));

check( ...
    "Bypass nozzle remains unchoked at the baseline point", ...
    ~logical(results.stations.station19.is_choked), ...
    sprintf( ...
        "Bypass nozzle Mach: %.6f", ...
        results.stations.station19.Mach));

%% Accepted preliminary HPT design
check( ...
    "Accepted HPT coefficients are active", ...
    abs(hpt.loading_coefficient - 1.20) < 1e-12 ...
    && abs(hpt.flow_coefficient - 0.45) < 1e-12 ...
    && abs(hpt.reaction - 0.50) < 1e-12 ...
    && hpt.stage_count == 1, ...
    sprintf( ...
        "psi=%.6f, phi=%.6f, R=%.6f, stages=%d", ...
        hpt.loading_coefficient, ...
        hpt.flow_coefficient, ...
        hpt.reaction, ...
        hpt.stage_count));

geometryPasses = ...
    hpt.mean_radius_m >= minimumAcceptedMeanRadius_m ...
    && hpt.mean_radius_m <= maximumAcceptedMeanRadius_m ...
    && hpt.blade_span_inlet_m > 0 ...
    && hpt.blade_span_exit_m > 0 ...
    && hpt.hub_radius_inlet_m > 0 ...
    && hpt.hub_radius_exit_m > 0 ...
    && hpt.tip_radius_inlet_m > hpt.hub_radius_inlet_m ...
    && hpt.tip_radius_exit_m > hpt.hub_radius_exit_m;

check( ...
    "Preliminary HPT geometry is positive and within range", ...
    geometryPasses, ...
    sprintf( ...
        "rm=%.6f m, hin=%.6f m, hex=%.6f m", ...
        hpt.mean_radius_m, ...
        hpt.blade_span_inlet_m, ...
        hpt.blade_span_exit_m));

machVector = [ ...
    hpt.rotor_inlet_absolute_mach, ...
    hpt.rotor_inlet_relative_mach, ...
    hpt.rotor_exit_absolute_mach, ...
    hpt.rotor_exit_relative_mach];

check( ...
    "Stored maximum HPT Mach is internally consistent", ...
    abs(hpt.maximum_mach - max(machVector)) < 1e-12, ...
    sprintf( ...
        "Stored: %.9f; recomputed: %.9f", ...
        hpt.maximum_mach, ...
        max(machVector)));

check( ...
    "HPT rotor-inlet absolute Mach remains below one", ...
    hpt.rotor_inlet_absolute_mach < 1.0, ...
    sprintf( ...
        "Rotor-inlet absolute Mach: %.6f", ...
        hpt.rotor_inlet_absolute_mach));

check( ...
    "HPT maximum mean-line Mach remains at or below 1.08", ...
    hpt.maximum_mach <= maximumAcceptedHPTMach, ...
    sprintf( ...
        "Maximum Mach: %.6f", ...
        hpt.maximum_mach));

check( ...
    "Project 2 HPT handoff fields are populated", ...
    all(isfinite([ ...
        results.stations.station3.Tt_K, ...
        results.stations.station3.Pt_Pa, ...
        results.stations.station41.Tt_K, ...
        results.stations.station41.Pt_Pa, ...
        results.stations.station45.Tt_K, ...
        results.stations.station45.Pt_Pa, ...
        hpt.mean_radius_m, ...
        hpt.blade_span_inlet_m, ...
        hpt.blade_span_exit_m, ...
        hpt.shaft_speed_rpm])), ...
    "Required coolant, hot-gas, geometry, and speed values must be finite");

%% Final summary
totalCount = passedCount + failedCount;

summary = struct();
summary.model_version = string(cfg.meta.model_version);
summary.total_tests = totalCount;
summary.passed_tests = passedCount;
summary.failed_tests = failedCount;
summary.failure_messages = failureMessages;
summary.net_thrust_N = results.performance.net_thrust_N;
summary.tsfc_g_kN_s = results.performance.tsfc_g_kN_s;
summary.hpt_maximum_mach = hpt.maximum_mach;

fprintf("==================================================\n");
fprintf("Acceptance-test summary\n");
fprintf("--------------------------------------------------\n");
fprintf("Passed: %d\n", passedCount);
fprintf("Failed: %d\n", failedCount);
fprintf("Total:  %d\n", totalCount);
fprintf("==================================================\n");

if failedCount > 0
    fprintf(2, "\nFailed checks\n");

    for failureIndex = 1:numel(failureMessages)
        fprintf(2, "  %s\n", failureMessages(failureIndex));
    end

    error( ...
        "v0.5 acceptance test failed: %d of %d checks failed.", ...
        failedCount, ...
        totalCount);
end

fprintf("v0.5 acceptance test PASSED\n\n");


    function check(testName, condition, detail)
    %CHECK Record and print one acceptance-test result.

        if condition
            passedCount = passedCount + 1;
            fprintf("[PASS] %s\n", testName);
        else
            failedCount = failedCount + 1;

            failureMessage = ...
                testName + " -- " + string(detail);

            failureMessages(end + 1, 1) = ...
                failureMessage;

            fprintf(2, "[FAIL] %s\n", failureMessage);
        end
    end

end
