function summary = test_cf34_operating_points()
%TEST_CF34_OPERATING_POINTS Smoke-test public operating-point definitions.
%
% This test verifies operating-point metadata and ambient-condition routing.
% It intentionally runs the full cycle only at the inherited APR baseline,
% because generic off-design matching has not yet been implemented.

clc;

%% Project paths
testFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Operating points to inspect
pointIds = [
    "maximum_takeoff_apr"
    "normal_takeoff_edb"
    "climb_out_edb"
    "approach_edb"
    "idle_edb"
    "maximum_continuous"
    "cruise_holdout"
];

numberPoints = numel(pointIds);

pointName = strings(numberPoints, 1);
role = strings(numberPoints, 1);
altitude_m = nan(numberPoints, 1);
flightMach = nan(numberPoints, 1);
ambientTemperature_K = nan(numberPoints, 1);
ambientPressure_kPa = nan(numberPoints, 1);
temperatureOverrideActive = false(numberPoints, 1);
pressureOverrideActive = false(numberPoints, 1);
targetThrust_kN = nan(numberPoints, 1);
targetFuelFlow_kg_s = nan(numberPoints, 1);
targetTSFC_g_kN_s = nan(numberPoints, 1);

fprintf("\nCF34 operating-point smoke test started\n");
fprintf("==================================================\n");

for i = 1:numberPoints
    cfg = baseline_engine();
    cfg = apply_cf34_operating_point(cfg, pointIds(i));

    atm = atmosphere( ...
        cfg.flight.altitude_m, ...
        cfg.flight.ambient_temperature_override_K, ...
        cfg.flight.ambient_pressure_override_Pa);

    pointName(i) = cfg.operating_point.name;
    role(i) = cfg.operating_point.calibration_role;
    altitude_m(i) = cfg.flight.altitude_m;
    flightMach(i) = cfg.flight.Mach;
    ambientTemperature_K(i) = atm.temperature_K;
    ambientPressure_kPa(i) = atm.pressure_Pa / 1000;
    temperatureOverrideActive(i) = atm.temperature_override_active;
    pressureOverrideActive(i) = atm.pressure_override_active;
    targetThrust_kN(i) = cfg.operating_point.target_thrust_N / 1000;
    targetFuelFlow_kg_s(i) = cfg.operating_point.target_fuel_flow_kg_s;
    targetTSFC_g_kN_s(i) = cfg.operating_point.target_tsfc_g_kN_s;
end

operatingPointTable = table( ...
    pointIds, ...
    pointName, ...
    role, ...
    altitude_m, ...
    flightMach, ...
    ambientTemperature_K, ...
    ambientPressure_kPa, ...
    temperatureOverrideActive, ...
    pressureOverrideActive, ...
    targetThrust_kN, ...
    targetFuelFlow_kg_s, ...
    targetTSFC_g_kN_s, ...
    'VariableNames', { ...
        'PointId', ...
        'PointName', ...
        'Role', ...
        'Altitude_m', ...
        'FlightMach', ...
        'AmbientTemperature_K', ...
        'AmbientPressure_kPa', ...
        'TemperatureOverrideActive', ...
        'PressureOverrideActive', ...
        'TargetThrust_kN', ...
        'TargetFuelFlow_kg_s', ...
        'TargetTSFC_g_kN_s'});

disp(operatingPointTable);

%% Checks
checkName = strings(0, 1);
checkPassed = false(0, 1);
checkDetail = strings(0, 1);

add_check( ...
    "All seven public operating points load", ...
    height(operatingPointTable) == 7, ...
    "Expected seven named conditions.");

edbRows = ismember(pointIds, [ ...
    "normal_takeoff_edb", ...
    "climb_out_edb", ...
    "approach_edb", ...
    "idle_edb"]);

add_check( ...
    "All EDB points activate temperature and pressure overrides", ...
    all(temperatureOverrideActive(edbRows)) ...
    && all(pressureOverrideActive(edbRows)), ...
    "EDB points should use the midpoint of the reported test range.");

add_check( ...
    "APR and maximum-continuous points remain sea-level static", ...
    altitude_m(1) == 0 ...
    && flightMach(1) == 0 ...
    && altitude_m(6) == 0 ...
    && flightMach(6) == 0, ...
    "Expected sea-level static rating definitions.");

add_check( ...
    "Cruise hold-out condition is 35,000 ft and Mach 0.8", ...
    abs(altitude_m(7) - 10668) < 1e-9 ...
    && abs(flightMach(7) - 0.8) < 1e-12, ...
    sprintf( ...
        "Actual altitude %.6f m and Mach %.6f.", ...
        altitude_m(7), ...
        flightMach(7)));

%% Full-cycle regression only at inherited APR baseline
cfgApr = baseline_engine();
cfgApr = apply_cf34_operating_point( ...
    cfgApr, ...
    "maximum_takeoff_apr");

resultsApr = run_turbofan(cfgApr);

add_check( ...
    "APR baseline thrust remains unchanged", ...
    abs(resultsApr.performance.net_thrust_N - 90561.52557522783) <= 25, ...
    sprintf( ...
        "Actual thrust %.6f kN.", ...
        resultsApr.performance.net_thrust_N / 1000));

add_check( ...
    "APR baseline TSFC remains unchanged", ...
    abs(resultsApr.performance.tsfc_g_kN_s ...
        - 11.268947855401436) <= 0.01, ...
    sprintf( ...
        "Actual TSFC %.9f g/(kN*s).", ...
        resultsApr.performance.tsfc_g_kN_s));

auditTable = table( ...
    checkName, ...
    checkPassed, ...
    checkDetail, ...
    'VariableNames', { ...
        'Check', ...
        'Passed', ...
        'Detail'});

disp(auditTable);

passedCount = nnz(checkPassed);
failedCount = numel(checkPassed) - passedCount;

summary = struct();
summary.total_checks = numel(checkPassed);
summary.passed_checks = passedCount;
summary.failed_checks = failedCount;
summary.operating_points = operatingPointTable;
summary.audit = auditTable;

fprintf("==================================================\n");
fprintf("Passed: %d\n", passedCount);
fprintf("Failed: %d\n", failedCount);
fprintf("Total:  %d\n", numel(checkPassed));

if failedCount > 0
    error( ...
        "CF34 operating-point smoke test failed: %d check(s) failed.", ...
        failedCount);
end

fprintf("CF34 operating-point smoke test PASSED\n\n");


    function add_check(name, condition, detail)
        checkName(end + 1, 1) = string(name);
        checkPassed(end + 1, 1) = logical(condition);
        checkDetail(end + 1, 1) = string(detail);

        if condition
            fprintf("[PASS] %s\n", name);
        else
            fprintf(2, "[FAIL] %s -- %s\n", name, detail);
        end
    end

end
