function summary = test_v06_acceptance()
%TEST_V06_ACCEPTANCE APR release checks for turbofan model v0.6.
%
% The accepted v0.5 Automatic Power Reserve (APR) numerical regression is
% retained as the foundation of v0.6. Multipoint EDB feasibility is tested
% separately by test_cf34_multipoint_matcher.
%
% Run from MATLAB with:
%
%   test_v06_acceptance
%
% The test executes the active baseline configuration directly. It does
% not create Data or Figures run folders and does not modify model inputs.

clc;

%% Project paths
testFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(testFolder);

addpath(fullfile(projectRoot, "Inputs"));
addpath(fullfile(projectRoot, "Functions"));

%% Execute active baseline
cfg = baseline_engine();
ref = cf34_10e_reference();
results = run_turbofan(cfg);

hpt = results.hpt_sizing;

%% Acceptance targets and tolerances
expectedModelVersion = "0.6";

expectedAprRegressionFoundation = ...
    "v0.5 accepted APR numerical baseline";

referenceThrust_N = ...
    ref.performance.sea_level_static_thrust_N;

expectedBaselineThrust_N = ...
    90561.52557522783;

expectedBaselineTSFC_g_kN_s = ...
    11.268947855401436;

maximumReferenceThrustError_N = 10;
maximumRegressionThrustError_N = 25;
maximumRegressionTSFCError_g_kN_s = 0.01;

maximumPowerResidual_W = 1e-3;
maximumMassResidual_kg_s = 1e-10;
maximumMixerEnergyResidual_W = 1e-6;

maximumAcceptedHPTMach = 1.08;
minimumAcceptedMeanRadius_m = 0.30;
maximumAcceptedMeanRadius_m = 0.33;

%% Independent accepted-v0.5 APR numerical input contract
contract.engine.core_airflow_kg_s = 43.03;
contract.engine.bypass_ratio = 5.4;
contract.engine.target_overall_pressure_ratio = 29.0;
contract.engine.fan_pressure_ratio = 1.60;
contract.engine.lpc_pressure_ratio = 1.80;
contract.engine.hpc_pressure_ratio = 29.0 / (1.60 * 1.80);
contract.engine.combustor_exit_temperature_K = 1600;

contract.geometry.core_nozzle_area_m2 = 0.157305086;
contract.geometry.bypass_nozzle_area_m2 = 0.693714887;

contract.efficiencies = [ ...
    0.995, ... % diffuser pressure recovery
    0.90, ...  % fan isentropic efficiency
    0.89, ...  % LPC isentropic efficiency
    0.88, ...  % HPC isentropic efficiency
    0.99, ...  % combustor efficiency
    0.91, ...  % HPT isentropic efficiency
    0.92];     % LPT isentropic efficiency

contract.losses = [ ...
    0.98, ... % core nozzle pressure recovery
    0.98, ... % bypass nozzle pressure recovery
    0.95, ... % combustor pressure ratio
    0.99, ... % bypass duct pressure ratio
    0.99, ... % core duct pressure ratio
    1.00];    % cooling-mixer loss coefficient

contract.mechanical_efficiencies = [0.99, 0.99];
contract.cooling_bleed_fraction = 0.05;
contract.external_loads = [0, 0];

contract.thermophysical = [287.05, 1.40, 1.33, 43.0e6];
contract.reference_state = [288.15, 101325];
contract.shaft_speeds_rpm = [18018, 6325];
contract.hpt_design = [1.20, 0.45, 0.50, 1];

contractTolerance = 1e-12;

%% Test state
passedCount = 0;
failedCount = 0;
failureMessages = strings(0, 1);

fprintf("\nv0.6 APR acceptance test started\n");
fprintf("==================================================\n");

%% Metadata and calibrated inputs
check( ...
    "Model version is v0.6", ...
    string(cfg.meta.model_version) == expectedModelVersion, ...
    "Actual version: " + string(cfg.meta.model_version));

check( ...
    "Accepted v0.5 APR numerical foundation is identified", ...
    string(cfg.meta.apr_regression_foundation) ...
        == expectedAprRegressionFoundation, ...
    "Actual foundation: " ...
        + string(cfg.meta.apr_regression_foundation));

check( ...
    "Release scope is APR design-point validation", ...
    string(cfg.meta.release_status) ...
        == "Validated APR design-point engine deck" ...
    && contains( ...
        string(cfg.meta.multipoint_status), ...
        "Diagnostic feasibility study"), ...
    "Expected APR release scope and diagnostic multipoint status.");

actualEngineContract = [ ...
    cfg.engine.core_airflow_kg_s, ...
    cfg.engine.bypass_ratio, ...
    cfg.engine.target_overall_pressure_ratio, ...
    cfg.engine.fan_pressure_ratio, ...
    cfg.engine.lpc_pressure_ratio, ...
    cfg.engine.hpc_pressure_ratio, ...
    cfg.engine.combustor_exit_temperature_K, ...
    cfg.engine.turbine_inlet_temperature_K];

expectedEngineContract = [ ...
    contract.engine.core_airflow_kg_s, ...
    contract.engine.bypass_ratio, ...
    contract.engine.target_overall_pressure_ratio, ...
    contract.engine.fan_pressure_ratio, ...
    contract.engine.lpc_pressure_ratio, ...
    contract.engine.hpc_pressure_ratio, ...
    contract.engine.combustor_exit_temperature_K, ...
    contract.engine.combustor_exit_temperature_K];

check( ...
    "Accepted APR flow, pressure-ratio split, and temperature inputs are exact", ...
    all(abs(actualEngineContract - expectedEngineContract) ...
        <= contractTolerance), ...
    "One or more accepted v0.5 APR engine inputs changed.");

%% Canonical combustor-exit temperature authority
perturbedCombustorExitTemperature_K = 1650;

cfgCanonicalOnly = cfg;
cfgCanonicalOnly.engine = rmfield( ...
    cfgCanonicalOnly.engine, ...
    "turbine_inlet_temperature_K");
cfgCanonicalOnly.engine.combustor_exit_temperature_K = ...
    perturbedCombustorExitTemperature_K;

resultsCanonicalOnly = run_turbofan(cfgCanonicalOnly);

check( ...
    "Canonical combustor-exit temperature controls station 4 and the cycle", ...
    resultsCanonicalOnly.stations.station4.Tt_K ...
        == perturbedCombustorExitTemperature_K ...
    && abs(resultsCanonicalOnly.performance.net_thrust_N ...
        - results.performance.net_thrust_N) > 1, ...
    sprintf( ...
        "Station 4 Tt %.12g K; thrust change %.12g N.", ...
        resultsCanonicalOnly.stations.station4.Tt_K, ...
        resultsCanonicalOnly.performance.net_thrust_N ...
            - results.performance.net_thrust_N));

cfgSynchronizedTemperature = cfg;
cfgSynchronizedTemperature.engine.combustor_exit_temperature_K = ...
    perturbedCombustorExitTemperature_K;
cfgSynchronizedTemperature.engine.turbine_inlet_temperature_K = ...
    perturbedCombustorExitTemperature_K;

resultsSynchronizedTemperature = ...
    run_turbofan(cfgSynchronizedTemperature);

check( ...
    "Synchronized canonical and legacy temperature fields remain compatible", ...
    resultsSynchronizedTemperature.stations.station4.Tt_K ...
        == perturbedCombustorExitTemperature_K ...
    && isequaln( ...
        resultsSynchronizedTemperature.performance, ...
        resultsCanonicalOnly.performance), ...
    "Synchronized compatibility alias changed the canonical cycle result.");

cfgInconsistentTemperature = cfg;
cfgInconsistentTemperature.engine.combustor_exit_temperature_K = ...
    perturbedCombustorExitTemperature_K;

inconsistentTemperatureRejected = false;
inconsistentTemperatureIdentifier = "";

try
    run_turbofan(cfgInconsistentTemperature);
catch temperatureError
    inconsistentTemperatureIdentifier = ...
        string(temperatureError.identifier);

    inconsistentTemperatureRejected = ...
        inconsistentTemperatureIdentifier ...
        == "TurbofanConfig:InconsistentCombustorExitTemperature";
end

check( ...
    "Inconsistent canonical and legacy temperature fields are rejected", ...
    inconsistentTemperatureRejected, ...
    "Actual error identifier: " + inconsistentTemperatureIdentifier);

check( ...
    "Accepted fixed nozzle-area literals are bit-for-bit unchanged", ...
    isequal( ...
        cfg.geometry.core_nozzle_area_m2, ...
        contract.geometry.core_nozzle_area_m2) ...
    && isequal( ...
        cfg.geometry.bypass_nozzle_area_m2, ...
        contract.geometry.bypass_nozzle_area_m2), ...
    "Core or bypass fixed effective nozzle area changed.");

actualEfficiencies = [ ...
    cfg.eff.diffuser_pressure_recovery, ...
    cfg.eff.fan_isentropic, ...
    cfg.eff.lpc_isentropic, ...
    cfg.eff.hpc_isentropic, ...
    cfg.eff.combustor, ...
    cfg.eff.hpt_isentropic, ...
    cfg.eff.lpt_isentropic];

check( ...
    "Accepted APR component efficiencies are unchanged", ...
    all(abs(actualEfficiencies - contract.efficiencies) ...
        <= contractTolerance), ...
    "One or more accepted component efficiencies changed.");

actualLosses = [ ...
    cfg.loss.core_nozzle_pressure_recovery, ...
    cfg.loss.bypass_nozzle_pressure_recovery, ...
    cfg.loss.combustor_pressure_ratio, ...
    cfg.loss.bypass_duct_pressure_ratio, ...
    cfg.loss.core_duct_pressure_ratio, ...
    cfg.loss.cooling_mixer_loss_coefficient];

check( ...
    "Accepted APR pressure recoveries and losses are unchanged", ...
    all(abs(actualLosses - contract.losses) <= contractTolerance), ...
    "One or more accepted pressure-loss inputs changed.");

actualMechanicalCoolingContract = [ ...
    cfg.mech.hpt, ...
    cfg.mech.lpt, ...
    cfg.cooling.bleed_fraction, ...
    cfg.external_loads.external_bleed_fraction, ...
    cfg.external_loads.accessory_power_extraction_W];

expectedMechanicalCoolingContract = [ ...
    contract.mechanical_efficiencies, ...
    contract.cooling_bleed_fraction, ...
    contract.external_loads];

check( ...
    "Accepted APR mechanical, cooling, and external-load inputs are unchanged", ...
    all(abs( ...
        actualMechanicalCoolingContract ...
        - expectedMechanicalCoolingContract) <= contractTolerance), ...
    "Mechanical efficiency, cooling bleed, or external load changed.");

%% Unsupported external-load rejection
cfgUnsupportedExternalBleed = cfg;
cfgUnsupportedExternalBleed.external_loads.external_bleed_fraction = 0.01;

externalBleedRejected = false;
externalBleedErrorIdentifier = "";

try
    run_turbofan(cfgUnsupportedExternalBleed);
catch externalBleedError
    externalBleedErrorIdentifier = ...
        string(externalBleedError.identifier);

    externalBleedRejected = ...
        externalBleedErrorIdentifier ...
        == "TurbofanConfig:UnsupportedExternalBleed";
end

check( ...
    "Nonzero directly supplied external bleed is rejected", ...
    externalBleedRejected, ...
    "Actual error identifier: " + externalBleedErrorIdentifier);

cfgUnsupportedAccessoryPower = cfg;
cfgUnsupportedAccessoryPower.external_loads.accessory_power_extraction_W = ...
    1000;

accessoryPowerRejected = false;
accessoryPowerErrorIdentifier = "";

try
    run_turbofan(cfgUnsupportedAccessoryPower);
catch accessoryPowerError
    accessoryPowerErrorIdentifier = ...
        string(accessoryPowerError.identifier);

    accessoryPowerRejected = ...
        accessoryPowerErrorIdentifier ...
        == "TurbofanConfig:UnsupportedAccessoryPowerExtraction";
end

check( ...
    "Nonzero directly supplied accessory extraction is rejected", ...
    accessoryPowerRejected, ...
    "Actual error identifier: " + accessoryPowerErrorIdentifier);

actualThermophysicalContract = [ ...
    cfg.thermo.R_J_kgK, ...
    cfg.thermo.gamma_cold, ...
    cfg.thermo.gamma_hot, ...
    cfg.fuel.lower_heating_value_J_kg];

check( ...
    "Accepted APR thermophysical and fuel inputs are unchanged", ...
    all(abs( ...
        actualThermophysicalContract ...
        - contract.thermophysical) ...
        <= contractTolerance .* max(1, abs(contract.thermophysical))), ...
    "Gas properties or fuel heating value changed.");

check( ...
    "Accepted corrected-parameter reference state is unchanged", ...
    all(abs( ...
        [cfg.reference.temperature_K, cfg.reference.pressure_Pa] ...
        - contract.reference_state) ...
        <= contractTolerance .* max(1, abs(contract.reference_state))), ...
    "Corrected-parameter reference temperature or pressure changed.");

actualShaftHPTContract = [ ...
    cfg.shaft.high_spool_rpm, ...
    cfg.shaft.low_spool_rpm, ...
    cfg.hpt.loading_coefficient, ...
    cfg.hpt.flow_coefficient, ...
    cfg.hpt.reaction, ...
    cfg.hpt.stage_count];

expectedShaftHPTContract = [ ...
    contract.shaft_speeds_rpm, ...
    contract.hpt_design];

check( ...
    "Accepted shaft-speed and HPT design inputs are unchanged", ...
    all(abs(actualShaftHPTContract - expectedShaftHPTContract) ...
        <= contractTolerance), ...
    "Shaft speed or accepted preliminary HPT design input changed.");

check( ...
    "CF34-10E bypass ratio is 5.4", ...
    abs(cfg.engine.bypass_ratio - 5.4) < 1e-12, ...
    sprintf("Actual BPR: %.12g", cfg.engine.bypass_ratio));

calculatedOPR = ...
    cfg.engine.fan_pressure_ratio ...
    * cfg.engine.lpc_pressure_ratio ...
    * cfg.engine.hpc_pressure_ratio;

check( ...
    "Overall pressure ratio is 29", ...
    abs(calculatedOPR - 29.0) < 1e-10, ...
    sprintf("Calculated OPR: %.12f", calculatedOPR));

check( ...
    "Public CF34 architecture is represented", ...
    cfg.architecture.fan_stage_count == 1 ...
    && cfg.architecture.lpc_stage_count == 3 ...
    && cfg.architecture.hpc_stage_count == 9 ...
    && cfg.architecture.hpt_stage_count == 1 ...
    && cfg.architecture.lpt_stage_count == 4, ...
    "Expected stage counts: 1 fan / 3 LPC / 9 HPC / 1 HPT / 4 LPT");

%% Reference calibration and baseline regression
referenceThrustError_N = ...
    results.performance.net_thrust_N ...
    - referenceThrust_N;

check( ...
    "Thrust matches CF34-10E7 reference within 10 N", ...
    abs(referenceThrustError_N) <= maximumReferenceThrustError_N, ...
    sprintf( ...
        "Error: %+.6f N; model: %.6f kN; reference: %.6f kN", ...
        referenceThrustError_N, ...
        results.performance.net_thrust_N / 1000, ...
        referenceThrust_N / 1000));

regressionThrustError_N = ...
    results.performance.net_thrust_N ...
    - expectedBaselineThrust_N;

check( ...
    "Baseline thrust regression is stable", ...
    abs(regressionThrustError_N) <= maximumRegressionThrustError_N, ...
    sprintf( ...
        "Regression error: %+.6f N", ...
        regressionThrustError_N));

regressionTSFCError_g_kN_s = ...
    results.performance.tsfc_g_kN_s ...
    - expectedBaselineTSFC_g_kN_s;

check( ...
    "Baseline TSFC regression is stable", ...
    abs(regressionTSFCError_g_kN_s) ...
    <= maximumRegressionTSFCError_g_kN_s, ...
    sprintf( ...
        "TSFC error: %+.9f g/(kN*s)", ...
        regressionTSFCError_g_kN_s));

%% Conservation and spool balances
check( ...
    "High-spool power balance closes", ...
    abs(results.residuals.high_spool_W) ...
    <= maximumPowerResidual_W, ...
    sprintf( ...
        "Residual: %.12g W", ...
        results.residuals.high_spool_W));

check( ...
    "Low-spool power balance closes", ...
    abs(results.residuals.low_spool_W) ...
    <= maximumPowerResidual_W, ...
    sprintf( ...
        "Residual: %.12g W", ...
        results.residuals.low_spool_W));

check( ...
    "Engine mass-flow balance closes", ...
    abs(results.residuals.mass_kg_s) ...
    <= maximumMassResidual_kg_s, ...
    sprintf( ...
        "Residual: %.12g kg/s", ...
        results.residuals.mass_kg_s));

check( ...
    "Cooling mixer energy balance closes", ...
    abs(results.cooling.mixer_energy_residual_W) ...
    <= maximumMixerEnergyResidual_W, ...
    sprintf( ...
        "Residual: %.12g W", ...
        results.cooling.mixer_energy_residual_W));

totalAirflowResidual_kg_s = ...
    results.mass.mdot_total_air_kg_s ...
    - (results.mass.mdot_core_air_kg_s ...
    + results.mass.mdot_bypass_air_kg_s);

check( ...
    "Total airflow equals core plus bypass airflow", ...
    abs(totalAirflowResidual_kg_s) <= maximumMassResidual_kg_s, ...
    sprintf( ...
        "Residual: %.12g kg/s", ...
        totalAirflowResidual_kg_s));

hptFlowResidual_kg_s = ...
    results.mass.mdot_hpt_kg_s ...
    - (results.mass.mdot_combustor_air_kg_s ...
    + results.mass.mdot_cooling_air_kg_s ...
    + results.mass.mdot_fuel_kg_s);

check( ...
    "HPT flow includes combustor air, coolant, and fuel", ...
    abs(hptFlowResidual_kg_s) <= maximumMassResidual_kg_s, ...
    sprintf( ...
        "Residual: %.12g kg/s", ...
        hptFlowResidual_kg_s));

%% Thermodynamic state ordering
pressureOrderingPasses = ...
    results.stations.station3.Pt_Pa ...
        > results.stations.station25.Pt_Pa ...
    && results.stations.station25.Pt_Pa ...
        > results.stations.station21.Pt_Pa ...
    && results.stations.station21.Pt_Pa ...
        > results.stations.station2.Pt_Pa ...
    && results.stations.station41.Pt_Pa ...
        < results.stations.station4.Pt_Pa ...
    && results.stations.station45.Pt_Pa ...
        < results.stations.station41.Pt_Pa ...
    && results.stations.station5.Pt_Pa ...
        < results.stations.station45.Pt_Pa;

check( ...
    "Compressor and turbine pressure ordering is physical", ...
    pressureOrderingPasses, ...
    "Expected compression pressure rise and turbine pressure drop");

temperatureOrderingPasses = ...
    results.stations.station4.Tt_K ...
        > results.stations.station41.Tt_K ...
    && results.stations.station41.Tt_K ...
        > results.stations.station45.Tt_K ...
    && results.stations.station45.Tt_K ...
        > results.stations.station5.Tt_K;

check( ...
    "Hot-section total-temperature ordering is physical", ...
    temperatureOrderingPasses, ...
    "Expected Tt4 > Tt41 > Tt45 > Tt5");

%% Nozzle behavior
check( ...
    "Core nozzle remains choked at the baseline point", ...
    logical(results.stations.station9.is_choked), ...
    sprintf( ...
        "Core nozzle Mach: %.6f", ...
        results.stations.station9.Mach));

check( ...
    "Bypass nozzle remains unchoked at the baseline point", ...
    ~logical(results.stations.station19.is_choked), ...
    sprintf( ...
        "Bypass nozzle Mach: %.6f", ...
        results.stations.station19.Mach));

%% Accepted preliminary HPT design
check( ...
    "Accepted HPT coefficients are active", ...
    abs(hpt.loading_coefficient - 1.20) < 1e-12 ...
    && abs(hpt.flow_coefficient - 0.45) < 1e-12 ...
    && abs(hpt.reaction - 0.50) < 1e-12 ...
    && hpt.stage_count == 1, ...
    sprintf( ...
        "psi=%.6f, phi=%.6f, R=%.6f, stages=%d", ...
        hpt.loading_coefficient, ...
        hpt.flow_coefficient, ...
        hpt.reaction, ...
        hpt.stage_count));

geometryPasses = ...
    hpt.mean_radius_m >= minimumAcceptedMeanRadius_m ...
    && hpt.mean_radius_m <= maximumAcceptedMeanRadius_m ...
    && hpt.blade_span_inlet_m > 0 ...
    && hpt.blade_span_exit_m > 0 ...
    && hpt.hub_radius_inlet_m > 0 ...
    && hpt.hub_radius_exit_m > 0 ...
    && hpt.tip_radius_inlet_m > hpt.hub_radius_inlet_m ...
    && hpt.tip_radius_exit_m > hpt.hub_radius_exit_m;

check( ...
    "Preliminary HPT geometry is positive and within range", ...
    geometryPasses, ...
    sprintf( ...
        "rm=%.6f m, hin=%.6f m, hex=%.6f m", ...
        hpt.mean_radius_m, ...
        hpt.blade_span_inlet_m, ...
        hpt.blade_span_exit_m));

machVector = [ ...
    hpt.rotor_inlet_absolute_mach, ...
    hpt.rotor_inlet_relative_mach, ...
    hpt.rotor_exit_absolute_mach, ...
    hpt.rotor_exit_relative_mach];

check( ...
    "Stored maximum HPT Mach is internally consistent", ...
    abs(hpt.maximum_mach - max(machVector)) < 1e-12, ...
    sprintf( ...
        "Stored: %.9f; recomputed: %.9f", ...
        hpt.maximum_mach, ...
        max(machVector)));

check( ...
    "HPT rotor-inlet absolute Mach remains below one", ...
    hpt.rotor_inlet_absolute_mach < 1.0, ...
    sprintf( ...
        "Rotor-inlet absolute Mach: %.6f", ...
        hpt.rotor_inlet_absolute_mach));

check( ...
    "HPT maximum mean-line Mach remains at or below 1.08", ...
    hpt.maximum_mach <= maximumAcceptedHPTMach, ...
    sprintf( ...
        "Maximum Mach: %.6f", ...
        hpt.maximum_mach));

check( ...
    "Project 2 HPT handoff fields are populated", ...
    all(isfinite([ ...
        results.stations.station3.Tt_K, ...
        results.stations.station3.Pt_Pa, ...
        results.stations.station41.Tt_K, ...
        results.stations.station41.Pt_Pa, ...
        results.stations.station45.Tt_K, ...
        results.stations.station45.Pt_Pa, ...
        hpt.mean_radius_m, ...
        hpt.blade_span_inlet_m, ...
        hpt.blade_span_exit_m, ...
        hpt.shaft_speed_rpm])), ...
    "Required coolant, hot-gas, geometry, and speed values must be finite");

%% Final summary
totalCount = passedCount + failedCount;

summary = struct();
summary.model_version = string(cfg.meta.model_version);
summary.total_tests = totalCount;
summary.passed_tests = passedCount;
summary.failed_tests = failedCount;
summary.failure_messages = failureMessages;
summary.net_thrust_N = results.performance.net_thrust_N;
summary.tsfc_g_kN_s = results.performance.tsfc_g_kN_s;
summary.hpt_maximum_mach = hpt.maximum_mach;

fprintf("==================================================\n");
fprintf("Acceptance-test summary\n");
fprintf("--------------------------------------------------\n");
fprintf("Passed: %d\n", passedCount);
fprintf("Failed: %d\n", failedCount);
fprintf("Total:  %d\n", totalCount);
fprintf("==================================================\n");

if failedCount > 0
    fprintf(2, "\nFailed checks\n");

    for failureIndex = 1:numel(failureMessages)
        fprintf(2, "  %s\n", failureMessages(failureIndex));
    end

    error( ...
        "v0.6 APR acceptance test failed: %d of %d checks failed.", ...
        failedCount, ...
        totalCount);
end

fprintf("v0.6 APR acceptance test PASSED\n\n");


    function check(testName, condition, detail)
    %CHECK Record and print one acceptance-test result.

        if condition
            passedCount = passedCount + 1;
            fprintf("[PASS] %s\n", testName);
        else
            failedCount = failedCount + 1;

            failureMessage = ...
                testName + " -- " + string(detail);

            failureMessages(end + 1, 1) = ...
                failureMessage;

            fprintf(2, "[FAIL] %s\n", failureMessage);
        end
    end

end
